### ISSUE TITLE
(promise) expect() instructions are not executed in finally clause without a catch clause

### ISSUE THREAD

**Issue by MarcLoupias** [jasmine/jasmine#1378] opened 2017-06-23 15:15 UTC
`jasmine-core` `2.6.4` - `expect()` are not executed in `finally` clause when there is no `catch` clause.

[Here is a plunker demo](http://plnkr.co/edit/x7nUbY7fkwFH28OW8IGD).

Run the tests with jasmine `2.6.4` : 
- the first test shows that `expect` in `finally` is not executed
- the second test is the same as the first, with a `catch` clause in addition (spy is returning a resolved promise so `catch` is not ran here). **Everything works fine in that case**.

All of this is invisible before jasmine `2.6.3`, because with `jasmine <= 2.6.2`, no `expect` are executed in `finally` clause at all.
To see this, activate the third test and link jasmine 2.6.2 instead (or any lower version) of 2.6.4 in the `index.html`.

**Comment by sgravrock** [comment] 2017-06-24 00:30
There's a lot going on in that plunker demo, which makes it hard to tell exactly what the problem is. But I'm noticing a couple of things. The first is that the expectations that you're expecting to fail might not actually be failing. When I drop `expect(true).toBe(false)` into each of the `finally` functions, I see both specs fail.

The other, possibly larger, problem is that each spec calls `done`, then does an expectation, then calls `done` again. Jasmine expects that specs won't do anything else -- and especially won't trigger any failures -- after `done`. When specs fail after calling `done`, Jasmine can't reliably associate the failure with the spec that caused it.
 
Try changing your specs to only call `done` from the `finally` function, and make sure that the expectations that should fail actually are failing. I hope this helps. Thanks for using Jasmine!

**Comment by MarcLoupias** [comment] 2017-06-24 07:18
You are right with expectations, the issues seems to be with spies only !

I have modified the plunker to be more accurate. I have commented the lines where the issue is.

**Comment by sgravrock** [comment] 2017-06-26 19:26
I added a bit of logging and saw that`uiLoaderServiceMock.disable` is being called after its calls are checked in the test that doesn't call `catch`. The `catch` call (or another `then`, for that matter) delays processing of the `finally` function until after `uiLoaderServiceMock.disable` has been called. So it looks like the expectations are behaving correctly in both cases, but one of them is running before the behavior that it's trying to test has happened.

It looks like what you need is a way to ensure that the code you've passed to `finally` doesn't get called until after Angular is done doing whatever it does that causes `uiLoaderServiceMock.disable` to be called. You'll probably get better help with that if you ask in an Angular forum.

**Comment by MarcLoupias** [comment] 2017-06-27 17:29
I am not sure i have understood. Are you saying the issue is in the `$q` AngularJS service ?

**Comment by sgravrock** [comment] 2017-07-05 16:50
No, I'm saying that your test runs two pieces of code in what is essentially a random order and then assumes that one of them happens before the other. It might be helpful to think of the promise `then` and `catch` methods as saying "and then do this other thing later on, when you get a chance". 

In the plunker demo that you posted, `userService.load` creates two independent promise chains: one that gets resolved when loading finishes, and then a separate one that disables the `uiLoaderService` at some point in the future. Then the spec chains off of the first promise to check the calls to the `disable` method at some other point in the future. Because the code doesn't do anything to ensure that one of those actions is caused by the other, they could happen in either order. And making changes like adding additional `.then` or `.catch` calls can certainly change the ordering.

If you want to write this kind of test, you'll probably need to modify your `userService` to expose a promise that resolves after `uiLoaderService.disable` is called. (Or an event, or some other similar mechanism.) Then put the test code that checks whether `uiLoaderService.disable` was called in a `.then` off of that promise, rather than off of the one returned by `userService.load`.

**Comment by MarcLoupias** [comment] 2017-07-12 16:51
> I'm saying that your test runs two pieces of code in what is essentially a random order and then assumes that one of them happens before the other

I am maybe missing something on promise but there is no random order.

The tested code is a promise with a `then`, a `catch` and a `finally`.

So the order is `then` then `finally` or `catch` then `finally`. It cannot be different.

According to the [AngularJS `$q` doc](https://docs.angularjs.org/api/ng/service/$q) : 

> allows you to observe either the fulfillment or rejection of a promise, but to do so without modifying the final value. This is useful to release resources or do some clean-up that needs to be done **whether the promise was rejected or resolved**.

This is exactly what i am doing here. I enable a loader in the UI, i start an http request, then i use the `finally` clause to disable the loader disregarding to the request result (`then` or `catch`).

This is the implementation.

For the testing part, i want to expect the `loader.disable` function is called when it have to be called. So after the http request resolve or rejection.

What i am understanding from your explanation is : The `finally` close inside the `load` function is not executed before the `then` clause execution in the spec. 

This is a really weird behavior, because i assume the `then` clause in the spec is executed after the `resolve` or the `reject` in the `load` function, so i assume the `finally` clause in the load function is **also** executed before.

In the end, the `finally` clause in the spec should **always** be executed the last !

I cannot see what i am missing here it makes me feel really bad !!

**Comment by slackersoft** [comment] 2017-07-18 04:47
It looks like you're still potentially calling `done` multiple times. Once in the `catch` (`done.fail` is still `done`) and then again in the `finally`. Once an async spec has told Jasmine that it is `done`, Jasmine will move on in its queue of specs and expectations that run may not get associated with the correct spec (if at all). 

If you're going to call `done` and `done.fail` in your `then` and `catch` respectively, you probably shouldn't have a `finally` for that promise, but figure out a different way to check that assertion.

Hope this helps. Thanks for using Jasmine!

**Closed** 2017-10-26 19:27 UTC
