### ISSUE TITLE
CIA: Community, Interfacing and Attitude

### ISSUE THREAD

**Issue by Usnul** [jasmine/jasmine#1571] opened 2018-06-21 08:23 UTC
Jasmine is an amazing project, one that I love and have personally been using for nearly a decade.

I have been tracking participation of core contributors of jasmine over the past few days here and in related projects. Here's what I have noticed and have an issue with:
* Presumption of Incompetence. Assumption is made that the reporter has made a mistake and no issue exists unless proven otherwise.
* Dismissal. I have often read "Thanks for using jasmine!" in a comment where the comment uses polite words to say "it is not important to us".
* Defensiveness. A lot of critique of the project is viewed as an attack on the project and its contributors, this makes any further discussion a lot less productive.
* Shifting the blame. Jasmine is used by many other projects and is typically a component of a larger infrastructure in real-world usage, which means that it is rarely used in isolation. I have read a lot of comments along the lines of "You use Jasmine with X, please address your problems to X instead of Jasmine" or "We noticed that you use Jasmine with tests, please address your problems with your tests!"

I believe the above points are making jasmine an unwelcoming community and is a net negative for the project as a whole and would like to invite a discussion on how to address these.

### Example
here is a thread that may serve as anecdotal evidence: https://github.com/jasmine/jasmine/issues/1570

the overview goes like so:
- A new person (A) presents a problem
- Senior member (S) comments quoting a quote of A back and claiming "can't reproduce"
- A corrects S on the reasonable assumption that reproduction was not attempted
- S responds with `I would also urge you to be careful and considerate when telling others what they have and haven't done. We've invested a significant amount of time [...]`
- S closes the issue
- S locks the issue as "too heated"

**Comment by slackersoft** [comment] 2018-07-21 00:56
I'm going to be short here, since you've expressed a preference for the Jasmine maintainers not to "use polite words" when discussing the project.

We get a wide variety of issues logged here on github. I try to answer them as best as I can, but I am just one person, and have a life outside of maintaining Jasmine. My questions on issues are generally meant to uncover more details to help solve the problem a user has, and sometimes the solution can be to test your code in a different way. Sometimes, the issue is caused by interactions with other libraries. Specifically with Karma and Angular, some of the other libraries, like Zone.js, actually reach in and "monkey-patch" parts of Jasmine.

I also don't appreciate the multiple issues _you_ have stirred up here (because the issue you reference was created by you). The issue in question (#1570) was a duplicate of another issue (#1327) that has been discussed extensively, including a number of changes to Jasmine to help alleviate the issue. We have been unable to reproduce with Jasmine alone, which makes it much harder to pinpoint where in Jasmine might be causing the problem. You then accused me and other maintainers of not even trying to reproduce the issue:

> Your choice of words is not very accurate. You didn't try to reproduce this issue. 

Note that you didn't say "reasonable attempt" as you indicate here, but none at all. Because of this and your note that

> My post is not really a call for help,

I then closed and locked the issue.

**Closed by slackersoft** 2018-07-21 00:56 UTC

**Comment by Usnul** [comment] 2018-07-26 12:35
Dear @slackersoft ,

Thank you for your response, I appreciate your open attitude. Your explanation is reasonable, however, it's quite contrarian, with respect and in friendly spirit - I would ask you to read what I have written here as constructive criticism for the project as a whole, not of your person specifically. Personally - I do not want to "fight" you or "win", I wanted to provide feedback with a hope that it may help make project as a whole better. 

There is no doubt in my mind that the project is doing exceedingly well as is, the testament to that is success of jasmine and it's widespread adoption.

As such, I wish _you_ a wonderful time of the day and I impart a big "thank you" for all your work so far.
