### ISSUE TITLE
Cannot spy on individual functions that are individually exported

### ISSUE THREAD

**Issue by kevinlbatchelor** [jasmine/jasmine#1414] opened 2017-08-22 17:31 UTC
Having done a lot of research I cannot find a way to mock functions that are exported with no parent object. For example I'm trying to mock functions exported the following way:

    module.exports = function thing(event) {};

OR in ES6

    export function thing(event) {};

When importing these into a test file I try importing like this:

    import {thing} from 'emvio-util-responses;  

    //call some function that calls thing()

    spyOn(???, 'thing').and.returnValue({});
    expect(???.thing).toHaveBeenCalled();

I have tried many ways of accomplishing this but the mock is not called.
Some suggest importing * and providing an alias as a parent object. like this:

    import * as SomeObj from 'emvio-util-responses;  

    //call some function that calls thing()

    spyOn(SomeObj , 'thing').and.returnValue({});
    expect(SomeObj .thing).toHaveBeenCalled();

This doesn't work.

Others suggest using the window object

    spyOn(window, 'thing').and.returnValue({});

But I'm in node :(.

**Comment by slackersoft** [comment] 2017-08-23 00:49
How are you expecting to use the spied on function in your actual implementation. Node.js most likely isn't going to use the spy when you `import` in the implementation. If you just need to pass in a fake implementation, you can just use `jasmine.createSpy` to get a spy function that can be passed to the implementation.

The way that `spyOn` works is by replacing the property for the function with a function that has all of the tracking properties on it, which means that the spec and implementation have to share the same object that holds the spy.

Hope this helps. Thanks for using Jasmine!

**Comment by sgravrock** [comment] 2017-11-03 01:00
I'm closing this as there hasn't been any activity for a while and I don't think it's something that we can realistically fix.

**Comment by kevinlbatchelor** [comment] 2018-04-18 00:02
Inability spy on things easily is actually the reason a lot of people are leaving Jasmine, that said we found some work around that are awkward, however in alot of cases its just easier to move to Jest, I wish I had some time to dig into this cause there is alot about Jest that I don't like.

**Comment by slackersoft** [comment] 2018-04-18 00:52
I would love to hear about how Jest or Mocha or whichever other testing frameworks you're using are able to accomplish what you're trying to do here. As far as I can tell, it is more of a limitation of Node.js itself and the ability (or lack thereof) to change the functions exported by another module.

**Comment by jscharett** [comment] 2018-05-30 13:09
Ran across this thread as I'm running into same issue.  Looks like Jest has the ability to [mock modules](https://facebook.github.io/jest/docs/en/mock-functions.html#mocking-modules) that are required by other modules.  Looks like tit can also mock Implementations, which is what @kevinlbatchelor is looking for I believe.  Can Jasmine do these?

**Comment by slackersoft** [comment] 2018-06-01 00:37
@jscharett Jasmine should be able to spy on functions from a module in the same way that Jest does with the module mocking.

```javascript
var foo = require('foo');
jasmine.spyOn(foo, 'bar');
```

Should replace the `bar` function from the `foo` module, in much the same way as Jest does for all functions on the module.

The original poster was asking for the ability to spy on a function that is exported directly, which doesn't give Jasmine a consistent place between the spec and implementation to save the spy.

Hope this helps. Thanks for using Jasmine!

**Comment by jscharett** [comment] 2018-06-01 08:57
Would [this ](https://railsware.com/blog/2017/01/10/mocking-es6-module-import-without-dependency-injection/)do the trick?
```
/*bar.js*/
export function bar(){}

/*foo.js*/
import { bar } from 'bar';
export function foo(){bar();}

/*foo.spec.js*/
import * as Bar from 'bar';
jasmine.spyOn(Bar, 'bar');
```
Not sure about using the commonjs syntax, but looks like its possible based off of what Jest is doing.
```
jest.mock('../foo'); 
const foo = require('../foo');
```

**Comment by goliney** [comment] 2018-12-13 13:45
> import * as ngrx from '@ngrx/store';
>spyOnProperty(ngrx, 'select')

Didn't work for me, unfortunately. Failed with:
>Error: <spyOn> : myFunctionName is not declared writable or has no setter

**Comment by momegas** [comment] 2019-01-05 17:39
Also facing the same issue

**Comment by gund** [comment] 2019-01-27 00:31
Approach with `spyOnProperty` actually works but it is doing something different than just `spyOn`.

I actually had an error saying `TypeError: Object(...) is not a function` so it was obvious something did change but not quite the way I expected.

What really happened is `spyOnProperty` actually replaced the function I was trying to spy on with a getter function that was a spy now, and when it was accessed `undefined` was returned by default and then it was trying to call function on undefined which led to that error.

So I needed to return my spy for that property and everything worked:

```ts
import * as metadata from './metadata';

it('should...', () => {
  // First create your actual spy
  const setPropertyTypeSpy = jasmine.createSpy('setPropertyTypeSpy');
  // Then replace original function with your spy
  spyOnProperty(metadata, 'setPropertyType').and.returnValue(setPropertyTypeSpy);

  // Do your test

  expect(setPropertyTypeSpy).toHaveBeenCalled(); // This will work now!
});
```

I still believe there is something wrong with `spyOn` function, I think it should actually do what I did inside...

**Comment by slackersoft** [comment] 2019-02-05 19:04
Jasmine's `spyOnProperty` is intended for installing a spy over a `get` or `set` property created with `Object.defineProperty`, whereas `spyOn` is intended for installing a spy over an existing `function`. @gund, it sounds like what you really want is just `spyOn`.

Hope this helps. Thanks for using Jasmine!

**Comment by gund** [comment] 2019-02-05 20:15
@slackersoft you are right, I really want to use just `spyOn`, BUT as many of us explained before (including me) it does not work with objects from other modules thus rendering `spyOn` broken.

So we came up with workaround by using `spyOnProperty` however it is not the way it was intended to be used, right?

So I think Jasmine as a testing library must provide first class support for mocking module exports but it's not currently because implementation of `spyOn` is buggy/not compatible with module exports...

Maybe it would make sense to add another function called `spyOnModule`:
```ts
function spyOnModule(modulePath: string, exportSymbolName: string): jasmine.Spy;
```
And it's implementation will be something like:
```ts
function spyOnModule(modulePath: string, exportSymbolName: string): jasmine.Spy {
  const spy = jasmine.createSpy(`Spy of ${modulePath}#${exportSymbolName}`);
  spyOnProperty(require(modulePath), prop).and.returnValue(spy);
  return spy;
}
```

P.S. I'm not sure if `require()` will really work but it's just an example, we can very well pass already imported module from `import * as m from './module/path'`.

**Comment by hauner** [comment] 2019-02-10 11:25
I have the same issue with functions exported from a library created with angular cli `ng generate library mylib` which are imported with `import * as ml from 'mylib'`.

`spyOn` works with `import * as ml` if the function is defined in the same angular project, but not when it is imported from another library project.

The `spyOnModule` workaround from @gund fixed that for me.

**Comment by slackersoft** [comment] 2019-02-11 19:27
I want to make sure I'm understanding this use case and the issues you're seeing with it. This is my current understanding so far. Given a function exported directly from some module, either

```javascript
export function bar() {}
```

or

```javascript
module.exports.bar = function() {}
```

You would like to be able to install a spy on `bar` such that the code under test actually gets the spy and not the original implementation.

This is potentially going to depend on which `import`/`require` mechanism you actually use and possibly even the load order of the spec and implementation. If both sides load the full module either with `require` or `import * as foo`, I would expect `spyOn` to work properly (and I think I'm seeing folks here saying that it does).

It's possible that in order to really make `spyOn` work, you'll need to actually use `require` for the full module at least in the spec in order to allow things to get installed correctly. I'm open to adding an additional function to Jasmine's interface, but I want to make sure that we can't solve this with the existing interface.

**Comment by hauner** [comment] 2019-02-11 23:25
I created a minimal test project to show the issue. Now spying doesn't work in both cases with `spyOn`. Grmpf ;-) 

It fails with: `Error: <spyOn> : spyMethod is not declared writable or has no setter`.

I found this webpack [issue](https://github.com/webpack/webpack/issues/6979), which says 

> When exporting functions using `export function foo` and importing using `import * as bar`, they are compiled to getters/setters in Webpack 4.

which explains why `spyOn` fails in that case and why it works using `spyOnModule`.

No idea why I have two different behaviors in my project.

**Comment by slackersoft** [comment] 2019-02-22 01:21
Ok, I think I've got a handle on this now. I would be happy to review a pull request to add something like `spyOnModule`. I would like it to be able to handle either the case of `import` using getters/setters or just a plain replacement. Basically it should work anywhere `spyOn` does currently so folks don't have to think about whether to use this across different setups.

Re-openning.

**Comment by gund** [comment] 2019-02-22 08:18
@slackersoft I can create a PR for this.

Just to clarify, you want to have `spyOnModule` that will support both spying on normal functions as well as functions declared as getters?

Also in my example of  `spyOnModule` above does it make sense to do `require` or should it accept already imported module object?

**Comment by slackersoft** [comment] 2019-02-23 01:44
I think it makes sense for a `spyOnModule` to also spy on a normal function as well as the function returned by a getter. This should allow it to be used if WebPack changes how it creates those imports or between different packaging systems.

I think it will make the most sense to have `spyOnModule` accept an already `require`d module. This allows it to also run in a browser or other non-CommonJS environment.

**Comment by ellipticaldoor** [comment] 2019-02-24 21:23
This works for me

``` typescript
import * as helpers from '@root/helpers'
import { decideWinner } from '@root/helpers/combat'

beforeEach(() => {
  jest.restoreAllMocks()
})

cases(
  'decideWinner',
  ({ prepare, expected }) => {
    const getRandomPercentageMock = jest
      .spyOn(helpers, 'getRandomPercentage')
      .mockReturnValueOnce(prepare.randomPercentage)

    const winner = decideWinner(prepare.attackerChanceToWin)

    expect(getRandomPercentageMock).toHaveBeenCalledTimes(1)
    expect(winner).toEqual(expected.winner)
  },
  {
    'attacker wins': {
      prepare: {
        randomPercentage: 70,
        attackerChanceToWin: 80,
      },
      expected: {
        winner: 'attacker',
      },
    },
    'defendant wins': {
      prepare: {
        randomPercentage: 90,
        attackerChanceToWin: 80,
      },
      expected: {
        winner: 'defendant',
      },
    },
  },
)
```

**Comment by slackersoft** [comment] 2019-02-26 01:37
@ellipticaldoor it looks like you're actually using Jest for all of that testing and not Jasmine, so I'm not sure this will apply here.

**Comment by kevinlbatchelor** [comment] 2019-03-07 00:52
We did find a hacky work around for that Jasmine + Webpack mocking using new es6 export syntax while calling functions in the same file.

If you file has a function you wanto mock say:
`export function goData() {}`

and later in the file you call that funciton:
`let result  = goData() {}`

Jasmine cannot mock or spyOn this function.

However if when you call this function you append it to exports like this:
`let result  = exports.goData() {}`

Jasmine can now spy on this function in the tests:
`
import * as allFunctions from './myFile';

spyOn(allFunctions , 'goData')
`
This is super hacky but it works. One downside to doing this is if you tack your function calls on to exports it will break your IDE ability to refactor or navigate or autocomplete stuff. We decided not to this and instead we just move these functions we need to mock into a different files, which can be tricky or we just all through the functions if we can.

**Comment by slackersoft** [comment] 2019-03-14 00:36
Unfortunately, @kevinlbatchelor, I don't think that use case is something that can be solved, since Jasmine doesn't have access to the scope inside your module to make changes.

**Comment by josh08h** [comment] 2019-04-01 18:27
I'm currently faced with the same issue:

```
// utils.js
export const helloWorld = () => 'HelloWorld';


// foobar.js
import { sayHello } from './utils';
export const foobar = () => {
  return sayHello();
};


// foobar-spec.js
import { foobar } from './foobar';
import * as utils from './utils';

describe('foobar', () => {
  it('works', () => {
    spyOn(utils, 'sayHello').and.returnValue('foobar');
    expect(foobar()).toEqual('foobar'); // Fails since sayHello() calls original and returns 'hello'
  });
});
```

Any suggestions?

**Comment by slackersoft** [comment] 2019-04-02 00:40
@josh08h this is going to largely come down to what code is being generated by your bundler/compiler of choice as to whether this is mockable. If `import { sayHello } from './utils';` becomes `const sayHello = require('./utils').sayHello` then the original function will already be saved off into a local variable and there isn't anything Jasmine (or any other library) can to to replace a local variable. However, if it becomes `const utils = require('./utils')` and usages are `utils.sayHello()`, then replacing the `sayHello` function on the object returned by `require` should work fine.

Hope this helps. Thanks for using Jasmine!

**Comment by josh08h** [comment] 2019-04-02 06:00
@slackersoft thanks for the help. I have decided to go against named exports and instead I will export a default object which will look like `export default { sayHello: sayHello }`. This should do it. 👍

**Comment by llorenspujol** [comment] 2019-06-12 10:14
I have experienced this issue recently in a Angular/Typescript project. We solved it setting the tsc ouput module to be **commonjs** in our testing tsconfig:

tsconfig.spec.json:
```
"compilerOptions": {
     ....
      // force commonjs module output, since it let mock exported members on modules to anywhere in the application (even in the same file)
      "module": "commonjs",
  },
```

The resultant output of any exported member of a module in commonjs would be like: `exports.myFunc = function() {}`. This led use spyOn without worries since it is wrapped on the 'exports' object. One great use case of that, is that it would be mocked anywhere, **including the usages in its own file**!

Example:

```js
// some-module.js
export function functionToMock() {
     return 'myFuncToMock';
}
export function functionToTest() {
     return functionToMock();
}

// testing-module.spec.js
import * as SomeModule from ./some-module
spyOn(SomeModule, 'functionToMock').and.returnValue('mockedCorrectly');
SomeModule.functionToTest().toBe('mockedCorrectly')
```

So, in resume, compile to **commonjs** module when testing may solve your issue, hope this helps someone:)

**Comment by antonpegov** [comment] 2019-07-02 08:57
> So, in resume, compile to **commonjs** module when testing may solve your issue, hope this helps someone:)

This is the best workaround! Thanks!!!

**Comment by imjeen** [comment] 2019-09-11 09:47
By the way, how to support the import/export syntax in your jasmine code?

**Comment by DrNecromant** [comment] 2019-10-11 14:04
Guys,

Solution for read-only methods is rather simple. Spy on GET property only.

import * as rxjs from 'rxjs';
import { timer } from 'rxjs';

const funcSpy = jasmine.createSpy('name-of-spy').and.returnValue(<here-is-you-spy-code>);
spyOnProperty(rxjs, 'timer', 'get').and.returnValue(funcSpy);

https://stackoverflow.com/questions/53296840/import-as-jasmine-spyon-not-writable

**Comment by yazonnile** [comment] 2019-12-03 12:09
Works for me

```js
import { thing } from 'emvio-util-responses';

jasmine.createSpy('thing or other name', thing).and.callThrough();
thing();
expect(thing).toHaveBeenCalledTimes(1);
```

```json
{ "jasmine": "^3.5.0", "jasmine-core": "^3.5.0" }
```

**Comment by gund** [comment] 2020-03-08 01:20
Actually setting `"module": "commonjs" in `tsconfig.json` for tests fixes this issue and you can use `spyOn` again.
I think this issue may be closed.

**Comment by C0ZEN** [comment] 2020-03-13 13:27
@gund no, I still have an issue since upgrading to Angular 9.
I tried all the hacks above and @llorenspujol answer is nice for the tests inside the library.
Using common-js is actually the solution in that case.
Nevertheless, once in an application using the builded library with ng-packagr, the common-js hack is not working anymore.
You can check out a more complete example of my problem on this related issue https://github.com/angular/angular-cli/issues/17207

**Comment by shwetasingh237** [comment] 2020-04-10 02:50
Adding "module": "commonjs" in tsconfig.spec.json worked for me. This lets you mock exported functions. You can spyOn the functions like so:

1. abc.spec.ts
import * as MyLibfrom 'my-lib';
const isNotEmptyStringSpy = spyOn(MyLib, 'isNotEmptyString').and.returnValue(false);

2. tsconfig.spec.json
"compilerOptions": {
"outDir": "../out-tsc/spec",
**"module": "commonjs",**
"target": "es5",
"types": ["jasmine", "node"]
}
Note that you need to add module in **tsconfig.spec.json** not in tsconfig.json.

**Comment by JoannaFalkowska** [comment] 2020-08-20 10:44
`"module": "commonjs"` in `tsconfig.spec.json` didn't help at all in my case.

When using `fixedSpyOn` from [this](https://github.com/jasmine/jasmine/issues/1414#issuecomment-460787052) comment I get `Property myExportedFunction does not have access type get`. Does anyone know what can this be caused by?

**Comment by danylobilokha** [comment] 2020-09-28 12:47
I firstly mocked with jest whole module
```
import * as utilities from '.../utilities';

jest.mock('.../utilities', () => ({
  ...jest.requireActual('.../utilities'),
  doSomeStuff: jest.fn(),
}));
```

and then if I need to have some value as return I used jasmine
```
spyOn(utilities, 'doSomeStuff').and.returnValue(whatever);
```

**Comment by EskalonaD** [comment] 2020-10-20 17:39
I solve this with:
`import  * as wrapper from '<place>';`
`spyOn(wrapper, 'default').and.callFake(....)`

**Comment by JoannaFalkowska** [comment] 2020-10-20 18:09
@EskalonaD This is exactly what I ended up doing! Thank you for writing down this answer for others.

**Comment by kekel87** [comment] 2020-10-29 08:34
Hello, I tried all solution posted here (execpt jest stuff (because we use jasmine)).

`"module": "commonjs"`  doesn't change anything and I think this is not the right approach (change of test context compared to normal operation).

@DrNecromant solution got:
`<spyOnProperty> : default is not declared configurable`

@EskalonaD solution got:
`<spyOn> : default is not declared writable or has no setter`

My context: 

`"@angular/*": "~10.2.0",`
`"jasmine-core": "~3.6.0",`
`"typescript": "~4.0.2",`

```typescript
import Swiper, { Keyboard, Mousewheel, Navigation, Pagination } from 'swiper';
...
ngAfterViewInit(): void {
  this.swiper = new Swiper('.swiper-container', { someOptions });
}
```
I just want to mock Swiper constructor and check if has call with expected arguments 🤷 (unit test)


I've tried all these weird things, but none of them work:

```typescript
const classSwiperMock = jasmine.createSpy('classSwiperMock').and.callFake(() => console.log('constructor'));
// @ts-ignore
spyOn(swiper, 'default').and.callFake(() => {
  console.log('Hello there');
  return swiper.Swiper;
}); // FAIL
spyOnProperty(swiper, 'default', 'get').and.callFake(() => {
  console.log('Hello there');
  return swiper.Swiper;
}); // FAIL
spyOnProperty(swiper, 'Swiper', 'get').and.returnValue(classSwiperMock); // FAIL
spyOnProperty(swiper, 'Swiper', 'get').and.callFake(() => console.log('Hello there')); // FAIL

spyOnAllFunctions(swiper.Swiper.prototype); // FAIL
(swiper.Swiper.prototype.constructor as jasmine.Spy).and.callFake(() => console.log('constructor')); // FAIL
Object.defineProperty(swiper.Swiper.prototype, 'constructor', classSwiperMock); // FAIL
Object.defineProperty(window, 'Swiper', classSwiperMock); // FAIL
swiper.Swiper.prototype.constructor = classSwiperMock; // FAIL
// @ts-ignore
spyOn(swiper.Swiper.prototype, 'constructor').and.callFake(() => console.log('constructor')); // FAIL

spyOn(swiper.Swiper, 'use'); // This work because is static
```

I wonder if it will be possible one day, maybe there is a better approach?

**Comment by lyleunderwood** [comment] 2020-11-09 19:09
It seems like there are a lot of different things going on in this issue, but if you're in a babel environment, check out [babel-plugin-rewire](https://github.com/speedskater/babel-plugin-rewire) as a potential solution.

**Comment by thw0rted** [comment] 2020-11-23 13:22
@kekel87 you didn't show us where `swiper` comes from -- that is, the first argument to all your `spyOn` calls.   I got this working as:

````ts
// shared.module.ts
export function replaceMe() { ... }

// OtherCode.spec.ts
import * as SharedModule from  "./shared.module";


beforeEach(() => {
  const replaceSpy = jasmine.createSpy("replaceMe")
        .and.callFake(() => "desired value");
  spyOnProperty(SharedModule, "replaceMe", "get").and.returnValue(replaceSpy);
});

it("works", () => {
  expect(thingThatCallsReplaceMe()).to.work();
});
````

I was already running with the relevant `tsconfig` set up to target commonjs, but I thought everybody had to do that.  Karma can technically load `esnext` modules instead, but in that case, `tsc` will emit lines like `import { Input } from "@angular/core"` verbatim, and of course the browser has no idea how to do node-style module resolution.  Maybe people are getting messed up because they stick Babel in the middle somewhere?

**Comment by kekel87** [comment] 2020-11-23 13:45
@thw0rted `swiper` is a 3rd party library.

We import It like that : `import Swiper, { Keyboard, Mousewheel, Navigation, Pagination } from 'swiper';`

For `tsconfig` file, we are aligned with the angular-cli file: https://github.com/cexbrayat/angular-cli-diff/blob/10.2.0/ponyracer/tsconfig.spec.json

**Comment by thw0rted** [comment] 2020-11-23 16:01
Ah, you wrote `spyOn(swiper, ...)` -- note the lower-case "S".  That's why I was confused.  

I don't use the Angular CLI so I had to put together my own Karma config that builds through karma-webpack.  As I mentioned above, this meant having TS emit CommonJS modules, which seems to be the key part of making `spyOnProperty` work.  Have you tried `module: "commonjs"` in your test `tsconfig`?

Also, have you tried `import * as Swiper from "swiper"`?  I'm not sure how it works with `esModuleInterop` / `allowSyntheticDefaultImports` or whatever, but I think in some cases `import * as Swiper` gives different emit from `import Swiper` -- and I can vouch that the former syntax works (with CommonJS).

**Comment by Sekin** [comment] 2020-12-21 22:55
> `import * as wrapper from '<place>';`
> `spyOn(wrapper, 'default').and.callFake(....)`

This answer worked for me, but I had to prefix my functions with `this`.
In your `<place>` file:
`    export function someFunc() {
       return this.default();
    }
`

`    export function default() {
       return 'something';
    }
`
In your spec file:
`spyOn(wrapper, 'default').and.callFake(() => 'someOtherValue');`

**Comment by thw0rted** [comment] 2020-12-22 10:42
Did you only need the `this` for a function that is actually called "default"?  `default` is a keyword and you really shouldn't use it to name variables, functions, classes, etc, even if the language technically allows you to.

**Comment by pfeileon** [comment] 2021-02-15 13:58
> Ok, I think I've got a handle on this now. I would be happy to review a pull request to add something like `spyOnModule`. I would like it to be able to handle either the case of `import` using getters/setters or just a plain replacement. Basically it should work anywhere `spyOn` does currently so folks don't have to think about whether to use this across different setups.
> 
> Re-openning.

So it took almost 2 years to grasp the issue. It's now 1 week away from being 2 years since that.
Btw: I think that the Jest troll comments are hilarious.

**Comment by StudioSpindle** [comment] 2021-07-05 13:56
This is still an issue. Tried every workaround posted here but no luck. Only workable way is by using Jest. But in the project I'm currently working on that is not an option. Would love to see an alternative for this in Jasmine.

**Comment by sgravrock** [comment] 2021-07-05 17:05
This is now covered in the FAQ: https://jasmine.github.io/pages/faq.html#module-spy

**Comment by StudioSpindle** [comment] 2021-07-05 18:11
Thanks for the info @sgravrock.

Having some sort of implementatino of `spyOnModule` isn't desirable anymore?

**Comment by sgravrock** [comment] 2021-07-05 19:03
> Having some sort of implementation of spyOnModule where you'd be able to mock out a single exported function outside of an class or object isn't desirable anymore?

I'm not quite ready to say no to this but I *am* leaning in the direction of no, or at least not now. My biggest concerns:

* There would need to be at least three implementations: One for CommonJS modules with read-only properties, one for ES modules using the current experimental loader API, and one for the eventual stable loader API. That's assuming that the experimental loader API has been stable from Node 12-16 *and* that it won't change again before the stable API is released. Neither of those assumptions is safe. If we were to add support for module mocking now, it'd almost certainly break at least once in the future as new Node versions come out. 

* What happens when someone is using modules at the source level, but everything has been run through Webpack (or any of the other JS bundlers) before it's loaded? Can the feature work in those configurations? When it fails, can it provide clear enough diagnostics to help users (who are often unfamiliar with how their code is packaged) understand and fix the issue? Think "boot camp student who just started their first Angular project" here, not "webpack expert".

* Performance. Jest appears to have overhead roughly proportional to the size of the module graph loaded. I've seen test suites for components that use Material UI (a big, heavily interconnected library) spend up to 10x as much time in Jest's setup and teardown as in the actual tests. I haven't been able to prove it, but I suspect that this is due to the bookkeeping needed to enable module mocking and still keep tests isolated from each other. How likely is it that we can do better? A feature like this really ought to cost nothing except when it's actually used, and I haven't seen that done yet.

* It would have to be a Node-only feature. That's not necessarily a deal-breaker but it is a pretty big negative. We try to maintain as much parity as possible between Node and browsers.

* Although module mocking is a useful tool, it tends to be overused. When it's readily available, teams tend to use it for everything. The result is more tightly coupled code and flakier test suites. I haven't entirely made up my mind about how opinionated Jasmine should be when it comes to features that are very popular but lead to worse outcomes, but it's a factor. It certainly doesn't encourage me to take on maintenance of something that's likely to throw a bunch of extra work at us in the future.

My biggest concern is the support and maintenance burden. All in all, I think it's probably best to rely on third party libraries for now and revisit this. It would make sense to revisit it if Node provides a stable ES loader module API that's good enough to support module mocking. But I'm open to further discussion especially if you know something that contradicts what I've said.

**Comment by blingerson** [comment] 2021-08-12 01:37
So use Jest?

**Comment by coyoteecd** [comment] 2021-09-08 08:23
Ran into this again in one of my projects. We already use commonjs for unit tests, which lets us spy on functions exported from our own modules; however one of the packages we use is now targeting ES6, so tests that were spying on functions exported by that library now give the `is not declared writable or has no setter` error.

Found a workable hack that may serve as inspiration for others using jasmine, which does not degrade performance and had no side-effects in our test suite, see https://github.com/facebook/jest/issues/6914#issuecomment-654710111

Basically, we use jasmine in a Node environment, and we already have a unit-test-runner.ts file that configures and starts jasmine.
In that file, I added the monkey-patch for Object.defineProperty:
```
// monkey-patch for ES6 imports
const { defineProperty } = Object;
Object.defineProperty = function(object, name, meta) {
  if (meta.get && !meta.configurable) {
    // it might be an ES6 exports object
    return defineProperty(object, name, {
      ...meta,
      configurable: true,
    });
  }

  return defineProperty(object, name, meta);
};

// run jasmine
const runner = new Jasmine({});
runner.loadConfig(....);
runner.execute();
```

Then I could use `spyOnProperty` to return a spy function on the getter of the original function
```
import * as typeorm from 'typeorm';

describe('example', () => {

  it('test', () => {
    // old code that did not work:
    // spyOn(typeorm, 'getConnection');

    // new code that does
    spyOnProperty(typeorm, 'getConnection', 'get').and.returnValue(jasmine.createSpy());
  });
});
```

**Comment by coyoteecd** [comment] 2021-09-08 08:37
Ran into this again in one of my projects. We already use commonjs for unit tests, which lets us spy on functions exported from our own modules; however one of the packages we use is now targeting ES6, so tests that were spying on functions exported by that library now give the `is not declared writable or has no setter` error.

Found a workable hack that may serve as inspiration for others using jasmine, which does not degrade performance and had no side-effects in our test suite, see https://github.com/facebook/jest/issues/6914#issuecomment-654710111

Basically, we use jasmine in a Node environment, and we already have a unit-test-runner.ts file that configures and starts jasmine.
In that file, I added the monkey-patch for Object.defineProperty:
```
// monkey-patch for ES6 imports
const { defineProperty } = Object;
Object.defineProperty = function(object, name, meta) {
  if (meta.get && !meta.configurable) {
    // it might be an ES6 exports object
    return defineProperty(object, name, {
      ...meta,
      configurable: true,
    });
  }

  return defineProperty(object, name, meta);
};

// run jasmine
const runner = new Jasmine({});
runner.loadConfig(....);
runner.execute();
```

Then I could use `spyOnProperty` to return a spy function on the getter of the original function
```
import * as typeorm from 'typeorm';

describe('example', () => {

  it('test', () => {
    // old code that did not work:
    // spyOn(typeorm, 'getConnection');

    // new code that does
    spyOnProperty(typeorm, 'getConnection', 'get').and.returnValue(jasmine.createSpy());
  });
});
```

**Comment by thw0rted** [comment] 2021-09-08 08:48
@coyoteecd I noticed you said your test runner is a TypeScript file.  Do you have a repo or something you could point to that shows how you've set it up?  I recently switched from `karma-webpack` (with the Angular compiler plugin building TS) to `karma-typescript`.  The latter comes with a transform that passes ES6 deps through Babel during the build process, which I *think* neatly sidesteps this issue.

**Comment by projectX21** [comment] 2021-11-26 15:35
is there any new possibility? Still struggeling with it. As a workaround I've switched from exported methods to classes with static methods.

**Comment by sgravrock** [comment] 2021-12-04 17:24
@projectX21 That's not solve-able by Jasmine. If the code emitted by the Angular compiler marks a property as read-only, then the browser won't let us write to it. You'd need to find some way to get the Angular compiler to mark exported properties writeable.

**Comment by JoannaFalkowska** [comment] 2021-12-05 10:03
Overriding Angular compiler is a tad bit of an overkill. The only reasonable solution is wrapping your pure functions in an object.

```
// before
export const myPureFunction = () => ...
```

```
//after 
const myPureFunction = () => ...

export const myUtilsWrapper {
  myPureFunction,
  ...
}
```

When imported like this, `myUtilsWrapper` itself is still not writable, but its fields are, so you can normally install spies on all of them.

This of course won't help with imported pure functions from external packages, though there's probably rarely a good reason to stub them in your tests.

**Comment by dofamine** [comment] 2022-01-11 12:56
Any updates?

**Comment by bsafwen** [comment] 2022-01-18 14:39
This framework has served its purpose and thanks to the developers, time to move on to jest or vitest.

**Comment by GeorgianStan** [comment] 2022-07-26 04:40
Hi @rcollette. This indeed solves the error, but does it really mocks the function, as for me using this approach still calls the original method `aFunction` from `theModule` ?

**Comment by docaohuynh** [comment] 2023-02-06 15:22
I did it by this

```
export const fooFunction = (url: string) => {
  // do somthing
}
// wrap individual functions to class
export abstract class FooWrapper {
  static readonly fooFunction = fooFunction
}
```
usage
```
import { FooWrapper } from '../utils';

// change call direct function by
FooWrapper.fooFunction('hello')
```

testing

```
const spyFoo = spyOn(FooWrapper, 'fooFunction')
expect(spyFoo).toHaveBeenCalled()
```

**Comment by triskweline** [comment] 2023-02-08 12:34
I recently wrote an article to sum up the various workarounds we discovered for this problem: [Jasmine: Mocking ESM imports](https://makandracards.com/makandra/528351-jasmine-mocking-esm-imports)

**Comment by JimmyRowland** [comment] 2023-07-20 21:47
I am having the same issue with custom angular inject functions

**Comment by sgravrock** [comment] 2023-09-12 00:23
I've published [a guide to enabling module mocking in a variety of environments](https://jasmine.github.io/tutorials/module_mocking), in many cases through the use of third-party tools. And I think that's all it makes sense for Jasmine to do. I had hoped that the JS world would develop in a direction that would make it practical for Jasmine to directly enable module mocking, but it hasn't.

Trying to build module mocking directly into Jasmine would:

* Require Jasmine to take control of the Node command line
* Require Jasmine to take control of loading and in some cases building user code, breaking most existing uses
* Call for a lowest-common-denominator API that most users would be unhappy with
* Impose performance and correctness trade-offs on everyone, whether they use module mocking or not
* Increase the maintenance workload, potentially past the limit of sustainability

On that last point: This is actually N features in a trench coat. There is no standard or portable way to enable module mocking. It has to be done separately for ComonJS in Node, ESM in Node, ESM in browsers, for each bundler, and for some specific bundler/transpiler combinations like the Angular dev tools. That actually understates the problem because most of those environments don't provide stable, documented APIs that can be used to enable module mocking. So for instance it can't just be solved once for ESM in Node. It has to be solved for each version of the experimental ESM loader API, and it's only going to stay solved until the next time that API changes. CommonJS in Node and ESM in browsers are the only environments where we can write code to enable module mocking today and be confident that it will still work a year from now. The care and feeding of this one feature could easily take more time than I currently spend on all of Jasmine.

I'm convinced that it's best to leave the job of enabling module mocking to third-party tools. That keeps Jasmine sustainable. It lets users choose tools that make the right trade-offs for them. It allows for solutions that are tailored to each environment rather than a lowest-common-denominator approach. And it comes at no cost to users who don't use module mocking. Jasmine's role is to document the availability of those tools, not to solve the problem itself.

**Closed by sgravrock** 2023-09-12 00:23 UTC
Labels: feature request

**Comment by ajlif** [comment] 2024-02-01 14:56
this issue is open from 2017 . It is time to migrate to another testing framework
