### ISSUE TITLE
Variation on allow reSpy for inheritance

### ISSUE THREAD

**Issue by edsharp** [jasmine/jasmine#1264] opened 2017-01-24 12:58 UTC
Our app uses [SmartClient](http://www.smartclient.com) which provides a class inheritance system which uses the underlying Javascript inheritance system. The following example is SmartClient-based, but the problem applies more generally, too.

Let's say you have a class `isc.ListGrid` and a sub-class `isc.ListGridPlus`.

If you `spyOn(isc.ListGrid, 'create')` it works. If you then try to `spyOn(isc.ListGridPlus, 'create')` it fails saying create has already been spied upon. This is because `ListGridPlus` does not provide its own implementation of create and hence spyOn sees the superclass' spy.

If you want to be able to differentiate between calls made to `isc.ListGrid.create` and `isc.ListGridPlus.create` you'd need to do something like:

`isc.ListGridPlus.create = jasmine.createSpy('ListGridPlus.create');`

However, I wanted to be able to use the idiomatic spyOn, so I made the following patch:

https://github.com/Osirium/jasmine/commit/ca35330e1058739d02c73caa918a5890efa47565

With the patch if spyOn detects the method it's trying to spyOn is already a spy, instead of outright throwing, it tests to see whether the `obj.hasOwnProperty(methodName)`. If it doesn't, then it creates a dummy function, such that the rest of spyOn can behave as expected.

The one caveat is that you couldn't call `.callThrough` because the dummy function would not do what you expected. This potentially could be worked around but I thought to keep it simple.

If this patch had associated tests and I raised a PR, would it be something you would consider merging? Or is there a better way of doing this?

**Comment by slackersoft** [comment] 2017-01-25 00:54
It sounds like this might be a duplicate of #931, which was fixed in #953. Please take a look at those to find the setting to allow re-spying on existing spies. I don't think that we want special case logic for handling subclassing and spying, but let us know if more general respy-ability solves your problem.

Closing this for now. Thanks for using Jasmine!

**Closed by slackersoft** 2017-01-25 00:54 UTC
