### ISSUE TITLE
Provide clear documentation with function signatures

### ISSUE THREAD

**Issue by fetis** [jasmine/jasmine#1239] opened 2016-12-02 16:50 UTC
Hello.

Current documentation it's fun and good example. But when I find some non-typical framework's call I stumble every time to understand what extra parameter means. Can you make standard documentation with function signatures and parameters description.

E.g., At the moment I'm trying realize what 3rd parameter does in this call
```
it('text', callbackFunc, 1000)
```

**Comment by slackersoft** [comment] 2016-12-02 17:35
This sounds like a duplicate of #596. Closing. Thanks for using Jasmine!

**Closed by slackersoft** 2016-12-02 17:35 UTC
Labels: docs
