### ISSUE TITLE
Cannot perform a 'it' inside another 'it'

### ISSUE THREAD

**Issue by Aelsa** [jasmine/jasmine#830] opened 2015-04-23 07:27 UTC
Hi everyone,

I recently upgrade to Jasmine 2.0 and my code does not work anymore. Let me explain my problem:
I fill a variable in a beforeAll method, and I use this variable to perform a forEach which contains some 'it'. My code is similar as this:

```javascript
describe ('Main describe', function() {
    var table;
    beforeAll( function(done) {
        table = anotherScript.method();
        done();
    });
    
    it("first it", function(done) {
        //I perform some actions...
        done();
    });
    
    table.forEach (function(item) {
        it("it in the loop", function(done) {
            //I perform some actions...
            done();
        });
    });
}); 
```
But my problem is the code read the loop before the beforeAll is executed and at this moment my 'table' variable is empty, so the code never enters in the loop...

Before I upgraded to Jasmine 2.0, I just put my loop in another 'it' like this:
```javascript
it("it that contains my loop", function() {
    describe("describe that contains my loop", function() {   
        table.forEach (function(item) {
            it("it in the loop", function() {
                //I perform some actions...
            });
        });
    });
});
```
I had no issue with 'it' inside other 'it' as long as I declare a 'describe', and the code entered in the loop after the beforeAll was performed. Jasmine 2.0 no longer accepts 'it' in another 'it': the code never enters in my second 'it'...

I tried to fill the 'table' variable in a method that returns a promise and perform the main describe only after the promise is fulfilled: but in this case, no specs are found and the script finished.

Have you a solution for this case ?

**Comment by mallowigi** [comment] 2015-04-23 15:16
I think it's metaprogramming. Technically, your tests should not depend on metadata, such as your table, think that they could be written by a guy that doesn't know your code. Therefore, what you can do in such a case is to iterate over your table and create expectations, not tests.

**Comment by nertzy** [comment] 2015-04-23 17:26
The problem is that you're mixing up code that runs at load time with code that runs at test time.

Here's what the outermost function (the one passed to 'describe') actually does:

1. Define a variable named `table`
2. Tell jasmine that, in the future, when Jasmine decides to run the tests defined in this `describe`, it should first run the passed-in function.
3. Tell jasmine about a test that it should run sometime in the future.
4. Call `table.forEach` (note that at this point the variable `table` is undefined, since the previous two steps didn't actually _run_ the functions, they only just set them aside to be run later.

@mallowigi's advice makes sense. If you want your tests to be based on what `anotherScript.method()` returns, you should do that work inside of the `it` block and just have multiple assertions instead.

*Bonus piece of advice*: If `anotherScript.method()` were to ever return an empty array, then you won't even have a single assertion. The test would succeed, even if that's not what you wanted. It's almost always a better idea to separately write each assertion in a verbose way when writing tests. That way your tests don't operate differently based on how the system under test operates.

**Comment by Aelsa** [comment] 2015-04-24 07:01
Thanks for your comments, I will follow your advises and iterate over my table !

**Comment by slackersoft** [comment] 2015-05-12 19:06
Having an `it` inside another `it` was never intended functionality, and 1.3 probably shouldn't have let that happen. Since you have a way forward, and this doesn't seem like it is an issue with jasmine itself, I'm going to close this issue.

Thanks for using jasmine!

**Closed by slackersoft** 2015-05-12 19:06 UTC

**Comment by poojagadekar89** [comment] 2017-09-13 14:15
I want to generate multiple protractor tests using promise value with loops, Is it possbile ?
var rowNumber = function call;
 rowNumber.then(function(resultTC){
         for (var i = 1; i < parseInt(resultTC); i++) {
                    it('should work for ' + i, function (done) {
                        console.log("welcome");
                    });
           };
        });
