### ISSUE TITLE
FR: if there is a map file next to the javascript file, use that for the line numbers

### ISSUE THREAD

**Issue by gregveres** [jasmine/jasmine#1210] opened 2016-09-14 22:13 UTC
Hi

I use jasmine with typescript source. The problem I am running into is that when an expect fails, jasmine prints out the line number of the line in the javascript file and then I am left trying to do the mapping back to the original typescript source manually. It would be very useful if jasmine would notice the existence of a .map file and use that to figure out the line of the original typescript file. 

From other comments I have seen, it doesn't seem that the jasmine authoring team uses typescript at all, but jasmine is proving very useful for unit testing typescript. 

Thanks
Greg

**Comment by slackersoft** [comment] 2016-09-14 22:26
This looks like a duplicate of #491. Closing in favor of the discussion over there.

Thanks for using Jasmine!

**Closed by slackersoft** 2016-09-14 22:26 UTC

**Comment by gregveres** [comment] 2016-09-14 22:35
Yup I agree it is the same. Sorry I didn't see the existing thread when I searched.
