### ISSUE TITLE
Memory leaks because of closures

### ISSUE THREAD

**Issue by saskodh** [jasmine/jasmine#941] opened 2015-10-11 13:03 UTC
Hi, this is the first issue that I am creating after almost 2 years of usage of your extraordinary testing framework for JavaScript. I am using it mainly for testing AngularJs code and I love it, it enables me to test every peace of my code and with the BDD syntax every test simply becomes part of my code documentation.

Recently after some extensive debugging, reading and analysing your source code I finally found out why I was experiencing memory leak problems. The problem was that the running tests were not able to finish because of the build up memory consumption in the browser caused by improper garbage collection.
This problem was reported by lot of people and I documented it recently in [this](http://stackoverflow.com/questions/32998442/angularjs-unit-testing-memory-leaks) StackOverflow question.

What I found out is that the reason for it was the improper cleanup after each test which is never mentioned anywhere even in the AngularJs [testing guide](https://docs.angularjs.org/guide/unit-testing).
Example:

``` javascript
describe('Test suite', function() {
  var a, b;

  beforeEach(function() {
	// init heavy objects
    a = new Array(10000).join('x');
	b = new Array(10000).join('y');
  });
  
  // NOTE: often forgotten cleanup
  afterEach(function () {
	a = null;
	b = null;
  });

  it('spec1', function() {
    // spec code..
  });
  
  // other specs and inner suites ..
});
```
If the needed cleanup is forgotten because jasmine builds up a tree from all registered suits and each suites containes references to his beforeEach, afterEach.. functions which contain references to the describe function closure which holds references to the 'a' and 'b' variables, the large objects that are referenced by that variables won't be GC-ed until Jasmine stops the execution. 

We can't say that this is an issue with Jasmine, the problem is because this information is not well transferred to all the developers using this great framework. The question is how we can improve this? Is there a better way that enables easy access to the defined variables in every inner spec, suite, function.. as this one but without caring for the cleanup which is almost always forgotten?

My idea for a workaround was to define only one 'container' object (ex. 'suite') which is nulled in an afterEach block and attach all variables there. This in the same time reduces the code length and keeps us safe from forgetting some defined variable.
Example:

``` javascript
describe('Test suite', function() {
  var suite = {};

  beforeEach(function() {
	// init heavy objects
    suite.a = new Array(10000).join('x');
	suite.b = new Array(10000).join('y');
  });
  
  // NOTE: often forgotten cleanup
  afterEach(function () {
	suite = null;
  });

  // other specs and inner suites ..
});
```

**Comment by ragaskar** [comment] 2015-10-12 16:26
Thanks for this detailed email Sashe, I'm sure it will help people who are
having memory leak issues.

R.

On Sun, Oct 11, 2015 at 6:03 AM, Sashe Klechkovski <notifications@github.com

**Comment by slackersoft** [comment] 2015-10-12 17:18
You might also look at putting your variables onto the `this` keyword (http://jasmine.github.io/edge/introduction.html#section-The_<code>this</code>_keyword) which will get disposed of when done.

**Comment by slackersoft** [comment] 2015-12-07 17:42
Closing this since it doesn't necessarily sound like an issue with jasmine itself, and jasmine provides a potential workaround with the `this` keyword.

Thanks for using jasmine!

**Closed by slackersoft** 2015-12-07 17:42 UTC

**Comment by codeword** [comment] 2016-06-23 15:39
Whoa, hold on, @slackersoft, are you saying the pattern of 
```javascript
describe("A suite is just a function", function() {
  var a;

  it("and so is a spec", function() {
    a = true;

    expect(a).toBe(true);
  });
});
```
causes memory leaks in the testing framework and that we are ok with that?  I am really surprised by that as this pattern is all over the introduction to Jasmine docs and has always been *the* pattern for writing tests.  If this pattern is in fact leaky then it is my opinion that Jasmine needs to be very clear in their documentation of the dangers of declaring variables in their describe blocks and update all their documentation to use some non leaky method of sharing variables between blocks.  In my opinion it should not be expected that developers create `afterEach` blocks for all their describes to ensure they deallocate all memory they may have used.

Honestly I think the right thing for Jasmine to do is to find the cause of the leak and fix it so that developers can use `described` scoped variables and know they go away when the `describe` block ends.

**Comment by thedocbwarren** [comment] 2016-06-23 15:55
I've experienced this in my testing many times.  In fact in my larger test suites it builds up a large amount of memory that appears to eventually slow down the browser.  

I've performed before and after methods to attempt deallocation as well with some benefit but not a fix.

**Comment by Gerg** [comment] 2016-06-24 04:42
These lines of code in Jasmine are meant to encourage your JS engine to garbage collect your closures:
https://github.com/jasmine/jasmine/blob/f6da0846423a08959b5602a630d419e3059283aa/src/core/Env.js#L158-L166

That said, Jasmine can only do so much to free memory. Memory leaks in your source code, its dependencies, or your spec runner (see https://github.com/jasmine/jasmine/issues/1108) will compound over your suite's execution. Also, if you have circular references in your code, then it may never be freed (see [here](http://stackoverflow.com/questions/33011097/chrome-v8-does-not-garbage-collect-a-circular-reference)).

Jasmine is definitely not perfect, so if you are able to find leaks in Jasmine or strategies to mitigate leaks, we would love to hear about them.

**Comment by firezdog** [comment] 2019-06-26 14:59
What if you limited nesting of tests to cases where absolutely necessary, implementing proper dereferencing as needed?

**Comment by saskodh** [comment] 2019-06-26 15:06
@firezdog, I found this workaround very useful, I haven't run on a memory leak issue since I started using it and updated all the tests.
https://stackoverflow.com/a/33072532/4319253

**Comment by slackersoft** [comment] 2019-06-26 23:21
Newer versions of Jasmine (3.0 and later I think) should also do what they can to remove references to functions (specs, before, after, etc) that have been fully executed, so we should be freeing up as much memory as we can.
