### ISSUE TITLE
argsFor not working for nested calls and same data object

### ISSUE THREAD

**Issue by miketb24** [jasmine/jasmine#1104] opened 2016-04-30 17:05 UTC
Hello, I've been having an issue with `argsFor` with a function called twice in a nested manner.

The function takes a params object, a data object and a callback. Inside the callback I call the original function but changing slightly the data object. Then, inside the test, `argsFor(0)` and `argsFor(1)` show the same data object (the one of the last call).

I was able to replicate the issue in plunker: http://plnkr.co/edit/5RBrnBhKkutYe1coyg7P 

I added a bunch of `console.log` so you may check that the args are not working as expected.

It's important to mention that the controller works fine, the data object is sent as expected.

**Comment by Gerg** [comment] 2016-09-27 00:46
The issue is that you are modifying the data object that the spy is holding on to. This issue is a duplicate of #444.

**Closed by Gerg** 2016-09-27 00:46 UTC
