### ISSUE TITLE
toEqual should list differences instead of pretty printing objects

### ISSUE THREAD

**Issue by mwisnicki** [jasmine/jasmine#675] opened 2014-09-18 16:29 UTC
Consider this simple example ([jsfiddle](http://jsfiddle.net/6y65oh1g/)):

``` js
var actual = { x: 1, y: { z: 2 } };
var expected = { x: 1, y: { z: 3 }};
expect(actual).toEqual(expected);
```

This outputs:
`Expected { x : 1, y : { z : 2 } } to equal { x : 1, y : { z : 3 } }.`

In other words it pretty prints both objects.

Now imagine we are in real world where objects are quite complex and toEqual quickly becomes useless.

I would expect output like:

```
Expected no differences but found 1:
1. Expected y.z = 2 to equal 3
```

i.e. list all differences with paths.

**Comment by mzgol** [comment] 2015-01-22 23:13
This is what [chai]() prints:

```
      AssertionError: expected { Object (id, issued_at, ...) } to deeply equal { Object (id, issued_at, ...) }
      + expected - actual

               "featuredCollectionsCount": 0
             }
             "avatar": {
               "origin": "gravatar"
      +        "url": "about:blankk"
      -        "url": "about:blank"
             }
             "email": "foo.bar@example.com"
             "fullname": "Foo Bar"
             "id": 42
      
```
So nice, I can immediately see what's wrong. In large objects like that Jasmine output is basically useless, it's completely unreadable. I have to copy the output to a separate file, hunt for "equal to" and split the string by that, copy both parts to two files and compare using my own eyes.

**Comment by slackersoft** [comment] 2015-02-11 21:22
We'd be happy to review a pull request for this that can work both in the `HtmlReporter` and `ConsoleReporter` (probably the one in [jasmine-npm](https://github.com/jasmine/jasmine-npm) since core's is now deprecated).

**Comment by mzgol** [comment] 2015-04-20 15:00
@slackersoft Mocha uses the [diff](https://www.npmjs.com/package/diff) package to display these readable diffs. Would you accept a PR that would use this package to display object differences in Jasmine?

**Comment by slackersoft** [comment] 2015-04-20 20:11
We'd like to keep the core of jasmine with no dependencies. Aside from just not wanting to install a bunch of dependencies on your system just so you can test your javascript, this also means we can release a standalone version that doesn't need much setup, and the platform specific versions (ruby, python, npm) don't need to figure out how to get the same dependencies in each environment.

**Comment by mzgol** [comment] 2015-04-21 11:38
@slackersoft 
> Aside from just not wanting to install a bunch of dependencies on your system just so you can test your javascript

The published `diff` package contains just 3 files: `README.md`, `package.json` & `diff.js`. This is not bloating anything. OTH, `jasmine-core` package contains a lot of files that are not necessary to run Jasmine, like `GOALS.md`, the `images/` directory etc.

> this also means we can release a standalone version that doesn't need much setup

Don't you already have a build process? You don't keep everything in one file after all.

If you don't want to include `diff` as an explicit npm dependency, another option would be do declare it as a dev dependency and treat it in the build process as every other source file that you're currently merging anyway.

Yet another option would be to copy `diff.js` inside the Jasmine repository; the drawback is that it's easy to diverge from the source then and miss its fixes etc. Also, it gives smaller credit to the original author.

What do you think? I could try something from the proposals above if you agree. I don't know what's the status of the Ruby version but I don't know Ruby so I can only offer a PR for the JS version.

**Comment by slackersoft** [comment] 2015-05-07 22:49
The concern from jasmine's perspective is around dependencies, not necessarily the size of the tarball that is downloaded for install. That said, the `images` folder is actually necessary for us to create a jasmine branded `specRunner.html` file in case a project using npm for package management wants to run browser based jasmine tests.

The dependency constraint hits us especially hard, considering the various different platforms that the jasmine javascript is released for (npm, ruby gem, python egg, standalone), which means that we can't just depend on a package to directly provide us other functionality.

This effectively leaves either the dev dependency route or inlining the `diff.js` file directly into jasmine iteself if we want to use the diff package. Inlining is obviously bad for updates, but both would actually require us to distribute the diff code and not just have it as a dependency, which isn't something I think we really want to do.

On top of all of this, the diff package wouldn't solve some of the more interesting cases like `objectContaining` or `arrayContaining`, so I think what we really want here is a more custom solution that supports the asymmetric matchers as well.

**Comment by mzgol** [comment] 2015-05-08 07:28
Would it be ok to start from the code from the diff package & iterate from
there?

-- 
Michał Gołębiowski

**Comment by antoineverger** [comment] 2015-05-27 16:08
Having that feature would be really great. Is there any progress on a PR ?

**Comment by jchoca** [comment] 2015-05-27 16:38
I think it would be a nice feature too.  What would a dependency free solution look like?

**Comment by andymaster01** [comment] 2015-07-27 18:33
If you're using karma to run your tests, you can use this one:
https://www.npmjs.com/package/karma-jasmine-diff-reporter

**Comment by mik01aj** [comment] 2015-08-03 10:30
I managed to have a highlighted diff in Jasmine (running in Node) by installing [jsondiffpatch](https://github.com/benjamine/jsondiffpatch) and by adding this in `beforeEach`:

```
        var jsondiffpatch = require('jsondiffpatch');
        jasmine.addMatchers({
            toEqualJSON: function(util, customEqualityTesters) {
                return {
                    compare: function(actual, expected) {
                        var result = {};
                        actual = JSON.parse(JSON.stringify(actual));
                        expected = JSON.parse(JSON.stringify(expected));
                        result.pass = util.equals(actual, expected, customEqualityTesters);
                        result.name = 'JSON objects ' + (result.pass ? '' :  'don\'t') + ' match';
                        if (result.pass) {
                            result.message = 'OMG Big Equal!';
                        } else {
                            result.message = '' + jsondiffpatch.formatters.console.format(jsondiffpatch.diff(expected, actual));
                        }
                        return result;
                    },
                };
            }
        });
```

The only thing I don't like about it is that, in case of an error, the diff gets displayed twice (once as message and once in stack)

**Comment by startswithaj** [comment] 2015-10-20 06:19
+1

**Comment by bcherny** [comment] 2015-12-23 21:17
:+1:

**Comment by josketres** [comment] 2015-12-31 10:29
+1 this behaviour is very useful. 
I tried to use [unexpected.js](https://github.com/unexpectedjs/unexpected) for this, but the combination: unexpected + jasmine + karma + PhantomJS is still not stable (I keep getting errors).
It would be nice if it's built-in in jasmine.

**Comment by gitnik** [comment] 2016-01-10 15:17
+1 for this.

**Comment by jsdir** [comment] 2016-02-22 17:31
:+1:

**Comment by vamsivarikuti** [comment] 2016-06-27 10:11
For reference: ExUnit handles like this
![](http://elixir-lang.org/images/contents/exunit-diff.png)

**Comment by benchristel** [comment] 2016-07-20 19:11
I've resumed work on this, at https://github.com/jasmine/jasmine/compare/master...benchristel:eq-diffs

**Comment by donald-s** [comment] 2016-10-22 20:06
@benchristel I see that you've put quite a bit of work into the diff functionality. Are you still planning to work on it?

**Comment by benchristel** [comment] 2016-10-23 04:55
@donald-s the bulk of the functionality should be there already--at this point the bottleneck is getting the PR reviewed and merged. Unfortunately it doesn't seem like the maintainers have had much time to dedicate to Jasmine recently (and of course it doesn't help that the PR is enormous!)

If you're daring and want to beta-test the diff functionality, I'm sure that would be helpful. Real usage might uncover some issues that I didn't think to write tests for.

**Closed** 2016-11-17 02:01 UTC
Labels: ready for work

**Comment by donald-s** [comment] 2016-11-21 01:41
@benchristel I see. Looks like it was just merged. I'm eager to try it out. Thanks for your work on this!

**Comment by giamir** [comment] 2016-11-29 21:55
@slackersoft It would be nice to know when the work done by @benchristel will be released.
This [story](https://www.pivotaltracker.com/n/projects/10606/stories/1283792) has a _3.0 label_ in your pivotal tracker; does it mean we will have to wait a Jasmine 3.0 release? If that's the case any chance to have a 3.0 prerelease published in npm?
Thanks!

**Comment by nemoDreamer** [comment] 2017-02-21 20:00
@slackersoft what's the target release for this? I'm looking to migrate our test suites to mocha+chai, because our deep comparisons are just too hard to debug in Jasmine at the moment... 😢

**Comment by nemoDreamer** [comment] 2017-02-21 20:05
Btw, @slackersoft @mgol : Mocha solved the "too many dependencies on initial setup" problem by making this optional.
If you set `mochaReporter: { showDiff: true }` in Karma's conf, _that's_ when you need to add the `diff` dependency to your `package.json`.
You'd really want to avoid re-inventing the wheel and copying something over into `jasmine-core` that's already been solved, no?

Note: I missed @andymaster01's comment about `karma-jasmine-diff-reporter`, so I'll give that a spin now.

**Comment by matthewadams** [comment] 2017-04-12 19:36
Is this still a no-go?  As of this note, the issue still has the `ready for work` label, but the issue is closed. What's the status?

**Comment by benchristel** [comment] 2017-04-12 20:29
@matthewadams there was a PR for this feature that was merged a while ago.

Here's the merge commit: https://github.com/jasmine/jasmine/commit/54e7a82ef31cf3a8efd63e48735021ba066d781f

I'm not sure what the timeline for release is.

**Comment by matthewadams** [comment] 2017-04-12 20:55
@slackersoft or @jasmine Can y'all give info on expected fix version that will contain https://github.com/jasmine/jasmine/commit/54e7a82ef31cf3a8efd63e48735021ba066d781f ?  That'd be just jim-dandy!  :)

**Comment by benjaminapetersen** [comment] 2017-09-15 01:57
Check in on this! The issue is closed, but I don't believe it has been released?  Feeling the pain and looking for something like what @mgol referenced in [the comment above](https://github.com/jasmine/jasmine/issues/675#issuecomment-71118844).

**Comment by benchristel** [comment] 2017-09-15 16:54
I see the code on the v2.8.0 tag, so I think it's out? What version do you have @benjaminapetersen ?

**Comment by benjaminapetersen** [comment] 2017-09-15 18:18
I'm on `jasmine-core` v `2.8.0`.  I see this kind of output:

```
Expected $[0] to have properties
    candy: 'bars'
@test/spec/services/membership/membershipSpec.js:284:7
```
.... is this correct?  If so, I'm current.  However, I was expecting more like what was shown in the above comments [this](https://github.com/jasmine/jasmine/issues/675#issuecomment-71118844) or [this](https://github.com/jasmine/jasmine/issues/675#issuecomment-228706113).

**Comment by benchristel** [comment] 2017-09-15 22:13
@benjaminapetersen yep, you're up-to-date. There were a couple different proposals for formatting the output and I went the one in [the OP](https://github.com/jasmine/jasmine/issues/675#issue-43152603).

**Comment by benjaminapetersen** [comment] 2017-09-16 00:05
ok thanks!

**Comment by ohjames** [comment] 2018-06-14 16:04
Is there a simple way to override this? The output can still be really difficult to interpret. When I have an array nested inside an object with a missing value mocha makes it immediately obvious, jasmine just tells me one object is different to another.

**Comment by ohjames** [comment] 2018-08-08 10:06
Working with a team now that replaced jasmine with mocha because they couldn't stand jasmine's diff output or find a way to update it to be more like mocha's. I think mocha's "pretty printed diff" output is so much easier to parse.

**Comment by cancerberoSgx** [comment] 2019-05-10 06:41
Is this working ? If so can somebody show me the way so I PR with a comment in the readme ?  I recently needed this for large strings comparison, I love jasmine because is agile and fast but because I have no descent diff for strings I'm switching to others.... or implementing my own diff which is not good... : 

```ts

import { ansi } from 'cli-driver'
import { createPatch } from 'diff'
import { DisplayProcessor, SpecReporter } from 'jasmine-spec-reporter'
import { CustomReporterResult } from 'jasmine-spec-reporter/built/spec-reporter'

class CustomProcessor extends DisplayProcessor {
  displayFailedSpec(spec: CustomReporterResult, log: string): string {
    const colored: string[] = []
      if (spec.failedExpectations && spec.failedExpectations.length) {
        spec.failedExpectations.forEach(s => {
          const p = createPatch(s.message, s.actual, s.expected)
          const c = p
          .split('\n')
          .map(l => (l.startsWith('-') ? ansi.format(l, ['red']) : l.startsWith('+') ? ansi.format(l, ['green']) : l))
          .join('\n')
          colored.push(c)
        })
      }
      return colored.join('\n\n\n')
    }
  displaySpecErrorMessages(spec: CustomReporterResult, log: string): string {
      return ''
    }
    displaySummaryErrorMessages(){return ''}
}

jasmine.getEnv().clearReporters()
jasmine.getEnv().addReporter(new SpecReporter({
  customProcessors: [CustomProcessor]
}))

j.execute()

```

**Comment by slackersoft** [comment] 2019-05-14 00:51
I am definitely still open to further refinements to the existing diff output. Currently it is primarily dealing with the differences of properties within an object, and not which words in a string are different.

**Comment by ohjames** [comment] 2019-05-14 02:24
Can you not make it so the user can override it? Even the object diff output is far less readable than mocha's, and for many other cases replace "far" with "far far far".

**Comment by slackersoft** [comment] 2019-05-15 01:07
As I said, I'm definitely open to further Pull Requests to refine how diffs are displayed to the user. Jasmine currently displays the same thing on the command line as it does in the browser, which can complicate things a bit.

**Comment by cancerberoSgx** [comment] 2019-05-17 05:28
hey @slackersoft I want to give it a try and support it in node version, so I will start with jasmine/jasmine-npm. Do you know if it's possible or viable that, as long as I use compatible / lightweight libraries for the diff, to reuse that solution in other JavaScript mediums like the browser or headless browser or should I just focus on node.js jasmine-npm?, thanks

**Comment by slackersoft** [comment] 2019-05-29 00:44
I would like to keep jasmine-core with no runtime dependencies if at all possible. Jasmine _is already_ tracking the differences, so you might be able to focus on the printing of those differences instead of detection.

Hope this helps.

**Comment by bowka** [comment] 2020-02-11 13:22
it has been 6 years since the issue was reported.And it is still not solved. It is even closed.
It doesn't make sense to me anymore to continue with Jasmine.

**Comment by slackersoft** [comment] 2020-02-12 17:25
As has been mentioned multiple times already in this thread, Jasmine prints out a detailed diff when two objects don't match using `toEqual`. Please make sure you're using a recent version of Jasmine that supports this feature. Again, I would be happy to review a pull request to improve the formatting of the diff. If the improved diff output is important enough to you that you would consider switching test runners, you might also investigate what it would take to help Jasmine get better as well.

**Comment by rodoabad** [comment] 2020-11-24 16:43
Even with `jest-circus` IIRC.

**Comment by aschriner** [comment] 2023-09-21 23:37
> Please make sure you're using a recent version of Jasmine that supports this feature

maybe i'm being dense... but i've upgraded to jasmine `5.1.0` and i'm still not seeing anything that looks like a detailed pretty print of an object diff as mentioned above.  what i see is:

```javascript
expect(publishedEvent).toEqual(jasmine.objectContaining(expectedEventData));
```
produces 
```javascript
Error: Expected TacoEnrolled({ _type: 'TacoEnrolled', createTime: 1695339103621, sendTime: null, eventId: 'YWI2YjExNWEtMGQ3MC00Mz', Taco: Object({ id: 1, isPublicTaco: false, isSpecialTaco: false }), enrollmentSource: null, isAutoEnrolled: false, userIsTacoEditor: false, uiRegion: null }) to equal <jasmine.objectContaining(Object({ taco: Object({ id: 1, isPublicTaco: false, isUdemyPath: false }), enrollmentSource: null, isAutoEnrolled: false, userIsTacoEditor: false, uiRegion: 'enroll_button' }))>
```

**Comment by sgravrock** [comment] 2023-09-22 00:53
@aschriner There isn't enough information in your comment to reproduce the problem. (This is usually the case when people ask for help by commenting on old issues, and it's one of the reasons why so many OSS projects auto-lock issues after they're closed.) When I make my best guess as to the values of `publishedEvent` and `expectedEventData`, I get this output:

```
Expected $.taco = undefined to equal Object({ id: 1, isPublicTaco: false, isUdemyPath: false }).
Expected $.uiRegion = null to equal 'enroll_button'.
```

I wonder if you're running a much older version of jasmine-core than you think you are. The output you posted looks like what 2.x or early 3.x would produce.

If you need help or think you've found a bug, please open a new issue and follow the instructions on the form.

**Comment by aschriner** [comment] 2023-09-22 22:47
> I wonder if you're running a much older version of jasmine-core than you think you are. The output you posted looks like what 2.x or early 3.x would produce.

hi @sgravrock thanks a bunch for the tip!! your hunch was correct and for some reason i've got one version of jasmine in `node_modules` and another one being used by the test runner.  not sure why that is but it's very helpful to know that the behavior i'm seeing is indeed due to an OLD version of jasmine.  

cheers and thanks again :)
