### ISSUE TITLE
BeforeAll does not run for nested describe blocks.

### ISSUE THREAD

**Issue by ticviking** [jasmine/jasmine#785] opened 2015-02-20 02:45 UTC
I have several tests with shared setup

``` js
describe( "First", function(){
  var foo;
  beforeAll(function (done){
    foo = "Shared Setup";
    done();
  });
  describe( "Second", function(){
    it("Has been setup", function(done) {
      expect(foo).toBe("SharedSetup");
    });
  });
 // More tests here
});
```

my beforeAll callback seems to never get called.

**Comment by Gerg** [comment] 2015-02-20 03:07
What version of Jasmine are you running? The following worked for me:

```js
describe( "First", function(){
  var foo;
  beforeAll(function (done){
    foo = "Shared Setup";
    done();
  });
  describe( "Second", function(){
    it("Has been setup", function() {
      expect(foo).toBe("Shared Setup");
    });
  });
});
```

**Comment by ticviking** [comment] 2015-02-20 21:03
2.1.3, I though I was more up-to-date.

Should this be fixed on 2.2.* or do I need to update to edge?

**Comment by Gerg** [comment] 2015-02-25 01:00
I tried my test on 2.1.3, and I was still unable to reproduce your problem. If you run my test from above, does it fail?

**Comment by slackersoft** [comment] 2015-03-26 22:03
It looks like the example `it` that you showed doesn't actually call the `done` callback that it receives so it won't be able to complete successfully. We've tried the example @Gerg provided on a few different versions and it seems to be working fine. 

I'm going to close this, but if you have a chance to try the other example or if you have more details on what exactly is going wrong with your suite, please post again.

Thanks for using jasmine!

**Closed by slackersoft** 2015-03-26 22:03 UTC
Labels: waiting
