### ISSUE TITLE
Spies save call arguments by reference 

### ISSUE THREAD

**Issue by eschwartz** [jasmine/jasmine#444] opened 2013-10-09 15:19 UTC
When a spy is called with arguments, the spy's `mostRecentCall.args` and `argsForCall` properties are set as a direct reference to the arguments. This means that if the argument objects themselves are changed, our reference to them will change as well.

Consider this example (http://jsfiddle.net/a5kp9/2/):
```javascript
var spy = jasmine.createSpy();
var arg = ['a', 'b'];

spy(arg);

arg.length = 0;

expect(spy.mosRecentCall.args[0][0]).toEqual('a');
expect(spy.mosRecentCall.args[0][1]).toEqual('b');
// Fails. Actual value of spy.mostRecentCall.args[0] is now '[]'
```

I would expect that the answer to "What arguments was this spy called with?" shouldn't change _after_ the spy is called.

I'm thinking it would make more sense to save a copy of the arguments, rather than a reference. Thoughts?

**Comment by toby-sullivan-hs** [comment] 2015-02-25 00:25
This is old but having just fought with this same issue, I would certainly argue the current behaviour is incorrect (or, at least, not the expected behaviour). I want to compare what value a function was called with.

**Comment by ahonaker** [comment] 2015-03-28 01:47
Agree with previous posters.  I need to test that the function is being called correctly, not the results of downstream changes to referenced object(s).

**Comment by slackersoft** [comment] 2015-04-01 01:41
As @ragaskar mentioned, this is a tradeoff between:

````javascript
it('allows the same object', function() {
  var spy = jasmine.createSpy('spy');
  var foo = { foo: 'bar' };
  spy(foo);
  foo.baz = 'quux';
  expect(spy).toHaveBeenCalledWith(foo);
});
````

and

````javascript
it('does not allow the same object', function() {
  var spy = jasmine.createSpy('spy');
  var foo = { foo: 'bar' };
  spy(foo);
  foo.baz = 'quux';
  expect(spy).toHaveBeenCalledWith({ foo: 'bar' });
});
````

Currently the tradeoff has come down on the side of allowing the use of the same object even if it has changed since the spy was called, most likely because this is easier for jasmine to implement.

Since we've heard some concern about this from the community, I'd be happy to review a pull request that changed this behavior so the params were duplicated and so matched an object that was the same as the param at the time of the call.

**Comment by slackersoft** [comment] 2016-09-27 19:28
I believe this should be fixed now that #1000 is merged and released. This is a per-spy setting

```javascript
jasmine.createSpy().calls.saveArgumentsByValue()
```

Closing.

**Closed by slackersoft** 2016-09-27 19:28 UTC
Labels: ready for work

**Comment by aaani** [comment] 2016-10-28 23:11
@slackersoft Any timeline on when this will be released? Also any updates about the docs for this?

**Comment by aaani** [comment] 2016-10-28 23:14
Sorry my bad, It's present in 2.5.2 already.

**Comment by mahhov** [comment] 2018-03-18 05:56
@slackersoft, this is shallow copy. is there a similar option for storing deep copy of value?

```
it('', function () {
        let spy = jasmine.createSpy('spy');
        spy.calls.saveArgumentsByValue();

        let a = {b: {c: 1}};
        spy(a);
        a.b.c = 3;

        expect(spy).toHaveBeenCalledWith({b: {c: 1}});
    });
```

**Comment by slackersoft** [comment] 2018-03-22 00:39
Deep copy can get expensive pretty quickly (and might have to deal with cycles in the object), so we don't have a plan to add that ability for spies at this time.
