### ISSUE TITLE
Not working expectationFAilOutput.

### ISSUE THREAD

**Issue by Niyarlatotep** [jasmine/jasmine#1361] opened 2017-05-25 07:09 UTC
- What version are you using?
'2.6.0'
 - What environment are you running Jasmine in (node, browser, etc)?
'nodejs'
 - How are you running Jasmine (standalone, npm, karma, etc)?
'included in protractor'
 - If possible, include an example spec that demonstrates your issue.
users.createUser(someUser);
expect(users.isUser(someUser)).toEqual(true, 'There isnt user:' + someUser.name)

if it fails, there isn't fail output there: "There isnt user: someUser"
it's just output:
Expected false to equal true.

**Comment by slackersoft** [comment] 2017-05-25 21:13
This is a duplicate of #641, also check out [my comment there](https://github.com/jasmine/jasmine/issues/641#issuecomment-54736801). This isn't a feature that Jasmine officially supports.

Closing. Thanks for using Jasmine!

**Closed by slackersoft** 2017-05-25 21:13 UTC

**Comment by fatsu** [comment] 2017-09-27 08:29
This n+1 message argument does work for other matchers but not for toEqual().

@slackersoft 
Could this be because the toEqual matcher explicitly sets the message on the result objects, while others don't?

`result.message = diffBuilder.getMessage();`
