### ISSUE TITLE
Should {} ==  Object.create(null)? 

### ISSUE THREAD

**Issue by dhoko** [jasmine/jasmine#1096] opened 2016-04-19 11:40 UTC
I am testing a map built with `Object.create(null)`, before it was with `{}`.

Ex: 
```js
expect({}).toEqual(Object.create(null))
```

Error message:
```js
Expected Object({  }) to equal null({  })
```

This weird message comes from [PrettyPrinter L119](https://github.com/jasmine/jasmine/blob/master/src/core/PrettyPrinter.js#L119)

The expect:false comes from: [matchersUtil L181](https://github.com/jasmine/jasmine/blob/master/src/core/matchers/matchersUtil.js#L181) because `Object.create(null).constructor` is undefined.

Should we use // Deep compare objects. for this one ?

**Comment by dhoko** [comment] 2016-04-19 12:21
With this it works:

```js
if (className !== '[object Array]') {
  var aCtor = a.constructor, bCtor = b.constructor;
  if (
      aCtor !== bCtor
      && !(
        isFunction(aCtor)
        && aCtor instanceof aCtor
        && isFunction(bCtor)
        && bCtor instanceof bCtor )
    ) {

    if (bCtor) {
      return false;
    }
  }
}
```

Tests:

```js
var noProto = Object.create(null);
noProto.name = 1;
function Toto() {
   this.name = 1
}
var otherProto = new Toto()

expect({}).toEqual({}) // true
expect({}).toEqual(Object.create(null)) // true
expect({name: 1}).toEqual(noProto) // true
expect({name: 1}).toEqual(otherProto) // false
```

**Comment by slackersoft** [comment] 2016-08-19 21:04
The pretty printer is attempting to show you that these objects differ based on the constructor used to create them. That's what the bit before the parentheses is.

Closing this as a duplicate of #598 and desired functionality for now. Thanks for using Jasmine!

**Closed by slackersoft** 2016-08-19 21:04 UTC
