### ISSUE TITLE
xdescribe results appear in report as pending

### ISSUE THREAD

**Issue by hnry** [jasmine/jasmine#1178] opened 2016-08-10 19:51 UTC
http://jasmine.github.io/2.4/introduction.html#section-Disabling_Suites

As per the docs it states the results will not appear in the results (I'm guessing this means the report). And in Pending section right below it, it clearly makes the distinction that it will still show the results.

And from what I understand xdescribe should not mark things as pending() as it's different from being disabled.

**Reproduce:**
Using jasmine 2.4.1 (from npm), I copy the code in that section into a file and run jasmine on the file (with a barebones support json file).

**Output:**

```
Started
*

Pending:

1) A spec is just a function, so it can contain any code
  No reason given

1 spec, 0 failures, 1 pending spec
```

**Comment by Gerg** [comment] 2016-09-17 00:10
Using `xit` is just a shortcut for calling `pending` in your spec. This is the expected behavior.

If you can think of a way to more clearly describe this behavior in the docs, please submit a PR here: https://github.com/jasmine/jasmine.github.io

**Comment by hnry** [comment] 2016-09-17 00:15
Hi Greg think there is a mistake, I am referring to xdescribe not xit, doc says "Suites can be disabled with the xdescribe function. These suites and any specs inside them are skipped when run and thus their results will not appear in the results."

The example is exact copy of the doc example. Yet xdescribe suite is still printed in report.

**Comment by Gerg** [comment] 2016-09-17 00:43
You are correct. `xdescribe` is a way to recursively pend all the specs below it in the spec tree. 

I believe what the docs are trying to say is something like: "These suites and any specs inside them are skipped when run and thus will not be marked as passed or failed." 

We still expect the specs and suites to be displayed, just marked as pending.

**Comment by hnry** [comment] 2016-09-17 01:45
OK, I guess I misunderstood the doc.

The text "These suites and any specs inside them are skipped when run and thus their results will not appear in the results." seemed as if it would not be part of the report.

Immediately below that line is "Pending specs do not run, but their names will show up in the results as pending." almost like it's making a contrast between the two.  Both do not run, but one is "not part of the report", and the "other will show up in the result".

--------
Also when I try this in jasmine 2.3.2 I get:
```
Started



Ran 0 of 1 spec
0 specs, 0 failures
Finished in 0.005 seconds
```

So 2.4.x and 2.5.x both display as pending but 2.3.2 does not show at all.

**Comment by Gerg** [comment] 2016-09-17 01:57
This might just be because the npm module didn't support displaying pending specs until 2.4. I'll check with other versions of jasmine to see what the behavior was.

**Comment by Gerg** [comment] 2016-09-27 00:22
I'm seeing the same behavior in browser versions of Jasmine. Prior to 2.4, it printed specs inside `xdescribe` blocks in grey.

![screen shot 2016-09-26 at 5 16 17 pm](https://cloud.githubusercontent.com/assets/875892/18856158/52463928-840d-11e6-8298-6522e76436fa.png)

After 2.4 is is marked pending:

![screen shot 2016-09-26 at 5 16 07 pm](https://cloud.githubusercontent.com/assets/875892/18856165/6092e936-840d-11e6-8956-75fae99830ba.png)

Looking at the release notes, this changed as part of this PR: https://github.com/jasmine/jasmine/issues/855

You are correct that the documentation was probably not updated as part of this. I'll leave this open as a documentation issue.

**Closed** 2016-12-16 21:47 UTC
Labels: docs, ready for work
