### ISSUE TITLE
Spy on module property

### ISSUE THREAD

**Issue by mtrezza** [jasmine/jasmine#1895] opened 2021-04-04 16:27 UTC
## Expected Behavior
Spy on module property should be possible.

## Current Behavior
Given a module that exports a property:
```
const aProperty = 'a';
module.exports = {
  aProperty
};
```
Trying to spy on it with:
```
const MyModule = require('MyModule');
spyOnProperty(MyModule, 'aProperty', 'get').and.returnValue('b');
```

throws error:

```
Error: <spyOnProperty> : Property aProperty does not have access type get
Usage: spyOnProperty(<object>, <propName>, [accessType])
```

## Your Environment
* Version used: 3.7.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): node 12.21.0

**Comment by sgravrock** [comment] 2021-04-04 16:53
This is a duplicate of #1414. You might also find useful information in #1817, even if you're not using TypeScript.

Something (probably a transpiler that you're using, but possibly Node) is marking exported module properties as read-only. As a result, Jasmine can't modify it. As a general rule, Jasmine can't spy on anything that you can't assign to with the `=` operator.

I recommend modifying your code to use dependency injection for things you'd like to mock. I've seen that approach consistently yield better results across a number of different teams. If you don't want to do that, there are tools like [testdouble](https://github.com/testdouble/testdouble.js/blob/master/docs/7-replacing-dependencies.md) and [rewire](https://www.npmjs.com/package/rewire) that monkey-patch the Node module loader to make things writeable. This is a rapidly changing landscape, so it's possible that future changes to your build system, the way you use modules, or the Node module loader could break whatever module mocking tool you use.

Closing as a duplicate.

**Closed by sgravrock** 2021-04-04 16:53 UTC

**Comment by sgravrock** [comment] 2021-07-05 17:05
This is now covered in the FAQ: https://jasmine.github.io/pages/faq.html#module-spy
