### ISSUE TITLE
Give test file in the result to enable to use the new sonar generic test import

### ISSUE THREAD

**Issue by jehon** [jasmine/jasmine#1256] opened 2017-01-16 15:26 UTC
When reporting to sonar, we now need to specify in wich file the test has run - see this:
https://docs.sonarqube.org/display/PLUG/Generic+Test+Coverage

A plugin exists to report data from karma to jenkins, but it requires the "describe" to contains the exact path name, which is not really beautifull:
https://github.com/tornaia/karma-sonarqube-unit-reporter

Would it be possible to add the file path (relative to baseRoot of course) in the result:
this.specSuccess = this.specSkipped = this.specFailure = function (browser, result) {
   result.file = ...
}

Thanks in advance

**Comment by jehon** [comment] 2017-01-16 15:37
This has already been done in Mocha, if I read that correctly:
https://github.com/mochajs/mocha/pull/1222

**Comment by slackersoft** [comment] 2017-03-10 20:35
In order to get a feature like this to work in browsers as well as node.js, Jasmine would need to throw an `Error` and parse out the stacktrace when processing your suite in order to get the name of the file that called `describe` or `it`. Throwing exceptions for everything in your full suite could potentially be expensive and make loading your suite take significantly longer than it does now.

Looking at that PR in mocha, it looks like it only really gets the filename when `require`ing a file (as in node.js) and won't get it at all when running in a browser.

Because of the `Error` stuff it might be necessary to make the file name information optional or configurable, but it would depend on how much (if any) time it added to parsing and running the suite. I would be happy to review a pull request that added the file info to the `result` object that gets sent to the reporters. The functionality should either be configurable, or have a discussion about how much time this adds to a large suite.

**Comment by sgravrock** [comment] 2022-07-01 00:14
Many of the difficulties mentioned here no longer apply. See #1884. Closing as a duplicate of that issue.

**Closed** 2022-07-01 00:34 UTC
Labels: help needed
