### ISSUE TITLE
Seeing tests run multiple times, intermittently.

### ISSUE THREAD

**Issue by Steveiwonder** [jasmine/jasmine#1003] opened 2015-12-23 10:02 UTC
Sometimes when running my tests everything in the describe section gets executed or atleast displayed multiple times on the page. I've just used the info from https://angular.io/docs/ts/latest/testing/first-app-tests.html to set it all up.

This is the TypeScript
```TypeScript
import {Hero} from '../app/hero';
describe('Hero', () => {
	it('has name given in the constructor', () => {
		let hero = new Hero(1, 'Super Cat');
		expect(hero.name).toEqual('Super Cat');
	});
	it('has id given in the constructor', () => {
		let hero = new Hero(1, 'Super Cat');
		expect(hero.id).toEqual(1);
	});
	it('has name given in the constructor', () => {
		let hero = new Hero(1, 'Super Cat', 'Claw Scratch');
		expect(hero.power).toEqual('Claw Scratch');
	});
	it('has alter ego given in the constructor', () => {
		let hero = new Hero(1, 'Super Cat', 'Claw Scratch', 'Feline');
		expect(hero.alterEgo).toEqual('Feline');
	});
})
```
Which spits out this JavaScript

```JavaScript
System.register(['../app/hero'], function(exports_1) {
    var hero_1;
    return {
        setters:[
            function (hero_1_1) {
                hero_1 = hero_1_1;
            }],
        execute: function() {
            describe('Hero', function () {
                it('has name given in the constructor', function () {
                    var hero = new hero_1.Hero(1, 'Super Cat');
                    expect(hero.name).toEqual('Super Cat');
                });
                it('has id given in the constructor', function () {
                    var hero = new hero_1.Hero(1, 'Super Cat');
                    expect(hero.id).toEqual(1);
                });
                it('has name given in the constructor', function () {
                    var hero = new hero_1.Hero(1, 'Super Cat', 'Claw Scratch');
                    expect(hero.power).toEqual('Claw Scratch');
                });
                it('has alter ego given in the constructor', function () {
                    var hero = new hero_1.Hero(1, 'Super Cat', 'Claw Scratch', 'Feline');
                    expect(hero.alterEgo).toEqual('Feline');
                });
            });
        }
    }
});
//# sourceMappingURL=hero.spec.js.map
```
This is my unit-test.html
```html

<html>

<head>
    <title>1st Jasmine Tests</title>
    <link rel="stylesheet" href="../node_modules/jasmine-core/lib/jasmine-core/jasmine.css">
    <script src="../node_modules/jasmine-core/lib/jasmine-core/jasmine.js"></script>
    <script src="../node_modules/jasmine-core/lib/jasmine-core/jasmine-html.js"></script>
    <script src="../node_modules/jasmine-core/lib/jasmine-core/boot.js"></script>
</head>

<body>
    <script src="../node_modules/systemjs/dist/system.src.js"></script>
    <script>
    // #2. Configure systemjs to use the .js extension
    //     for imports from the app folder
    System.config({
        packages: {
            'out': {
                'app': {
                    defaultExtension: 'js'
                }
            }
        }
    });
    // #3. Import the spec file explicitly
    System.import('out/unit-tests/hero.spec')
        // #4. wait for all imports to load ...
        //     then re-execute `window.onload` which
        //     triggers the Jasmine test-runner start
        //     or explain what went wrong
        .then(window.onload)
        .catch(console.error.bind(console));
    </script>
</body>

</html>
```

This is what I see:

![image](https://cloud.githubusercontent.com/assets/7313655/11974417/faa5988a-a95b-11e5-9d56-b4da2ae935b0.png)

It does not always show the tests multiple times.

Bug or my error?

Thanks

S

**Comment by TheMysticMan** [comment] 2016-01-27 20:59
@Steveiwonder. I had the same problem. After moving all scripts to the body instead of the head this problem is gone. I know it feels hacky but it gets the job done.

**Comment by slackersoft** [comment] 2016-02-22 20:06
Based on the screenshot where it says it has executed 8 specs, but 12 are listed, it looks like when you're seeing this Jasmine is executing twice. My best guess is that somehow the page gets loaded with your spec file already included (browser back button maybe?). This causes the file to register its specs with Jasmine. Jasmine then executes on `window.onload`, running your 4 specs. Additionally around `onload` time, your script in `body` gets executed which loads the spec file again (adding the specs again), then re-runs Jasmine when that finishes causing Jasmine to run the specs (twice this time), and since the HTML reporter just appends to its summary section, the first run's summary sticks around.

I'm inclined to think that Jasmine is just doing what the page is telling it to in this case, but I'd be happy to look into it if this is still an issue.

Thanks for using Jasmine!

**Comment by verdammelt** [comment] 2016-03-16 18:57
Thanks @TheMysticMan this helped me too.

**Comment by stphivos** [comment] 2016-04-20 23:23
Still an issue for me, tried @TheMysticMan's suggestion but no luck. I'm also following that tutorial, reached up to the next section [pipe-testing](https://angular.io/docs/ts/latest/guide/testing.html#!#pipe-testing) and get duplicated specs in the report. When I hit refresh sometimes I get 7 specs, some times I get 10 specs. Any ideas how to overcome this?

**Comment by karelwgonzalez** [comment] 2016-05-20 19:12
I'm having this issue as well, with @TheMysticMan's solution not working. What's weird, is that it's only doing it with one of my .spec files, and not all of them.

Also, something is causing my custom matchers to not load when tests are being run occasionally (~30% of the time or so).

It seems that @slackersoft is correct in that jasmine is running spec's multiple times. I find it strange that it is selectively running spec's multiple times, though.

Has anyone found anything on this yet?

**Comment by pliski** [comment] 2016-06-12 01:03
As describe [here](http://stackoverflow.com/questions/36756309/angular-2-for-typescript-app-testing-specs-appear-multiple-times-in-jasmine), this behavior appear when some of the spec are loaded before the browser raises the window load event. 

The subsequent window.onload cause the spec to be executed multiple times.

The solution suggested in the stackoverflow question above (remove `.then(window.onload)`), doesn't work for the spec that doesn't get to be loaded before the browser raises the window load event. 

One (ugly) workaround that I find is to retard the execution of the spec like this:

```javascript
setTimeout(function(){ 
    Promise.all([
        System.import('app/1st.spec'),
        System.import('app/my-uppercase.pipe.spec')
    ])   
    .then(window.onload)
    .catch(console.error.bind(console));
}, 1000);
```

**Comment by slackersoft** [comment] 2016-09-28 21:35
The default `boot.js` file that Jasmine uses starts execution of your suite when the `window.onload` event is fired. If your specs are not all loaded (or at least not guaranteed to be loaded) at the time the `window.onload` event fires, you'll want to either [provide your own `boot.js`](https://jasmine.github.io/http://jasmine.github.io/edge/custom_boot.html] or otherwise stop the default onload and start your suite once you've confirmed that all of your specs are loaded.

I'm inclined to think that this isn't really an issue that Jasmine can solve. This is one of the reasons we've split out the things in `boot.js` so they can be overridden in situations like this. I'm going to close this. Thanks for using Jasmine!

**Closed by slackersoft** 2016-09-28 21:35 UTC
