### ISSUE TITLE
It can't do some async work in the reporter hooks.

### ISSUE THREAD

**Issue by CommanderXL** [jasmine/jasmine#1419] opened 2017-09-07 03:26 UTC
## Are you creating an issue in the correct repository?

- When in doubt, create an issue here.
- If you have an issue with the Jasmine docs, file an issue in the docs repo
  here: https://github.com/jasmine/jasmine.github.io
- This repository is for the core Jasmine framework
- If you are using a test runner that wraps Jasmine, consider filing an issue with that library if appropriate:
  - [Jasmine npm](https://github.com/jasmine/jasmine-npm/issues)
  - [Jasmine gem](https://github.com/jasmine/jasmine-gem/issues)
  - [Jasmine py](https://github.com/jasmine/jasmine-py/issues)
  - [Gulp Jasmine Browser](https://github.com/jasmine/gulp-jasmine-browser/issues)
  - [Karma](https://github.com/karma-runner/karma/issues)
  - [Grunt Contrib Jasmine](https://github.com/gruntjs/grunt-contrib-jasmine/issues)

## Expected Behavior

I want to do some async work during the custom reporter hooks.

## Current Behavior

It can't do async work in the custom reporter hooks.

custom reporter:

```javascript
var reporter = {
    ....
    suiteDone () {
        //  It log nothing after 1s
         setTimeout(() => {
             console.log(123)
       }, 1000)
    },
    jasmineDone() {
        // It log nothing after 2s
          setTimeout(() => {
               console.log(456)
         }, 2000)
    }
}
```

## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() {
});
```
## Your Environment

* Version used: 2.8.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 62
* Operating System and version (desktop or mobile): Desktop
* Link to your project:

**Comment by sgravrock** [comment] 2017-10-23 17:01
This looks like a duplicate of #842, so I'm closing it in favor of that issue. If you have a moment to comment on that issue explaining what async things you need to do, it would help us understand the need.

**Closed by sgravrock** 2017-10-23 17:01 UTC
