### ISSUE TITLE
jasmine.any() runs out of memory on 2.6.4

### ISSUE THREAD

**Issue by VictorJuliani** [jasmine/jasmine#1376] opened 2017-06-22 11:43 UTC
- What version are you using?
**2.6.4**
 - What environment are you running Jasmine in (node, browser, etc)?
**6.10.3**
 - How are you running Jasmine (standalone, npm, karma, etc)?
**Karma and yarn**
 - If possible, include an example spec that demonstrates your issue.
`it('should extend TagRequestsComponent', () => {
	expect(component).toEqual(jasmine.any(TagRequestsComponent));
});`

After upgrading from 2.5.2 to 2.6.4 (also tested on 2.6.0 and issue happened too), the spec above stopped working. It's task is to check if the component extends TagRequestsComponent.
What happens is that my test times out and fails for being out of memory (Chrome reaches some 2.5gb of RAM usage). The other tests of this component and of TagRequestsComponent run normally (what makes me think that the problem is not on the component itself then).

The output follows (though it seems of little help):

> RangeError: Invalid string length
>     at StringPrettyPrinter.append (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3831:20)
>     at StringPrettyPrinter.formatProperty (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3821:12)
>     at http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3814:12
>     at StringPrettyPrinter.PrettyPrinter.iterateObject (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3706:7)
>     at StringPrettyPrinter.emitObject (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3807:10)
>     at StringPrettyPrinter.PrettyPrinter.format (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3692:16)
>     at StringPrettyPrinter.formatProperty (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3826:14)
>     at http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3814:12
>     at StringPrettyPrinter.PrettyPrinter.iterateObject (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3706:7)
>     at StringPrettyPrinter.emitObject (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?da99c5b057693d025fad3d7685e1590600ca376d:3807:10)
>

**Comment by slackersoft** [comment] 2017-06-22 18:53
This looks like a duplicate of #1360 which should be fixed in master.

Closing. Thanks for using Jasmine!

**Closed by slackersoft** 2017-06-22 18:53 UTC
