### ISSUE TITLE
Trying to send an SMS via SMPP

### ISSUE THREAD

**Issue by JFnine** [jasmine/jasmine#1372] opened 2017-06-21 11:18 UTC
Hi there!

I'm actually trying to send a SMS via SMPP by using Jasmin, but i can't find the way to do it.

Once I'm designed smppcm

#Connector id                        Service Session          Starts Stops
#SMPP_INX                            started BOUND_TRX        1      0  

a user:

#User id          Group id         Username         Balance MT SMS Throughput
#A*N*             J*                     A*N*         0.0     ND     ND/20.0 

a group:
#Group id        
#J* 

 a mtrouter:

#Order Type                    Rate       Connector ID(s)                                  Filter(s)              
#0     DefaultRoute            0.01000    smppc(SMPP_INX)  

In Logs:

2017-06-21 12:11:47 INFO     838 Added amqpBroker to SMPPClientManagerPB
2017-06-21 12:11:47 INFO     838 Added Redis Client to SMPPClientManagerPB
2017-06-21 12:11:47 INFO     838 Added RouterPB to SMPPClientManagerPB
2017-06-21 12:11:47 INFO     838 Loading/Activating [jcli-prod] profile configuration from //etc/jasmin/store/jcli-prod.smppccs
2017-06-21 12:11:47 INFO     838 Binding submit.sm.SMPP_INX queue to submit.sm.SMPP_INX route_key
2017-06-21 12:11:47 INFO     838 Added a new connector: SMPP_INX
2017-06-21 12:11:47 INFO     838 SMPPClientFactory-SMPP_INX is consuming from queue: submit.sm.SMPP_INX
2017-06-21 12:11:47 INFO     838 Started connector [SMPP_INX]
2017-06-21 12:12:06 INFO     838 Returning a list of 1 connectors
2017-06-21 13:04:06 INFO     838 Returning a list of 1 connectors

  3091 SMS-MO [cid:SMPP_INX] [queue-msgid:XXXX] [status:ESME_ROK] [prio:LEVEL_0] [validity:None] [from:XXXX] [to:XXXX] [content:'Test']

If I execute this file:

  GNU nano 2.3.1                        Fichero: file.py                                                          

import logging
from twisted.internet import reactor, defer
from jasmin.vendor.smpp.twisted.client import SMPPClientTransceiver, SMPPClientService
from jasmin.vendor.smpp.twisted.config import SMPPClientConfig

class SMPP(object):

    def __init__(self, config=None):
        if config is None:
            config = SMPPClientConfig(host='IP', port=2775, username='A*N*', password='XXX')

            # Uncomment line below to recv SMS via ### only
            # config = SMPPClientConfig(host='localhost', port=999, username='uname', password='pwd', addressTon=$
        self.config = config

    @defer.inlineCallbacks
    def run(self):
        try:
            #Bind
            smpp = yield SMPPClientTransceiver(self.config, self.handleMsg).connectAndBind()
            #Wait for disconnect
            yield smpp.getDisconnectedDeferred()
        except Exception, e:
            print "ERROR: %s" % str(e)
        finally:
            reactor.stop()

    def handleMsg(self, smpp, pdu):
        """
        NOTE: you can return a Deferred here
        """
        print "Received pdu %s" % pdu

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    SMPP().run()
    reactor.run()

python file.py 
WARNING:smpp.twisted.client:Establishing TCP connection to 10.22.20.21:2775
WARNING:smpp.twisted.protocol:SMPP connection established from 10.22.20.21 to port 41628
WARNING:smpp.twisted.protocol:Requesting bind as transceiver
DEBUG:smpp.twisted.protocol:Sending PDU: PDU [command: bind_transceiver, sequence_number: 1, command_status: ESME_ROK
system_id: 'A*N*'
password: 'XXX'
system_type: ''
interface_version: 52
addr_ton: None
addr_npi: None
address_range: None
]
DEBUG:smpp.twisted.protocol:Sending data [00000025000000090000000000000001416972654e657400343172336e3374000034000000]
DEBUG:smpp.twisted.protocol:Outbound transaction started with message id 1
INFO:smpp.twisted.protocol:SMPP Client received PDU [command: bind_transceiver_resp, sequence_number: 1, command_status: ESME_ROK]
DEBUG:smpp.twisted.protocol:Received PDU: PDU [command: bind_transceiver_resp, sequence_number: 1, command_status: ESME_ROK
system_id: 'A*N*'
]
DEBUG:smpp.twisted.protocol:Receiving data [00000018800000090000000000000001416972654e657400]
DEBUG:smpp.twisted.protocol:Outbound transaction finished with message id 1
WARNING:smpp.twisted.protocol:Bind succeeded...now in state BOUND_TRX
INFO:smpp.twisted.protocol:SMPP Client received PDU [command: enquire_link, sequence_number: 1, command_status: ESME_ROK]
DEBUG:smpp.twisted.protocol:Received PDU: PDU [command: enquire_link, sequence_number: 1, command_status: ESME_ROK
]
DEBUG:smpp.twisted.protocol:Receiving data [00000010000000150000000000000001]
DEBUG:smpp.twisted.protocol:Sending PDU: PDU [command: enquire_link_resp, sequence_number: 1, command_status: ESME_ROK
]
DEBUG:smpp.twisted.protocol:Sending data [00000010800000150000000000000001]

So, what is exactly the purpose of this? What exactly do i have to do? 

The map of all of this is that i'm connected to a SMSC which will send a SMS if I send a SMS to it but the only way to do this is via SMPP because this SMSC doesn't understand HTTP POST messages.

What I have to do is to create a phyton file to execute it and send the SMS to the SMSC? 

Kind regards.

**Comment by slackersoft** [comment] 2017-06-21 14:43
Dupe of #1341 you're in the wrong repo. Closing

**Closed by slackersoft** 2017-06-21 14:43 UTC
