### ISSUE TITLE
Using --grep will call every defined beforeAll() in your suite/spec

### ISSUE THREAD

**Issue by wburgess-datical** [jasmine/jasmine#1265] opened 2017-01-24 19:25 UTC
Hello!

Essentially when users use the --grep option to delineate which tests run (which is a fantastic feature), it will run every beforeAll() in the file where matches are found, resulting in many superfluous beforeAll()s being triggered. This does not happen with beforeEach().

I reported this issue within the Protractor project, but it was tagged as possibly as issue with Jasmine (and not Protractor).

For much more detail (including full code examples), please see the original issue: https://github.com/angular/protractor/issues/3952

**Comment by slackersoft** [comment] 2017-01-24 23:00
It looks like this is a duplicate of #1175 which was fixed in #1225, but hasn't been released yet.

We're still looking at what is going to be in the 2.6 release of Jasmine, and I don't have an ETA on when that will occur.

Closing. Thanks for using Jasmine!

**Closed by slackersoft** 2017-01-24 23:00 UTC

**Comment by wburgess-datical** [comment] 2017-02-13 16:51
Great news! Thanks for all your hard work.

**Comment by Ukochka** [comment] 2017-05-19 07:52
Hello,

I have updated to Jasmine 2.6, but still BeforeAll methods are running for every suite if I am using --grep=#smoke. What am I doing wrong? Can you help me?

Thanks in advance.

**Comment by slackersoft** [comment] 2017-05-19 20:40
@Ukochka the `--grep` flag isn't part of Jasmine itself, so I'm not sure how it is implemented and how it is calling into Jasmine to accomplish its task. It's also possible that the library you're using to run Jasmine isn't utilizing the newer version of Jasmine you have installed, and that's why you're still seeing this issue.

Hope this helps. Thanks for using Jasmine!

**Comment by dsteinbach** [comment] 2017-09-25 19:27
@wburgess-datical @Ukochka Were you able to solve your issues? I am having the same issue except afterEach() is being called for all tests while beforeEach() is not called even if they dont pass the grep filter.

**Comment by wburgess-datical** [comment] 2017-09-26 13:45
@dsteinbach I am stuck with <2.6 Jasmine due to the version of Protractor we're currently using, so I forked it and took a different approach. I split up my tests into a bunch of different files and organized them into directories so I can set up suites with wildcards; don't really need to --grep anymore.

**Comment by slackersoft** [comment] 2018-03-22 00:33
This issue is resolved within Jasmine itself, but the library you're using to run Jasmine might not be using (or support) the newer versions of Jasmine that include the fix. Please ensure that your Protractor, Karma, or other library that you're using to execute your Jasmine specs is using at least Jasmine 2.6 or later.
