### ISSUE TITLE
Tests are not running

### ISSUE THREAD

**Issue by rochapablo** [jasmine/jasmine#1211] opened 2016-09-15 12:05 UTC
For some reason, when I run ```$ jasmine``` nothing happen and I really don't get it what am I missing.

package.json
```
{
    "jasmine": "^2.5.1",
    "jshint": "^2.7.0"
}
```

jasmine.json
```
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
```

DummySpec.js
```
describe("Dummy", function() {
  it('has a dummy spec to test 2 + 2', function() {
    expect(1 + 1).toEqual(4);
  });
});
```

**Comment by slackersoft** [comment] 2016-09-15 16:27
It sounds like this is a duplicate of jasmine/jasmine-npm#88. Closing this in favor of the discussion over there.

**Closed by slackersoft** 2016-09-15 16:27 UTC
