### ISSUE TITLE
fail() from reporter appears multiple time in results

### ISSUE THREAD

**Issue by maximnaidenov** [jasmine/jasmine#778] opened 2015-02-12 12:31 UTC
If I fail a suite from reporter like this:
```javascript
jasmine.getEnv().addReporter({
    suiteStarted: function(result){
       fail(new Error('Suite failed'));
    }
});
```
I get the error message multiple times, once for every spec as if it was a failed expectation contained in every spec.

```
1) test1
  Message:
    Failed: test error
  Stack:
    ...
  Message:
    Failed: No element found using locator: ...
  Stack:
    ...
2) test2
  Message:
    Failed: test error
  Stack:
    ...
 .....
```
I would expect to see a single error message ?

**Comment by slackersoft** [comment] 2015-02-12 20:41
Why are you failing a suite (or a spec) from the reporter? The reporter shouldn't be modifying the suite it is reporting on, as then it isn't really a reporter anymore but some kind of plugin that messes with your suite.

As for what makes this happen... Because you're calling `fail` in `suiteStarted` you are not in the context of any individual spec, so any failing expectations are effectively being treated as if you were in a `beforeAll` for that suite and thus must get passed down to the specs, because code that occurs in the suite before any specs is assumed to be setup code, and if it fails, all of the specs in that suite should fail.

**Comment by maximnaidenov** [comment] 2015-02-13 06:57
My purpose is to hide a lot of setup code that prepares our test environment. And if there is a problem in the setup there is no meaning in running any spec so I was hoping that failing the suite before any spec will avoid running them.
Actually throwing an error from the start of the suite (outside of beforeAll... blocks)  achieves exactly this effect - get a single error message and no specs run at all. 
Do you have an advice how to 'hide' some test setup code with the purpose to keep the specs clean and focused ?

**Comment by slackersoft** [comment] 2015-02-28 00:19
It sounds like some combination of #414 and #577 would solve your problem, specifically, stopping further execution of specs once a failure occurs. The error message would still be reported multiple times, because failing in a `beforeAll` does cause all of the specs that `beforeAll` encompasses to fail.

I'm going to close this issue, since it seems to be a dupe of one or both of the other two. If you feel this is not the case, please re-open.

Thanks for using jasmine!

**Closed by slackersoft** 2015-02-28 00:19 UTC
Labels: waiting
