### ISSUE TITLE
Getting "Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory" while running unit tests

### ISSUE THREAD

**Issue by Deepangose** [jasmine/jasmine#1928] opened 2021-09-01 11:42 UTC
Recently we've updated our angular app from 4.3.6 to 7.2.16. After new update, we are getting below issue in unit tests while running them.

![image](https://user-images.githubusercontent.com/56765950/131665256-23daf93a-8a3f-40ec-b216-7b35c95a056f.png)

**Further details:**
Angular: 7.2.16
Node version: 10.15.0
@types/jasmine: 2.5.43

Could anyone please help me on this to be fixed?

**Comment by sgravrock** [comment] 2021-09-02 01:45
These kinds of problems are almost impossible to debug over the internet, but I can provide a couple of pointers.

From the screenshot you posted, it looks like Node is running out of memory inside of `karma-sourcemap-loader`. That doesn't have anything to do with Jasmine. Memory issues related to Jasmine would show up in your browser, not in Node. So the first thing I'd do is upgrade Karma to the newest version possible. There's a good chance that that will solve your problem.

You mentioned @types/jasmine 2.5.43, so I assume you're running Jasmine 2.5.x. That's quite old, hasn't been supported in years, and has known bugs including memory leaks that particularly affect Angular test suites. So I suggest upgrading to at least Jasmine 3.0 and preferably all the way to 3.9, even though Jasmine isn't likely the cause of your current problems.

Good luck.

**Comment by Deepangose** [comment] 2021-09-07 14:19
Even tried to upgrade @types/jasmine to 3.0+ version. But still I'm facing same issue.

**Comment by sgravrock** [comment] 2021-09-11 20:26
There are a couple of key things to understand here:

1. Jasmine is almost certainly not causing the crash. So I would not expect changing Jasmine things to fix it. I suggested upgrading Jasmine because it will help with problems you're likely to encounter after you get past the current crash, not because it will fix the crash.
2. Packages whose names start with @types are TypeScript type definitions. They don't contain any executable code. Upgrading them won't change how your system behaves, just whether or not it compiles. If you had e.g. jasmine-core 2.5.0 and @types/jasmine 2.5.43 before and you only upgraded @types/jasmine, then you're still running jasmine-core 2.5.0. 

You didn't say whether or not you've tried upgrading Karma. If you haven't, that remains my first suggestion.

**Comment by Deepangose** [comment] 2021-09-16 07:36
Tried by upgrading karma too. But same issue still persists.

**Comment by sgravrock** [comment] 2021-10-02 17:22
I'm sorry this isn't going well for you.

I'm going to close this since there's nothing here to suggest a problem with Jasmine. Feel free to open a new issue with more information if you see something new that points at Jasmine, but keep in mind that I might not be able to help unless you can provide complete steps to reproduce the error.

**Closed by sgravrock** 2021-10-02 17:22 UTC
