### ISSUE TITLE
TypeError: this.expectationResultFactory is not a function

### ISSUE THREAD

**Issue by DarthOpto** [jasmine/jasmine#1292] opened 2017-03-15 15:49 UTC
- Jasmine-core 2.5.2

The following is the test I am running:

```
/// <reference path="visualize.page.ts" />
/// <reference path="../../reference.d.ts" />

import { CommonPageItems } from '../../../../test/e2e/common.page'
import { NewVisualizationView } from './visualize.page'
import { ListView } from '../../../../test/e2e/listView.page'

let common = new CommonPageItems()
let vizList = new ListView()
let vizPage = new NewVisualizationView()

describe('create visualizations', () => {
    /**
     * Create Visualizations Test Suite
     */

    beforeAll(() => {
        vizPage.navigateToApp()
    })

    afterAll(() => {
        common.signOut()
    })

    beforeEach(() => {
        vizPage.newViz()
    })

    it('bar chart - additional config', () => {
        vizPage.chooseChart('bar')
        expect(vizPage.additionalConfigAlert.getText()).toMatch('Bar chart needs at least 1 measure and 0 breakdowns.')
        vizPage.returnToVizListView()
    })
})
```

I run the following command to get this run:
`gulp e2e --suite visualize --baseUrl <a URL goes here>`

The test runs and passes however the browser session never closes and I get the following error:

```
<REST OF PATH>/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2219
      this.result.failedExpectations.push(this.expectationResultFactory(data));
                                               ^
TypeError: this.expectationResultFactory is not a function
    at Suite.onException (/Users/curtissalisbury/src/github.com/artemishealth/artemis-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2219:48)
    at QueueRunner.onException (/Users/curtissalisbury/src/github.com/artemishealth/artemis-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2330:28)
    at onException (/Users/curtissalisbury/src/github.com/artemishealth/artemis-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1924:12)
    at Timeout._onTimeout (/Users/curtissalisbury/src/github.com/artemishealth/artemis-app/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1910:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

This was literally working yesterday and this morning I come in and I am getting the above mess.

 Thanks for using Jasmine!

**Comment by slackersoft** [comment] 2017-03-15 17:18
Are you sure you didn't somehow get bumped back to jasmine-core 2.4.x? The code in Jasmine to handle failures in global `beforeAll` and `afterAll` didn't get implemented until 2.5 and it looks like the line numbers in that stacktrace match up with the line number in 2.4.0, but not 2.5.0 or later.

From where the error is coming from, it looks like something (probably cleanup in an `afterAll`) is taking too long and hitting Jasmine's timeout. You should also be able to [set a custom timeout](https://jasmine.github.io/edge/introduction#section-57) if the action can take longer than the default 5 seconds.

Hope this helps. Thanks for using Jasmine!

**Comment by DarthOpto** [comment] 2017-03-15 17:32
Yes, it looks like `jasmine-reporters` is depending on `2.4.1`.

**Comment by slackersoft** [comment] 2017-03-15 18:16
I'm going to close this issue then, since it sounds like the issue is with jasmine-reporters and not jasmine itself.

Thanks for using Jasmine!

**Closed by slackersoft** 2017-03-15 18:16 UTC
