### ISSUE TITLE
Stop Jasmine javascript testing after first it fails.

### ISSUE THREAD

**Issue by gavdix** [jasmine/jasmine#1253] opened 2017-01-13 10:02 UTC
I am new to jasmine javascript testing and for starting i got a dummy project from internet with some basic functions and test spec for same. I am using jasmine 2.5 and using jasmine.js library for loading jasmine related functionality. I am running this basic test in chrome browser.

My source file: MathUtils.js: 
```
MathUtils = function() {};

MathUtils.prototype.sum = function(number1, number2) {
		return number1 + number2;
}

MathUtils.prototype.substract = function(number1, number2) {
	return number1 - number2;
}
```

and spec file for this is: 
```
describe("MathUtils", function() {
	var calc;
	beforeEach(function() {
		calc = new MathUtils();
	});
	it("should be able to calculate sum of 10 and 40", function() {
		expect(calc.sum(10, 40)).toEqual(54);	
	});
        it("should be able to calculate diff of 40 and 10", function() {
		expect(calc.substract(40, 10)).toEqual(30);	
	});
});
```

In spec, 1st case will fail and 2nd will pass. 
Here I want a mechanism to stop execution when 1st case fails i.e. when 1st case fails 2nd should not execute. Right now even if 1st case fails, it executes remaining cases and shows report with test cases fail/pass status.

There are already issue with same requirement raised specially #414 and #577 . I tried to use the solution but could not achieve desired result. (or you can say i did not understand it)

Can you give solution in naive way, or in context of above code so it will be very basic approach to understand jasmine abort test feature for new developer.

**Comment by lmj0011** [comment] 2017-01-15 01:04
you may need to look into customizing configuration to be loaded by `boot.js`
https://jasmine.github.io/2.0/boot.html
https://jasmine.github.io/2.5/custom_boot.html

I know this option is available if you're using node to run your tests.
https://jasmine.github.io/2.5/node.html#section-21

**Comment by gavdix** [comment] 2017-01-16 06:16
Node js command i saw, but i am not using node js to run my tests. Let me check this boot.js options. I will check and shall update the outcome. Thanks in advance. :)

**Comment by gavdix** [comment] 2017-01-16 11:31
@lmj0011 As you mentioned "it's not clear on how to set the option" in given link. 
I did not find any solution to my problem. Can anyone update any solution?

**Comment by slackersoft** [comment] 2017-02-09 22:42
This sounds like a duplicate of #414 which has not been implemented. The current eager stopping functionality is to stop further `expect` calls in a single spec once one of them has failed.

Closing. Thanks for using Jasmine!

**Closed by slackersoft** 2017-02-09 22:42 UTC
