### ISSUE TITLE
mock clock in 2.5.0 advances date by sum of previous calls to tick

### ISSUE THREAD

**Issue by Necroskillz** [jasmine/jasmine#1198] opened 2016-09-05 11:47 UTC
seems that pull request #980 may have fixed an issue, but it broke the clock. mockDate.tick is now called with endTime, which is accumulated from all calls to tick.

Example:
```
fdescribe('test', function () {
    beforeEach(function() {
        jasmine.clock().install();

        self.baseDate = new Date(2016, 0, 1, 5, 30, 20);

        jasmine.clock().mockDate(self.baseDate);
    });

    function offsetFromBaseDate() {
        return new Date().getTime() - self.baseDate.getTime();
    }

    it('should work', function () {
        expect(offsetFromBaseDate()).toBe(0);

        jasmine.clock().tick(60000);

        expect(offsetFromBaseDate()).toBe(60000);

        jasmine.clock().tick(60000);

        expect(offsetFromBaseDate()).toBe(120000);
    });

    afterEach(function() {
        jasmine.clock().uninstall();
    });
}); 
```

fails with ` Expected 180000 to be 120000.`

**Comment by slackersoft** [comment] 2016-09-07 22:52
Closing this as a duplicate of #1190. The fix should be available in 2.5.1

**Closed by slackersoft** 2016-09-07 22:52 UTC
