### ISSUE TITLE
Unable to get spec description and test description

### ISSUE THREAD

**Issue by bharathp** [jasmine/jasmine#1112] opened 2016-05-10 11:06 UTC
Hi,
I'm in need of getting my spec description in "onPrepare" block in order to replicate them in my own customized html report and appending 'it' block's title to my screenshot.png file name.

_Able to get the spec name only when control gets into 'it' block, but not before or after that._

I've stuck here from many days and been trying in multiple ways as mentioned in many blogs but couldn't achieve this.
I think this feature is most important for anyone to access their own test names. Could you please provide any possible solution to achieve this.

Thanks  in advance.

**Comment by Gerg** [comment] 2016-09-27 00:39
This appears to be a duplicate of #1212. See discussion in that thread.

**Closed by Gerg** 2016-09-27 00:39 UTC
