### ISSUE TITLE
stopSpecOnExpectationFailure not work as expected

### ISSUE THREAD

**Issue by netmajor** [jasmine/jasmine#1313] opened 2017-04-11 11:55 UTC
I am using Webdriver with JasmineJs. In WDIO configuration I have set 
```
jasmineNodeOpts: {
    stopSpecOnExpectationFailure: true
  },
```
I am expecting that in that test case:

```
describe('Log to the site', () => {
 
  it('authorize', () => {
    //some webdriver steps
  });

  it('go to other site', () => {
      //some webdriver steps
  });
});
```

When my steps in authorize it failed, my tests not go to next it , but continue executing next describe.
I am right?

**Comment by slackersoft** [comment] 2017-04-11 13:54
In Jasmine/BDD parlance an `it` is called a spec and `describe` is a suite. So `stopSpecOnExpectationFailure` just bails out of the current `it`. 

Hope this helps. Thanks for using Jasmine!

**Comment by netmajor** [comment] 2017-04-11 18:01
How should I use stopSpecOnExpectationFailure to exit current suite after failure in spec?
I can only think about using beforeEach. Do you have any solution for that problem?

**Comment by slackersoft** [comment] 2017-04-11 18:07
If you want to stop the entire Jasmine suite on the first spec failure, this is something we're looking into, the existing issue for that is #414.

If you want to skip out from one `describe` into the next `describe` when an `it` from fails, I don't think that is something we're likely to have in Jasmine. In general, you should probably try to have your specs be isolated from one another so this isn't necessary. If some core functionality breaks, it probably makes sense for multiple specs to break as well.

**Comment by slackersoft** [comment] 2017-07-26 00:44
It sounds like this has become a duplicate of #414, so I'm going to close it. Thanks for using Jasmine!

**Closed by slackersoft** 2017-07-26 00:44 UTC
