### ISSUE TITLE
Error when expecting a specific enum value

### ISSUE THREAD

**Issue by chrisvelevitch** [jasmine/jasmine#1723] opened 2019-06-22 11:36 UTC
I'm using Jasmine with an Angular 7 app and I have a test where:-
```typescript
someValueContainingAnEnum = MyEnum.EnumValue
...
expect(someValueContainingAnEnum).toEqual(MyEnum.EnumValue);
```
and I'm getting a compiler error:-
```typescript
ERROR in src/my.component.spec.ts: error TS2345: Argument of type 'MyEnum.EnumValue' is not assignable to parameter of type 'Expected<MyEnum.EnumValue>'.
```
and `MyEnum` is defined as:-
```typescript
export enum MyEnum {
     EnumValue,
     ...
}
```
## Expected Behavior
No compile errors.
## Current Behavior
Compile errors.
## Possible Solution
If I don't assign `someValueContainingAnEnum` a value, the test compiles. I suspect the compiler has made a type inference that is incompatible with Jasmine.
## Context
The code is not compilable.
## Your Environment
* Jasmine-core: 3.4.0
* Angular: 7.2.15
* Typescript: 3.2.4
* @types/jasmine: 3.3.13
* @types/jasminewd2: 2.0.6
* Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)
* Node: 12.3.1
* MacOS: 11.13.6

**Comment by elliot-nelson** [comment] 2019-06-26 12:19
Although frustrating, right now I believe this is a language problem - see https://github.com/microsoft/TypeScript/issues/28102.  (Essentially, types extended from `WrapperType<Enum>` do not infer `WrapperType<Enum.NAME>`.)

I would suggest opening a ticket against https://github.com/DefinitelyTyped/DefinitelyTyped for jasmine if I thought there was a way to work around that, but I don't think there is until the type inference is fixed.

A couple local workarounds in the meantime:

### Avoid direct assignment

As you already discovered, if the compiler can't infer locally what _specific_ value it is, the problem will go away.  e.g.:

```
describe('a working suite', function() {
    type Context = {
        value: Enum;
    }

    beforeEach(function(this: Context) {
        this.value = Enum.A;
    });

    it('is annoying, but works', function(this: Context) {
        // The compiler doesn't know the value, so this compiles.
        expect(this.value).toEqual(Enum.B);
    });
});
```

### Cast to Enum

Probably much simpler, you can cast to Enum almost anywhere and the problem will go away:

```
// Up front
const value = Enum.A as Enum;
expect(value).toEqual(Enum.B);

// Or in expect
const value = Enum.A;
expect(value as Enum).toEqual(Enum.B);
```

Hope that helps!

**Comment by be-ndee** [comment] 2019-06-27 09:06
Having the same issue here. Are you sure it is a language problem? I discovered it with enums as well, and then I noticed that there is the problem with this code as well:

```typescript
const x: (1|2) = 1;
expect(x).toBe(2); // error: Argument of type '2' is not assignable to parameter of type 'Expected<1>'.

const y: number = 1;
expect(y).toBe(2); // works

const z = 1;
expect(z).toBe(2); // works
```

**Comment by elliot-nelson** [comment] 2019-06-27 13:28
Thanks for the additional example... I still think this isn't a jasmine typing problem, but my original explanation is definitely full of holes!  It looks like any time type inference collapses the type, you could get this issue.

According to the answer (so far) on question https://stackoverflow.com/questions/56791777/how-to-avoid-collapsing-a-wrapped-union-type/56791973#56791973, I think this is considered "working as intended" -- if the compiler can determine which piece of any union type is selected, it will collapse the type.

**Comment by elliot-nelson** [comment] 2019-06-27 13:40
Also see link to this issue: https://github.com/microsoft/TypeScript/issues/8513, which has several posts (some explaining why, some with issues) about the feature in question, which is called "control flow analysis" (compiler keeping track whenever it can of the actual value of variables, not just their declared types).

**Comment by slackersoft** [comment] 2019-09-05 00:22
I think this issue more likely belongs in https://github.com/DefinitelyTyped/DefinitelyTyped as that is where the typings for Jasmine live. I'm sure many people would love to see a type assertion there to help solve this, but I'm not entirely sure how to make that all work.

I'm going to close this issue, but would be happy to see a link or something here to a relevant issue/solution in the typings for folks who find this issue in the future. Thanks for using Jasmine!

**Closed by slackersoft** 2019-09-05 00:22 UTC
