### ISSUE TITLE
spyOnProperty does not work with object literals.

### ISSUE THREAD

**Issue by silverbucket** [jasmine/jasmine#1415] opened 2017-08-23 12:31 UTC
## Expected Behavior

 I seem completely unable to override existing object literals to provide mock data during tests. Initially I tried with object properties 2 levels deep, but it seems that it also does not work even at the first level.

    var foo = { 
      bar: "test",
      pizza: {
        toppings: "cheese"
      }
    };
    spyOnProperty(foo, "bar", "get").and.returnValue("baz");
    spyOnProperty(foo.pizza, "toppings", "get").and.returnValue("pineapple");
    expect(foo.bar).toEqual("baz");
    expect(foo.pizza.toppings).toEqual("pineapple");

## Current Behavior

    - Error: Property bar does not have access type get
    
## Suite that reproduces the behavior (for bugs)

```javascript
describe("BASIC test of object properties", () => {
    const foo = {
        bar: "test",
        pizza: {
            toppings: "cheese"
        }
    };
    it("test base-level object property", () => {
        spyOnProperty(foo, "bar", "get").and.returnValue("baz");
        expect(foo.bar).toEqual("baz");
    });
    it("test second level object property", () => {
        spyOnProperty(foo.pizza, "toppings", "get").and.returnValue("pineapple");
        expect(foo.pizza.toppings).toEqual("pineapple");
    });
});

//   BASIC test
//    ✗ test base-level object property
//      - Error: Property bar does not have access type get
//    ✗ test second level object property
//      - Error: Property toppings does not have access type get
```

## Your Environment
* jasmine v2.7.0
* jasmine-core v2.7.0
* node.js v8.2.1
* Mac OS X - Sierra

**Comment by slackersoft** [comment] 2017-08-23 23:49
`spyOnProperty` is intended for use on objects that have used `Object.defineProperty`, since that is implemented with a function behind it and can't be modified by just assigning to it. If you just have basic properties on an object, you should be able to just assign over them.

Since this is the current expected behavior, I'm going to close this.

Hope this helps. Thanks for using Jasmine!

**Closed by slackersoft** 2017-08-23 23:49 UTC

**Comment by silverbucket** [comment] 2017-08-24 08:27
@slackersoft thanks for the clarification, do you think this should be clarified in the documentation? It's really not that clear from reading the API doc on this function.

**Comment by guzmanoj** [comment] 2020-10-14 12:20
If you **truly** need it, here's what you can do:
```

  const matDialogDataMock = {
    get data() {
      return {};
    },
    get formAction() {
      return FormAction.ADD;
    }
  }
```

Then you can spy the properties like this:
`  spyOnProperty(matDialogDataMock, 'formAction').and.returnValue(FormAction.EDIT);`

**Comment by triskweline** [comment] 2021-12-02 13:56
I wrote a function [`spyOnValueProperty()`](https://makandracards.com/makandra/507722-jasmine-spy-on-value-properties)  that converts a value property to getters and setters so it can be mocked with Jasmine.

**Comment by tarekahf** [comment] 2022-10-24 05:46
> I wrote a function [`spyOnValueProperty()`](https://makandracards.com/makandra/507722-jasmine-spy-on-value-properties) that converts a value property to getters and setters so it can be mocked with Jasmine.

Exactly what I was looking for.
