### ISSUE TITLE
spy always returns 0 for the length

### ISSUE THREAD

**Issue by mfeingold** [jasmine/jasmine#1007] opened 2015-12-25 01:06 UTC
I need to spy on a callback function which can be called in 2 different ways depending on the number of parameters. Unfortunately the spy function returned by spyOn always returns 0 as the value of its length property regardless of the number of parameters of the original callback. Is there a way to work around this behavior?

**Comment by gpiress** [comment] 2015-12-30 01:08
So as I see it, you want to know which version of the callback your test has called, is that right?

If that is the case, you need to create a spy on the callback method and then you make an `expect` statement with that callback call, as in:

`expect(methodSpied.calls.mostRecent().args.length).toEqual(2);`, 

as per the docs (in the __Other tracking properties__ section).

The code above checks the last call of the spied method with `calls.mostRecent()`, which is an object that has an _args_ property, that holds the arguments of the last call to the spied method.

**Comment by mfeingold** [comment] 2015-12-30 01:55
On Tue, Dec 29, 2015 at 7:09 PM, gpiress <notifications@github.com> wrote:

> So as I see it, you want to know which version of the callback your test
> has called, is that right?
>
Not quite. As the spy to the method I need to spy on is built, the
signature of the spy differs from the signature of the original method, The
original method (function) has its length property set to 2 or 3 depending
on the use case, while the spy always has its length property set to 0. The
code under testing relies on the correct value of this property and because
of this it breaks.


-- 
Michael Feingold, President
401 Huehl RD, Suite 2A,
Northbrook, IL 60062
Email mfeingold@hill30.com

**Comment by slackersoft** [comment] 2016-02-16 23:25
It looks like this is a duplicate of #991. I'm going to close this as a duplicate. As mentioned in that thread we would be happy to review a pull request to fix this, but I'm not sure what it would look like.

Thanks for using Jasmine!

**Closed by slackersoft** 2016-02-16 23:25 UTC
