### ISSUE TITLE
done.fail() results in timeout

### ISSUE THREAD

**Issue by albertreed** [jasmine/jasmine#1204] opened 2016-09-13 01:56 UTC
Calling done.fail() or fail() still waits for the timeout and then prints an erroneous error message stating that the async callback wasn't invoked in time. The error message seems to get through correctly (the message was "Failed" below)

============

Message:
    Failed
  Stack:
    Error: Failed
        at /Users/areed/Projects/chilmark/spec/chilmarkSpec.js:45:16
        at process._tickCallback (node.js:369:9)
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:92:15)

**Comment by Gerg** [comment] 2016-09-16 16:29
What version on Jasmine are you using? Can you provide an example spec that demonstrates this behavior?

**Comment by httpdigest** [comment] 2016-09-26 10:35
We are experiencing this, too. It happens with every test case that is executed asynchronously, such as via a task or microtask (ES "Job"). The simplest test case could to reproduce this, would be via setTimeout():
```JavaScript
it('...', done => {
  setTimeout(() => {
    fail('...');
  }, 0);
});
```
Our real usecase is more sophisticated with a microtask (via a Promise).
Using done() in asynchronous tests however works. So done() must be doing something more than fail() with regards to notifying test completion.

**Comment by slackersoft** [comment] 2016-09-26 16:26
@httpdigest You should use `done.fail()` in an async spec to get it to continue to the next spec. If you're seeing the same behavior with `done.fail()` as with `fail()` alone, we would definitely like to look into it.

**Comment by httpdigest** [comment] 2016-09-26 17:52
Thanks! Indeed, using `done.fail()` solves the issue. From my side, there are no issues with asynchronous tests and done/done.fail() anymore.

**Comment by Gerg** [comment] 2016-09-28 00:24
Closing since things seem to be working as intended if you use `done.fail()`. Please re-open if you are able to reproduce the original issue.

**Closed by Gerg** 2016-09-28 00:24 UTC
Labels: waiting
