### ISSUE TITLE
Jasmine fails on errors in React 16 components

### ISSUE THREAD

**Issue by the-spyke** [jasmine/jasmine#1453] opened 2017-11-27 14:38 UTC
## Expected Behavior

The test should be green

## Current Behavior

Test fails.

## Suite that reproduces the behavior (for bugs)

A React component has an error which is caught by an Error Boundary. React prints the error in console and Jasmine fails the test.

[CodePen](https://codepen.io/the-spyke/pen/xPaKeN)

## Context

Not sure if it's desired behavior in Jasmine.

## Your Environment

* Version used: 2.8.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 62, Node 8.9.1
* Operating System and version (desktop or mobile): Ubuntu 17.04 (4.10.0-40-generic)
* Link to your project:

**Comment by sgravrock** [comment] 2017-11-27 16:55
I was able to reproduce the issue [without using an Error Boundary](https://codepen.io/anon/pen/VrGKEG). It looks like React is triggering an `error` event whenever a component throws an exception. Failing the current spec in response to an `error` event is very much expected behavior -- `error` events during spec execution almost always indicate the kind of bugs that a test suite should catch. But I can see how it makes it difficult to do things like write integration tests for error handling in a React app. I'm open to suggestions for how to improve that scenario without making error handling worse in general.

**Comment by the-spyke** [comment] 2017-11-27 17:03
Yeah, I've added an Error Boundary to my sample to show that I can't catch this error.

Does Jasmine have a way to expect on error events?

**Comment by the-spyke** [comment] 2017-11-28 14:00
My temporary solution for now:

```javascript
function catchWindowError(testSpec, handleError) {
    const backup = window.onerror;
    const unhandledErrors = [];

    function onUnhandledError(error) {
        unhandledErrors.push(error);
    }

    let regularError;

    try {
        window.onerror = onUnhandledError;

        testSpec();
    } catch (error) {
        regularError = error;
    }

    window.onerror = backup;

    handleError(regularError, unhandledErrors);
}

it("should throw an error on empty props", () => {
    catchWindowError(() => {
        mount(<MyComp />);
    }, error => {
        expect(error).toEqual(new Error("MockCmp requires <name> prop"));
    });
});
```

**Comment by slackersoft** [comment] 2017-12-15 01:28
Jasmine doesn't currently have any way to `expect` an error event to occur. We'd be happy to review a pull request to add a new matcher similar to `toThrowError` that registers itself with Jasmines existing `GlobalError` handler to receive these without failing the spec.

Thanks for using Jasmine!

**Comment by craigkovatch** [comment] 2017-12-27 05:23
@slackersoft I think this issue should be renamed -- as @sgravrock mentioned, Error Boundary usage is not required for Jasmine to fail to catch thrown errors in React 16 components.

**Comment by sgravrock** [comment] 2018-05-09 03:40
I spent a bit of time digging into this recently. I'm seeing some inconsistency in whether or not a global `error` event is triggered when React catches an exception from a component. In the example above, it is. In the examples I've set up myself, it isn't. I'm not sure if the difference is due to React versions, use of Enzyme, where in the lifecycle the exception is thrown, or something else. In the case where no `error` event is triggered, there's nothing that Jasmine can do because it has no way of knowing about the error.

I've had some success with using an error boundary to take control of the behavior, e.g.:

```
export class SpecErrorBoundary extends React.Component {
   componentDidCatch(error, info) {
      if (this.props.errorHandler) {
         this.props.errorHandler(error);
      } else {
         // Rethrow from a setTimeout so react can't catch it.
         // This way it will fail the test suite even if the error
         // might not be associated with the test that caused it.
         setTimeout(() => {
            throw error;
         });
      }
   }

   render() {
      return this.props.children;
   }
}

```

This can be used to write tests that expect an error to occur, that fail if an error occurs, or (if you really want to) that don't care if an error occurs:

```
it('throws an exception', async function() {
   const errorHandler = jasmine.createSpy('errorHandler');
   mount(
      <SpecErrorBoundary errorHandler={errorHandler}>
         <Throws />
      </SpecErrorBoundary>
   );
   expect(errorHandler).toHaveBeenCalledWith(
      jasmine.objectContaining({message: 'nope!'})
   );
});

it('fails the suite if an exception is thrown', async function() {
   mount(
      <SpecErrorBoundary>
         <Throws />
      </SpecErrorBoundary>
   );
});
```

There are a couple of major issues still: React will log the error to the console even if it's caught by an error boundary, and Enzyme will throw if you try to do anything to the wrapper after the error is caught. I don't believe there's anything Jasmine can do about those issues, and to my way of thinking they seriously limit the usefulness of any test that intentionally causes a component to throw.

To cover all the bases around React 16 errors and error boundaries, I think we need three things:

1. A way to control whether a thrown error fails the test.
2. A way to control whether the error is logged to the console.
3. A way to inspect the render tree of an error boundary after it catches an error. 

I don't think Jasmine itself can or should solve any of those problems. The first is best handled with individual test code, as above. The second is ultimately up to react-dom, and the third seems to be solidly on Enzyme's turf (or on the turf of whatever it is that people use instead of Enzyme). 

Further discussion and new ideas are welcome but as it is I'm inclined to close this since I don't think there's anything that Jasmine can do to help the situation.

**Comment by the-spyke** [comment] 2018-05-14 08:17
Not sure how it works for you. I've used MyComp for CodePen, copied you error boundary and tests, and added one more test that always pass.

Code:

```js
class SpecErrorBoundary extends React.Component {
    constructor(props) {
        super(props);

        this.state = { isError: false };
    }

    componentDidCatch(error, info) {
        if (this.props.errorHandler) {
            this.props.errorHandler(error);
        } else {
            // Rethrow from a setTimeout so react can't catch it.
            // This way it will fail the test suite even if the error
            // might not be associated with the test that caused it.
            setTimeout(() => {
                throw error;
            });
        }

        this.setState({ isError: true });
    }

    render() {
        if (this.state.isError) {
            return "Error";
        }

        return this.props.children;
    }
}

class MyComp extends React.Component {
    componentDidMount() {
        throw new Error("Ha-ha!");
    }
    render() {
        return <span>{"No error"}</span>;
    }
}

describe("React 16 issues", () => {

    it("should always pass", () => {
        expect(true).toBe(true);
    });

    it("throws an exception", () => {
        const errorHandler = jasmine.createSpy("errorHandler");

        mount(
            <SpecErrorBoundary errorHandler={errorHandler}>
                <MyComp />
            </SpecErrorBoundary>
        );

        expect(errorHandler).toHaveBeenCalledWith(
            jasmine.objectContaining({ message: "Ha-ha!" })
        );
    });

    xit("fails the suite if an exception is thrown", () => {
        mount(
            <SpecErrorBoundary>
                <MyComp />
            </SpecErrorBoundary>
        );
    });

});
```

Results:

```
START:
  React 16 issues
    ✔ should always pass
ERROR: 'The above error occurred in the <MyComp> component:
    in MyComp (at react-tests.js:81)
    in SpecErrorBoundary (created by WrapperComponent)
    in WrapperComponent

React will try to recreate this component tree from scratch using the error boundary you provided, SpecErrorBoundary.'
    ✖ throws an exception

Finished in 0.024 secs / 0.021 secs @ 11:14:18 GMT+0300 (+03)

SUMMARY:
✔ 1 test completed
ℹ 1 test skipped
✖ 1 test failed

FAILED TESTS:
    ✖ throws an exception
      Chrome 66.0.3359 (Linux 0.0.0)
    Uncaught Error: Ha-ha! thrown
```

**Comment by the-spyke** [comment] 2018-05-14 08:36
Okay, with `jasmine@3.1.0` I've got duplication even in simple test file:

```
START:
  React 16 issues
    ✔ should always pass
ERROR: 'The above error occurred in the <MyComp> component:
    in MyComp (at react-tests.js:81)
    in SpecErrorBoundary (created by WrapperComponent)
    in WrapperComponent

React will try to recreate this component tree from scratch using the error boundary you provided, SpecErrorBoundary.'
    ✖ throws an exception
    ✖ throws an exception 

Finished in 0.029 secs / 0.021 secs @ 11:34:29 GMT+0300 (+03)

SUMMARY:
✔ 1 test completed
ℹ 1 test skipped
✖ 2 tests failed

FAILED TESTS:
  React 16 issues
    ✖ throws an exception
      Chrome 66.0.3359 (Linux 0.0.0)
    Uncaught Error: Ha-ha! thrown

    ✖ throws an exception 
      Chrome 66.0.3359 (Linux 0.0.0)
    Uncaught Error: Ha-ha! thrown
```

**Comment by sgravrock** [comment] 2018-05-14 15:09
I haven't been able to reproduce either the test failure or the duplication. I wonder if the duplication has something to do with the reporter that you're using. Here's what I get with `ConsoleReporter`, Jasmine's default reporter:

```
Randomized with seed 67197
Started
*.Error: Uncaught [Error: Ha-ha!]
    at reportException (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at invokeEventListeners (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
    at HTMLUnknownElementImpl._dispatch (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at HTMLUnknownElementImpl.dispatchEvent (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
    at HTMLUnknownElementImpl.dispatchEvent (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
    at HTMLUnknownElement.dispatchEvent (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
    at Object.invokeGuardedCallbackDev (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/react-dom/cjs/react-dom.development.js:138:16)
    at invokeGuardedCallback (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/react-dom/cjs/react-dom.development.js:187:29)
    at commitRoot (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/react-dom/cjs/react-dom.development.js:11594:9)
    at completeRoot (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/react-dom/cjs/react-dom.development.js:12502:36) Error: Ha-ha!
    at MyComp.componentDidMount (/Users/work/workspace/jasmine-enzyme-update-exception-demo/src/Throws.test.js:12:15)
    at commitLifeCycles (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/react-dom/cjs/react-dom.development.js:9784:26)
    at commitAllLifeCycles (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/react-dom/cjs/react-dom.development.js:11455:9)
    at HTMLUnknownElement.callCallback (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/react-dom/cjs/react-dom.development.js:100:14)
    at invokeEventListeners (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
    at HTMLUnknownElementImpl._dispatch (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at HTMLUnknownElementImpl.dispatchEvent (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
    at HTMLUnknownElementImpl.dispatchEvent (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
    at HTMLUnknownElement.dispatchEvent (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
    at Object.invokeGuardedCallbackDev (/Users/work/workspace/jasmine-enzyme-update-exception-demo/node_modules/react-dom/cjs/react-dom.development.js:138:16)
The above error occurred in the <MyComp> component:
    in MyComp
    in SpecErrorBoundary (created by WrapperComponent)
    in WrapperComponent

React will try to recreate this component tree from scratch using the error boundary you provided, SpecErrorBoundary.
.

Pending:

1) React 16 issues fails the suite if an exception is thrown
  Temporarily disabled with xit

3 specs, 0 failures, 1 pending spec
Finished in 0.036 seconds
Randomized with seed 67197 (jasmine --random=true --seed=67197)
✨  Done in 1.07s.
```

**Closed** 2022-07-01 01:12 UTC
Labels: React, help needed

**Comment by craigkovatch** [comment] 2022-07-01 02:43
Yay! Thank you!
