### ISSUE TITLE
Custom messages for passed expectations

### ISSUE THREAD

**Issue by adityaparab** [jasmine/jasmine#1127] opened 2016-06-03 07:57 UTC
Hi,

There are various places where it makes sense to have a custom message for passed test cases.
This is not an "issue" as such and the jasmine framework is doing a pretty good job for what it is intended.

However, I have faced many situations where if I write of own report generator, It is impossible to add an explanatory message for all the expectations. It makes HTML/Excel reports much readable,

There is a condition in the buildExpectationResult function in [ExpectationResult.js](https://github.com/jasmine/jasmine/blob/master/src/core/ExpectationResult.js)

```
    function message() {
      if (options.passed) {
        return 'Passed.';
      } else if (options.message) {
        return options.message;
      } else if (options.error) {
        return messageFormatter(options.error);
      }
      return '';
    }
```

if this the `option.passed` condition evaluates true, it overrides my custom message with a string "Passed."

Do you think changing this condition to 

`if (options.passed && !options.message) {` 

would make it more useful?

I have tested in on my local setup and everything seems to work as expected.
If I set custom message for expectations (using functions like `since()` ) then the passed and failed test cases use that message. If I don't pass any custom message, it returns passed.

Following this approach, I was expecting the framework to return something like, for example, `Expected true to be true` but it seems to be working perfectly fine.

I believe this would be a great value add to the framework.

----------------------

Use case where it comes handly

```
    var tc1 = it('Should navigate to SomePage', function () {
        tc1.result.tcName = "TC1";
        tc1.result.tcDesc = "Verify create button is present";
        tc1.result.expectations = [];
        since('Verify create button is present') // This is how the message is passed.
        .expect(SomePage.CreateButton.isPresent()).toBe(true);
    });
```

This generates the output as

```
"passedExpectations": [{
    "matcherName": "toBe",
    "message": "Verify create button is present",
    "stack": "",
    "passed": true
}]
```

Pretty handy, isn't it?
Now, If I don't have ability to add custom message, I have to build my own expecation results again by writing each each expecation twice. (2nd time for my own result generation) like

```
    var tc1 = it('Should navigate to SomePage', function () {
        tc1.result.tcName = "TC1";
        tc1.result.tcDesc = "Verify create button is present";
        tc1.result.expectations = [];
        expect(SomePage.CreateButton.isPresent()).toBe(true); // This will build the native jasmine results object
        SomePage.CreateButton.isPresent().then(function(isPresent){ // now I have to manually build my own result object
            tc1.result.expectations.push({
                title: 'Verify create button is present',
                status: isPresent ? 'Passed' : 'Failed'
            })
	    });
    });
```
As you can see, this makes the test cases look dirty. And the logic gets scattered all over the place.

It would be great, if all the results logic is at one place and is handled by the framework itself. :)

**Comment by t2n** [comment] 2016-07-01 11:43
or maybe extend all the default matchers so that we can do something like `expect(elementsFound).toBe(5).because('expected to have 5 elements after doing something')`

so html reporter could provide more feedback on which expectation passed and which not

I guess people would benefit from such behavior a lot.

**Comment by faredis** [comment] 2016-07-14 00:46
This also means the the custom matcher's passed messages are changed to "Passed."

I would find it useful when working with protractor as a number of the expect statements are testing a number of things  so to make it easier to read we created custom matchers and we would like the  passed messages to appear in the reports so that we can show our customers the tests we have run without  showing them the actual test code. 

So a customer requirement:
`Given an admin user
When they log into the website
then they have access to the admin page` 

Translates to:
```
describe ("Given an admin User", function() {
  ...
    it("logs into the website", function(){
         ...
         expect(something).toHaveAdmimAccess();
    }
...
}
```

`toHaveAdminAccess` will then have a user friendly passed message along the lines of the requirement above that will appear in our reports.

What is odd is that the error message is generated in one place and the passed message in another. Therefore I think they need to be moved together and hopefully somewhere that is exposed so that we can alter it.

Within `buildExpectationResult`

Is changed to:
```javascript
function message() {
      if (options.message) {
        return options.message;
      } else if (options.error) {
        return messageFormatter(options.error);
      }
      return '';
    }
```

Then in within `Expectation.prototype.wrapCompare`

```javascript
...
if (!result.pass) {
        if (!result.message) {
          args.unshift(this.isNot);
          args.unshift(name);
          message = this.util.buildFailureMessage.apply(null, args);
        } else {
          if (Object.prototype.toString.apply(result.message) === '[object Function]') {
            message = result.message();
          } else {
            message = result.message;
          }
        }
} else {
         message = "Passed."
}
...
```

Then if we want to we can override `Expectation.prototype.wrapCompare` as protractor already does via jasminewd

In my case I wanted the message for passed and failed so I changed it to either output the normal message or use my custom matcher message, or the since(...) message:

```javascript
...
if (!result.message) {
          args.unshift(this.isNot);
          args.unshift(name);
          message = this.util.buildFailureMessage.apply(null, args);
        } else {
          if (Object.prototype.toString.apply(result.message) === '[object Function]') {
            message = result.message();
          } else {
            message = result.message;
          }
        }
...
```

**Comment by slackersoft** [comment] 2016-10-17 19:11
This sounds like a duplicate of #971. Jasmine doesn't expect you to really print messages for expectations that were met, and in order to reduce confusion by displaying a message that doesn't make sense, we change the message for passed expectations to 'Passed'.

I think @t2n and @faredis may be talking about a different use case of simply allowing more customizability for expectations that fail which is then a duplicate of #641.

Closing. Thanks for using Jasmine!

**Closed by slackersoft** 2016-10-17 19:11 UTC
Labels: feature request
