### ISSUE TITLE
Test freezes when fixture.debugElement.query(By.css(".something")) is checked for null

### ISSUE THREAD

**Issue by egdraper** [jasmine/jasmine#1263] opened 2017-01-23 18:53 UTC
I have a test that checks if a DOM element has been removed by an ngIf. When I grab the DOM element using: fixture.debugElement.query(By.css(".something")) the result is either `null` or a DOM element.

If the result is null, then the following test works fine. But, if the test result contains an element, it doesn't simply fail the test, it freezes up the debug browser.

The test looks like this:

`var result = fixture.debugElement.query(By.css("#something"))`
`expect(result).toBe(null)`  // same goes for .toBeFalsy(), .toEqual(null)

This is not a problem if you use `document.getElementById("something")` to get the element. So the issue seems to be only if you try to check if a `fixture` element is null when it is not.

**Comment by slackersoft** [comment] 2017-01-24 23:06
This sounds like it is probably an issue with Protractor (that's what it looks like you're using), and not Jasmine itself. Jasmine doesn't include any kind of fixture or DOM manipulation functionality, so I'm unsure what might be going on there. Also, if I remember correctly, Protractor also wraps the built-in `expect` that comes with Jasmine so that it will wait for promises to be resolved and make your synchronous looking code actually behave asynchronously.

I'm going to close this, since it doesn't seem like it is a problem with Jasmine itself. Thanks for using Jasmine!

**Closed by slackersoft** 2017-01-24 23:06 UTC

**Comment by SethGunnells** [comment] 2017-03-22 16:53
I looked into this myself as I've just run in to the same problem. It also occurs when checking with `toBeFalsy()`. My exploration showed that the failure occurs when Jasmine attempts to pretty print the `DebugElement` from Angular.

I don't know for sure, but I suspect that `DebugElement` might have circular references in it as this is something I've generally observed with Angular. Is is conceivable that, as Jasmine is attempting to print out, it is getting caught up in the circular reference?

To be specific, stepping over [this line](https://github.com/jasmine/jasmine/blob/master/src/core/PrettyPrinter.js#L50) while debugging freezes up.

**Comment by SethGunnells** [comment] 2017-03-23 17:49
Angular will fix this with this upcoming PR: https://github.com/angular/angular/pull/15074

**Comment by kkajdd** [comment] 2017-11-29 15:29
Hi SethGunnells,
I migrated to angular 5, but still this issue exists

**Comment by prashu2705** [comment] 2018-01-11 02:18
I'm using angular 5.0.0 and met with the same scenario to check whether an element exists or not in my test and used the below and it works fine.
`expect(fixture.debugElement.query(By.css('.cssclass')) === null).toBeTruthy();`

**Comment by sgravrock** [comment] 2018-01-11 02:52
This sounds like it could be a case of Jasmine exhausting memory when trying to pretty-print an object graph that's both deep and wide. We've done some recent work, particularly c0d051319990858de86c46a9697711bf80a2ef7c, to prevent that. If anyone who has this issue is willing and able to run Jasmine from the master branch and let us know if the issue still reproduces, it would be helpful.

**Comment by dwilches** [comment] 2018-02-04 08:31
Posted a workaround that works for me in Angular 4.2.4 here: https://stackoverflow.com/questions/44301315/karma-error-no-captured-browser-open-http-localhost9876/48606192
