### ISSUE TITLE
testFunction in it() should be required

### ISSUE THREAD

**Issue by sefo2810** [jasmine/jasmine#1464] opened 2017-12-15 08:48 UTC
I am wondering, why the parameter testFunction in `it()` is optional, but in the function `fit()` it is not.

**Background:**
I had the following code and was struggling to find the error:
`describe('foo', () => {
  it('bar'),async(inject([BarService], (classUnderTest: BarService)=>{
  //some test code
  }));
});`
This is two expressions ( `it('bar')` AND `async(...)` ) separated by a comma. As `it('bar')` is valid code, the compiler is perfectly fine with it.

At some point i changed to `fit` (to just run this one test) and immediately got an error message, that the testFunction is missing, which helped me to find my mistake.

Is there an use case to call `it()` with just a name. I can not image one.
Therefore I would recommend to keep the signature of both methods the same.

**Comment by tymfear** [comment] 2017-12-15 08:59
@sefo2810 yes, there is a valid case to call it with just a name. When you do so the spec is marked as pending.
This is very helpful when you plan your test suite, and just create pending cases. And after planning you start developing these specs one by one.

**Comment by sgravrock** [comment] 2017-12-17 00:35
The only thing I have to add to @tymfear's explanation is that the signatures differ because it's not useful to focus on a pending test. So `fit` doesn't support the pending form. 

Closing as this is the intended behavior and not something that we're interested in changing.

**Closed by sgravrock** 2017-12-17 00:35 UTC
