### ISSUE TITLE
[toHaveBeenCalledWith] is not freezing the object passed to the function

### ISSUE THREAD

**Issue by viniciusdacal** [jasmine/jasmine#1076] opened 2016-03-18 19:55 UTC
given the example:
```js
spyOn(accountService, 'create').and.callFake(function (account) {
    account.id = 3;
    return q.resolve();
});

accountService.create({name: 'Kakaroto account'});
expect(accountService.create).toHaveBeenCalledWith({name: 'Kakaroto account'});
```
I got the following error:

```bash
Expected spy create to have been called with [ Object({ name: 'Kakaroto account' }) ] but actual calls were [ Object({ name: 'Kakaroto account', id: 3 }) ].
```
I know, it's not a good practice change the same object, this can be easily solved in my side of the code just making a copy of the account object, but the fact is: I called accountService.create with 
`{ name: 'Kakaroto account' }` and the test is saying I didn't.

Probably the code is just saving a reference to the original object.
Is there a way to just take a copy of the object when it's passed to the function?

**Comment by motizuki** [comment] 2016-03-28 10:43
Hello @viniciusdacal,
I believe it's just working as intended.
As parameters of a function in Javascript, objects are passed by 'copy of it's reference', thus any change you perform to the object itself will be effective.

```
function replace(ref) {
    ref = {};           // this code does _not_ affect the object passed
}
function update(ref) {
    ref.key = 'newvalue';  // this code _does_ affect the _contents_ of the object
}
var a = { key: 'value' };
replace(a);  // a still has its original value - it's unmodified
update(a);   // the _contents_ of 'a' are changed
```

**Comment by sgravrock** [comment] 2016-05-07 19:22
Not all objects are trivially copyable, and some aren't copyable at all. Consider an object that's part of a cyclical graph, like a tree whose nodes link to both parents and children. Or an object that references something non-copyable like one of the builtin browser globals. It would be difficult to test code that uses objects like that if toHaveBeenCalledWith tried to copy its argument.

@viniciusdacal, in the example you gave you could just pass the same object reference to both functions:

```javascript
var account = {name: 'Kakaroto account'};
accountService.create(account);
expect(accountService.create).toHaveBeenCalledWith(account);
```

Of course a real test would be more involved than that, and maybe the test can't directly access the object that will be passed to createAccount. In that case you could use the tracking properties of the spy to inspect the argument, like this (untested, beware of errors):

```javascript
triggerAccountCreationSomehow();
expect(accountService.create).toHaveBeenCalled();
expect(accountService.create.calls.argsFor(0)[0].name).toEqual('Kakaroto account')
```

**Comment by viniciusdacal** [comment] 2016-05-10 01:06
Indeed, thanks for the help @motizuki @sgravrock 
So, I think we can close this issue.

**Comment by slackersoft** [comment] 2016-09-26 23:57
This looks to also be a duplicate of #444. Closing.

**Closed by slackersoft** 2016-09-26 23:57 UTC
