### ISSUE TITLE
Calling expect() when no spec is running doesn't generate any visible errors

### ISSUE THREAD

**Issue by sgravrock** [jasmine/jasmine#781] opened 2015-02-17 01:08 UTC
The following code causes Jasmine to throw "'expect' was used when there was no current spec, this could be because an asynchronous test timed out". But the suite passes and the error doesn't appear to be logged anywhere:

```javascript
describe("Specs that try to expect things after they're done", function() {
	it("should cause something to go red", function (done) {
		done();
		expect(true).toBe(false);
	});
});
```

(Tested on 2.0.2 with the HTML reporter and 2.2.0 with both the HTML reporter and the stock node.js setup.)

Obviously that's a contrived example. But it corresponds to an async testing mistake that I’ve run into a number of times: writing test code that expects something to be async even though all of the async pieces have been replaced with synchronous mocks. It would be a big help if that error caused the suite to fail, even if Jasmine couldn’t pin the failure on the specific spec that caused it.

**Comment by slackersoft** [comment] 2015-02-17 06:13
As of 2.1 with the changes that were made to support `afterAll`, I think this should only be possible for specs at or near the end of your suite, where the `QueueRunner` wouldn't clear stack before you called done and the full suite finished before you managed to call `expect`. That said, it probably makes sense  now to just tell the `topSuite` about the expectation failure and let that cause the suite to fail.

I'd be happy to review a pull request that solves this problem.

**Comment by sgravrock** [comment] 2015-02-23 07:11
2.2.0 correctly associates the failure with the spec that causes it, which gets us at least halfway to a solution. But the spec still appears to pass in most cases because the failure occurs after the reporters' specDone methods are called. I can fix that by modifying QueueRunner to not move onto the next spec until an async spec both returns and calls its done callback. However, that breaks the behavior described in #790 , so I think I'd better hold off on this issue until we figure out what to do about that one.

**Comment by slackersoft** [comment] 2015-03-02 06:10
When you have an async spec, jasmine assumes you know what you're doing and that when you call `done` you are in fact done with that portion of your spec (see our resposes in #709 & #743).

However, I'd be happy to review a pull request that made sure to associate any expectation failures outside of any suite with the topSuite. This should make sure that the suite at least fails in this situation.

**Comment by marshmellow1328** [comment] 2015-06-23 02:21
Is this sitting waiting for someone to implement a solution?

**Comment by slackersoft** [comment] 2015-07-02 21:49
@marshmellow1328 that is correct.

**Comment by slackersoft** [comment] 2016-10-15 00:45
It sounds like this has become a duplicate of #529 in handling global errors for specs (async and otherwise). Closing in favor of the more general issue.

**Closed by slackersoft** 2016-10-15 00:45 UTC
Labels: feature request, ready for work
