### ISSUE TITLE
error  ".spies undefined" after all specs run as of v.2.5.x

### ISSUE THREAD

**Issue by wardbell** [jasmine/jasmine#1231] opened 2016-10-30 06:20 UTC
Somewhere around `jasmine.js` v.2.5.x the spy clearing logic changed and I started getting 
the error: `TypeError: Cannot read property 'spies' of undefined` in the console.

The visible symptom is that the browser testrunner output is empty.

All tests have run. This error happens during the final cleanup.

Everything worked fine as recently as v.2.4.1 before some kind of change to the cleanup involving spies.

See the errant behavior in this trivial plunker: http://plnkr.co/edit/qixgrpWpf6mgbIfn29zc?p=preview from the Angular 2 docs (I'm the author of the Angular 2 testing chapter).

During the final cleanup, when the `id` is "suite0", the error is thrown in ...

```
    var spyRegistry = new j$.SpyRegistry({currentSpies: function() {
      if(!currentRunnable()) {
        throw new Error('Spies must be created in a before function or a spec');
      }
      return runnableResources[currentRunnable().id].spies; // <-- THROWS HERE
    }});
```

... because the value of `runnableResources` is the empty object `{}`. 

The following hack gets around the bug:

```
    var spyRegistry = new j$.SpyRegistry({currentSpies: function() {
      if(!currentRunnable()) {
        throw new Error('Spies must be created in a before function or a spec');
      }
      if (runnableResources[currentRunnable().id]) {
        return runnableResources[currentRunnable().id].spies;
      }
      return [];
    }});
```

**Comment by slackersoft** [comment] 2016-11-04 18:49
There is quite a bit of code in the example you've provided, including some patching of core Jasmine functionality. Given that we're not seeing this in Jasmine's own tests or hearing about it from other sources, I'm inclined to say that the issue is arising because of the custom patches to Jasmine that you are using. If you can provide a simpler example without the patching that still causes the error, that would be helpful in diagnosing this issue. At this point, my best guess is that something in the patches is causing the completion callback for the `TreeProcessor` (https://github.com/jasmine/jasmine/blob/master/src/core/Env.js#L254) to be called more than once, and the second time everything has already been cleaned for the top suite.

If you need to wait to `execute` your Jasmine environment, like in the `browser-test-shim.js` when `window.onload()` is called, you should make sure that that `onload` is _not_ getting called when the window loads.

**Comment by mgwhitfield** [comment] 2016-11-30 04:28
Reproduced this behavior via #1237

**Comment by slackersoft** [comment] 2016-12-01 00:50
See [my comment](https://github.com/jasmine/jasmine/issues/1237#issuecomment-264044881) on #1237, multiple `execute` calls on the same `Env` isn't really supported by Jasmine.

If this is happening during a single run and we can narrow it down to something that Jasmine is doing, we would be happy to get that fixed.

**Comment by eplatzek** [comment] 2017-01-10 21:12
+1: Our project started throwing this error when we upgrade from 2.4.1 to 2.5.2. 
If we run jasmine and remove all the test cases, it still throws the same error.

**Comment by slackersoft** [comment] 2017-02-16 00:55
I still haven't seen an example that fails with _just_ Jasmine and not other patching going on. This makes it very hard to nail down to something that Jasmine itself is doing to cause this. If anyone can give me a sample that doesn't include patching Jasmine or running the same suite twice, I'd be happy to help figure out what is going on.

**Comment by GZidar** [comment] 2017-03-14 02:20
I have encountered this error with jasmine v2.5.2 in conjunction with zone.js v0.7.2 & v0.8.1 patching. The issue may not be in the jasmine code at all but reverting to 2.4.1 does fix it so perhaps some analysis of what changed with regards to cleanup of spies between those two versions might be helpful to track down why the zone.js patch is causing this to fail.

**Comment by slackersoft** [comment] 2017-03-15 00:35
The primary change for spy cleanup in 2.5.0 was allowing the global `beforeAll` and `afterAll` to have spies and expectations #811. Doing this means that Jasmine now has to track those things at the topLevel suite (this is the hidden parent `describe` of all of the `describes` in your suite). These should be tracked in the same way as in any of the child suite, so if zone.js (and the associated patching) is doing something to Jasmine that breaks this, the patches and such probably need to change.

**Comment by RonNewcomb** [comment] 2017-05-25 00:37
I am also having this issue, using a SpecRunner.html file and spec files which are wrapped by SystemJS.  I haven't changed jasmine-core for this, but reverting to 2.4.1 made the error go away. 

Granted, I still get "no specs found".

**Comment by GZidar** [comment] 2017-05-25 04:26
Hi @RonNewcomb, the issue (for me at least) isn't with Jasmine it was the combination of Jasmine and Zone.js if you have a look at this link (https://github.com/angular/zone.js/issues/679) you will find a workaround to the problem so you can use the newest Jasmine with the zone.js

**Comment by RonNewcomb** [comment] 2017-05-25 17:03
I am indeed using zone.js; thanks for the tip @GZidar !

**Comment by slackersoft** [comment] 2017-06-16 21:11
It sounds like this issue is primarily arising because of patching that zone.js is doing to Jasmine and it potentially not matching up with the current version of Jasmine. I'm going to close this issue, but if we can identify a reproduction case that only uses Jasmine, I'd be happy to work on a fix.

Thanks for using Jasmine!

**Closed by slackersoft** 2017-06-16 21:11 UTC

**Comment by bisubus** [comment] 2017-09-13 16:16
@slackersoft The error is still applicable in pure SystemJS setup, with no Zone.js. See http://plnkr.co/edit/oJq4W8WnW3EpkWu2ysKN

**Comment by slackersoft** [comment] 2017-11-15 05:23
@bisubus It looks like the bootstrapping code you have there is just re-executing the `window.onload` handler that Jasmine installs in `boot.js` which is causing the Jasmine Suite to be executed twice. Once without any specs, and once again after all the specs have been loaded. Because a Jasmine `Env` doesn't really expect to be `execute`d more than once, it looks like there is some cleanup/setup that is only done during creation of the full Environment that causes this error when run a second time. If you need to cause Jasmine to delay executing your specs for some time after page load, you should also _remove_ the `window.onload` handler that Jasmine installs (or build your own [custom boot](https://jasmine.github.io/edge/custom_boot.html) that sets up when you really need the `execute` call to be made).

Hope this helps. Thanks for using Jasmine!

**Comment by bisubus** [comment] 2017-11-15 05:59
@slackersoft Thanks, I see what you mean by *executed twice*. I've tried to remove window.onload, but it seems [it doesn't help](http://plnkr.co/edit/9dyQuDqITUbCpxpPuskB?p=preview). Yes, custom boot is an option but copying and pasting a considerable part of the library without changes doesn't look very good.

**Comment by slackersoft** [comment] 2017-11-17 05:13
@bisubus looks like `delete` doesn't do the job in this case. I tried `window.onload = function() {};` and it looks like it works correctly.

Hope this helps. Thanks for using Jasmine!

**Comment by cbuteau** [comment] 2018-03-19 01:10
What is the actual workaround?
I need more information spelled out to me.
I originally launched my package with testem/jasmine and am trying to migrate my tests and infrastructure to karma/jasmine and this bug is in the way.

**Comment by slackersoft** [comment] 2018-03-22 00:37
@cbuteau the workaround mentioned above has to do with using Zone.js with Jasmine. You should take a look at the Zone.js issue referenced above and ask in that forum, since the patching happening there seems to be causing the issue and not Jasmine itself.

Hope this helps. Thanks for using Jasmine!

**Comment by cbuteau** [comment] 2018-03-25 00:45
I am not using Zone.js I am just migrating to karma/jasmine and I keep getting this error.

**Comment by slackersoft** [comment] 2018-03-28 00:18
@cbuteau please create a new issue with a stripped down example that exhibits the problem. The error shown in this issue was related to Zone.js (as a dependency of Angular) and how it was patching into Jasmine.

Hope this helps. Thanks for using Jasmine!
