### ISSUE TITLE
Error: <spyOn> : openSnackbar is not declared writable or has no setter while spyOn import a method in Angular 12 (Jasmin)

### ISSUE THREAD

**Issue by Chirlancharamana** [jasmine/jasmine#1942] opened 2021-11-11 16:13 UTC
I'm trying to spy a method which has been imported in my component. but getting the below error when we run the Test cases.

>      Error: <spyOn> : openSnackbar is not declared writable or has no setter

Also tried spyOnProperty() method but got the below error:

>      <spyOnProperty> : default is not declared configurable

`import * as snackbar from '@xyz/util'; `
`let openSnackSpy: jasmine.Spy;`

Spied in Jasmin like below

`openSnackSpy = jasmine.createSpy('openSnackbar');`
`spyOn(snackbar, 'openSnackbar').and.callFake(openSnackSpy);`

Expecting openSnackSpy to be called once.

`expect(openSnackSpy).toHaveBeenCalledTimes(1);`

tsconfig.json
`"compilerOptions": {`
`     "module": "es2020", // Do not want to use "commonjs"`
`  },`

**Comment by sgravrock** [comment] 2021-11-11 16:40
You aren't able to spy on module exports because the build tools that you're using have made them immutable. Please see [the relevant FAQ entry](https://jasmine.github.io/pages/faq.html#module-spy) for more information and some things you can do.

Closing as a duplicate of #1414.

**Closed by sgravrock** 2021-11-11 16:40 UTC
