### ISSUE TITLE
"Stop execution on spec failure" does not work

### ISSUE THREAD

**Issue by maximedupre** [jasmine/jasmine#1576] opened 2018-07-07 20:52 UTC
## Expected Behavior

"Stop execution on spec failure" does not work

## Current Behavior

The specs keep executing even if a previous spec has failed.

## Your Environment

* Jasmine core : `v3.1.0`
* Chrome 67
* Operating System and version (desktop or mobile): OSX 10.13.5

**Comment by slackersoft** [comment] 2018-07-20 00:54
It looks like it's working in my environment. Can you give me a bit more information about how you're running your specs and maybe an example suite that reproduces the error to help with troubleshooting?

Thanks

**Comment by maximedupre** [comment] 2018-08-18 15:30
It seems to stop the execution, but only for the current describe. Shouldn't it bail for the whole test suite?

**Comment by slackersoft** [comment] 2018-08-22 00:37
Do you have an example suite that demonstrates the error? This is what I'm seeing when I check the "stop execution on spec failure" checkbox.

<img width="491" alt="screen shot 2018-08-21 at 5 35 58 pm" src="https://user-images.githubusercontent.com/512724/44436200-be23d000-a568-11e8-871e-a3788c304c42.png">

**Comment by maximedupre** [comment] 2018-08-31 14:26
Please clone https://github.com/maximedupre/jasmineIssue1576, change directory to the repo and run `npm test`

As you can see in the screenshot, there is an error in `describe('1', ...`, but `describe('2'...` is still executed. The execution is stopped only the describe context, not for the whole suite.

![screen shot 2018-08-31 at 10 22 46 am](https://user-images.githubusercontent.com/5158181/44918199-60ca1480-ad08-11e8-87e9-f8eb5fc7e436.png)

**Comment by johnjbarton** [comment] 2018-12-21 16:41
Almost certainly a karma-jasmine issue, fixed in v2.x

**Comment by maximedupre** [comment] 2018-12-24 17:59
I'm using `"karma-jasmine": "2.0.1"` and it has not been fixed.

**Comment by slackersoft** [comment] 2019-01-23 01:48
It looks like this is an issue with Karma-Jasmine and not Jasmine itself. Closing this.

If you're still seeing the issue, I'm sure the Karma-Jasmine team would appreciate a reproduction case to help them resolve the issues.

**Closed by slackersoft** 2019-01-23 01:48 UTC
Labels: Karma
