### ISSUE TITLE
beforeAll(async () => { throw new Error() }) does not stop test execution

### ISSUE THREAD

**Issue by conartist6** [jasmine/jasmine#1827] opened 2020-06-12 22:39 UTC
This obfuscates the real location where the failure occurs.

**Comment by sgravrock** [comment] 2020-06-25 01:05
This looks like a duplicate of #1533, which is an open issue that we'd be happy to get a PR for. Closing in favor of the existing issue.

**Closed by sgravrock** 2020-06-25 01:05 UTC
