### ISSUE TITLE
Feature Request: Sourcemap support

### ISSUE THREAD

**Issue by nicosommi** [jasmine/jasmine#491] opened 2014-01-02 18:26 UTC
It would be nice if the original line number of the error is displayed when developing in coffeescript.

For example for this error:
TypeError: entityCollection.get(...) is undefined in http://somehost:[someport]/somepath/SomeSpec.js (line 37)

It can be something like this (reading the sourcemap):
TypeError: entityCollection.get(...) is undefined in http://somehost:[someport]/somepath/Spec.coffee (line 15) (and line 37 on /somepath/SomeSpec.js)

I think this can be done reading the //@sourceMappingURL or the //#sourceMappingURL attribute of the compiled js and later the sourcemap itself (using the value of that attribute), then there is the sourcemap interpretation using https://github.com/mozilla/source-map

**Comment by alexeagle** [comment] 2015-04-24 21:01
+1 this would be useful for running unit tests written in Typescript

**Comment by caseyhoward** [comment] 2015-06-12 16:44
:+1: I compile all my tests beforehand using typescript. Source map support would be really nice. I hate digging through the generated file.

**Comment by geddski** [comment] 2015-08-01 20:10
+1 as someone using webpack, I have no idea where the actual errors are without source map support.

**Comment by geddski** [comment] 2015-08-01 20:25
For anyone else needing this, I've found that adding `?catch=false` to the URL at least lets the errors make it to the console so the browser can use source maps to show you where the errors are.

**Comment by cmdelatorre** [comment] 2015-10-28 14:50
+1 to support tests in coffeescript
In the meanwhile, @novocaine , do you have some tips on how to integrate your module in my project without patching Jasmine?

**Comment by novocaine** [comment] 2015-10-28 16:08
sorry, you definitely have to patch Jasmine..

**Comment by inf3rno** [comment] 2015-11-02 20:42
@geddski I tried out, but it does not work, because the error was rethrown by jasmine, so it points to the code of jasmine instead of my source code. (Btw. did anybody manage to use sourcemaps in firefox and chrome. I got proper support only in opera and msie.)

If somebody needs this feature, it works with karma + browserify + jasmine (tested with phantomjs). Here is a project template: https://github.com/inf3rno/javascript-project-template

**Comment by guncha** [comment] 2015-12-10 20:12
If anyone else is looking for a quick hack to get the source mapped stack traces working with Jasmine's HTML reporter while this is being figured out, here's a gist for you: https://gist.github.com/guncha/f45ceef6d483c384290a

**Comment by DanielSchuech** [comment] 2016-01-21 09:14
thx @guncha 

I am using it with karma jasmine html reporter and its working well! I haven't found another solution so I just can recommand that atm.

**Comment by guncha** [comment] 2016-01-21 15:58
I actually ended up using https://github.com/evanw/node-source-map-support which overwrites the native `Error#stack` to fetch the source maps and rewrite the stacktrace. It works with Jasmine as well as errors in the console. The only issue with testing is that is uses AJAX, so if you use `jasmine-ajax`, it will break in strange ways.

**Comment by ArnaudRinquin** [comment] 2016-02-03 22:34
@guncha Thanks for the gist, I hacked it a little to make it work but that'll do for now. Do you know if there is a way to restore the stack traces before they get sent to karma/testem/initial loader?

**Comment by geddski** [comment] 2016-02-04 05:59
This issue still makes using jasmine such a major pain when using something like webpack. Not knowing what line errors are coming from makes things impossible.

**Comment by andyl** [comment] 2016-02-04 23:11
Is there a different JavaScript test runner that handles sourcemaps??

**Comment by slackersoft** [comment] 2016-02-23 21:55
As @infews [mentioned](https://github.com/jasmine/jasmine/issues/491#issuecomment-53599970), we'd be happy to review a pull request that either:

* Allows injection of an ExceptionFormatter, allowing a custom one that can deal with sourcemaps
* Allows injection of some sort of filtering/rewriting function that the existing ExceptionReporter can use to accomplish this

This would also allow for a better solution to #801 and filtering lines out of the stacktrace of an error.

**Comment by rdy** [comment] 2016-04-06 14:45
We have added very preliminary support for this similar to the way that has been described for gulp-jasmine-browser, it is currently only supported in the browser stacktrace, I haven't yet re-worked the headless reporter to support this correctly. You can check that out here: 
https://github.com/jasmine/gulp-jasmine-browser

Make sure you use the `{sourcemappedStacktrace: true}` as the option to the spec runner.

From this early experimentation we would need to add some kind of asynchronous formatter since the loading of the source maps is not instantaneous.

Would we be open to adopting the use of promises in Jasmine? This would make it a lot easier to handle these kinds of real asynchronous things. I've already made some other modifications for async style tests which I'd be happy to share.

**Comment by andreisoare** [comment] 2016-06-30 00:55
How about just implementing this for inline source maps? Surely a development setup can configure source maps to be inline and this way you don't need to make any async calls to grab the source maps.

**Comment by guncha** [comment] 2016-06-30 15:00
As far as I know there's no way to access the inlined source map except by doing an XHR request for the file and parsing it manually.

**Comment by daryllabar** [comment] 2017-02-03 16:03
Any update on this? It's been 6 months...

**Comment by steven-solomon** [comment] 2017-05-08 18:36
This would be very beneficial.

**Comment by taavo** [comment] 2017-05-11 21:18
Mostly redundant with prior discussion, but since nobody's talked about this for a while:

- If we don't want to introduce sourcemap concerns into the core codebase we can make the `ExceptionFormatter` injectable via `Env`. Extract it to a field on the `options` parameter, done. (Then presumably someone would write an `ExceptionFormatter#stack` that handles sourcemaps using one of many existing libraries.)
- That, however, isn't that useful since any sourcemap processing you do will occur asynchronously. `ExceptionFormatter#stack` needs therefore to take a callback or return a promise.
- If `ExceptionFormatter#stack` is asynchronous, either a whole lot of things calling it (and things that call those things) need to be asynchronous, or `Spec#addExpectationResult` and `Suite#addExpectationResult` add results to `result.failedExpectations` in a non-deterministic order when sourcemaps are enabled.

Any thoughts or advice, @slackersoft?

(ps. for people running into this thread: if you're using karma-jasmine with karma-webpack you should be able to get sourcemapped stacktraces out of the box. I imagine you can do the same thing with typescript as well.)

**Comment by johngrogg** [comment] 2017-11-21 01:22
I'd also like an update on this feature. We're wanting to switch our server-side node tests to use jasmine like our Angular apps, but since we use TypeScript server-side it makes it hard to quickly identify where in a spec file the error/assertion failure actually occurred.

**Comment by rdy** [comment] 2017-11-22 02:46
It might be possible to make this work using Babel as part of your toolchain, I may do some investigation into this, for those relying on typescript you would probably need to be using that toolchain with the new babel7.

**Comment by leonadler** [comment] 2017-11-22 10:10
@johngrogg for node, take a look at [source-map-support](https://github.com/evanw/node-source-map-support#readme)

**Comment by rdy** [comment] 2017-11-22 16:17
@johngrogg I was able to get inline-source-maps working correctly with jasmine but I used a babel plugin to inject the source-maps for my tests.
https://www.npmjs.com/package/babel-plugin-stack-trace-sourcemap

It works the same way as described by @leonadler under the hood and even works with browser based source maps. I have mine working with `devTool: 'cheap-inline-source-map'` in webpack. Seems to be the best solution though it the source map support only works in chrome and node.

**Comment by cancerberoSgx** [comment] 2018-04-13 13:41
found this one for typescript, seems to obe working just fine and easy to install: https://github.com/SeanSobey/JasmineTSConsoleReporter

**Comment by klemenoslaj** [comment] 2018-10-18 11:01
I think that the easiest solution is the following:

- install `source-map-support` with npm or yarn.
- add/modify test script in package.json
```
"test": "NODE_OPTIONS='-r source-map-support/register' jasmine ./src/**/*.spec.js",
```

**Comment by DamienCassou** [comment] 2018-10-19 07:02
@klemenoslaj said:
> I think that the easiest solution is the following:
>     * install `source-map-support` with npm or yarn.

that doesn't work for me. I guess it's because Jasmine already does something with source-map (#1598).

**Comment by slackersoft** [comment] 2018-10-19 23:20
Jasmine itself definitely doesn't know anything about sourcemaps. If there is another library included that is patching the `Error` prototype to provide a sourcemapped stacktrace, then Jasmine will end up using that.

**Comment by cancerberoSgx** [comment] 2018-10-24 22:43
Just in case, for those using typescript, in node.js, what I do is execute typescript directly with (npm install) ts-node, basically just change all `*.js` with `*.ts` in your spec/support/jasine.json file and then run `npx ts-node node_modules/jasmine/bin/jasmine.js `. For actually debugging (like putting a breakpoint) it in node.js you will need to compile TS with sourcemap: true in tsconfig.json and that works fine though

**Comment by sgravrock** [comment] 2019-08-17 16:57
I'd like to get a sense of whether there is still a need for Jasmine to do anything with source maps in 2019, and if so how widespread it is. Jasmine has produced correct stack traces for TypeScript and Flow for at least a couple of years now, thanks to the sourcemap support that's built into those languages' toolchains. I suspect that the same is true for other languages that compile to JS.

If anyone still has this problem today despite using the latest version of their language's build system and (if necessary) turning on source maps in their language's configuration, I'd love to hear specifics.

**Comment by MarcusRiemer** [comment] 2019-08-18 18:25
I am not sure whether this exactly fits this issue, but I am always frustrated by only partially helpful stacktraces of stacks in the `debug.html`-runner. I have an Angular (Typescript) application and get stacktrace entries like this:

```
<Jasmine>
./src/app/shared/multilingual-input.spec.ts/</</<@http://0.0.0.0:9876/_karma_webpack_/main.js:5309:61
```
The mentioned file is correct, but sadly there is no class name, method name or line number. I am not 100% certain that this would be solved via sourcemaps, but if this would be the case I would be more then glad for a fix.

**Comment by DamienCassou** [comment] 2019-08-19 11:59
@sgravrock Please read https://github.com/jasmine/jasmine/issues/1598#issuecomment-522538164 which contains an up-to-date way to reproduce a problem with stacktraces in Jasmine.

**Comment by sgravrock** [comment] 2019-08-21 04:00
Thanks. This helps. I played with the repro from @DamienCassou a bit and tried a few different source map configurations with a few different browsers. None of them resulted in `Error` objects with a correct `stack` property, which is what Jasmine uses to figure out where expectation failures come from. So it looks like while Node might be pretty well supported today, browsers aren't. 

So I think there's a good case to be made for Jasmine to apply source maps to stack traces, especially since they're already processed to filter out Jasmine's own frames. But the prospect of changing all the code paths that touch stack traces to be async doesn't exactly fill my heart with joy. Maybe the source maps could be preloaded prior to the call to `Env#execute` and then processed synchronously when errors occur.

**Comment by sgravrock** [comment] 2019-12-19 03:37
A while ago, I finally had a chance to spend a solid block of focused time looking into this. I was able to get source mapped stack traces working in modern browsers using [`source-map`](https://github.com/mozilla/source-map) without too much effort. See [this spike](https://github.com/jasmine/jasmine/compare/source-map-via-script-tag-spike) for details (but keep in mind that it's not production-ready or architecturally anything like what I'd want to end up with).

IE is another matter entirely. I wasn't able to find a way to compile `source-map` to something that runs in IE without introducing polyfills in the process. That's something that we'd really like to avoid, since it can create a situation where tests pass because of the polyfills and the code under test fails when run outside of Jasmine.

It would be great if somebody who's better than I am with Webpack and Babel could come up with a solution. Alternately, I think it would be OK to let users bring their own build of `source-map` and have Jasmine use it if it's present. That would let uses make an informed choice about introducing polyfills and might open up some possibilities for frameworks like Angular that can make different assumptions about the environment they run in.

I can't rule out the possibility that I might give this another try in the future, but it's not anywhere near the top of my personal to-do list. If someone wants to step up and make a major contribution, this would be a great place to do it. I'd be happy to offer context & advice, review PRs, or provide other support.

**Comment by elliot-nelson** [comment] 2020-10-01 13:22
After playing around with `jasmine` and `nyc` options, I was surprised to see how hard it was to get this working with a very basic setup, no webpack, babel, typescript or browsers involved.

My setup is: install `jasmine` and `nyc` in a local node project, have a failing test case.  I'd like the `line:column` output to read `67:8` but instead it reads `10:35803`.  Does anyone know if there's a node module I can plug in that would fix this scenario?

**Comment by JannesMeyer** [comment] 2020-11-02 05:46
Node.js actually has (experimental) source map support since v12. It can be enabled with the [`--enable-source-maps`](https://nodejs.org/dist/latest/docs/api/cli.html#cli_enable_source_maps) flag. No additional dependencies required.

Unfortunately, it looks like Jasmine is swallowing the extra information in the stack trace that Node.js provides because it ignores stack frames where the `file` property is `undefined`. Presumably this happens in an attempt to filter out stack frames that are about Jasmine internals.

After testing with some compiled TypeScript I get an additional stack frame that contains an arrow and the original file name in the `raw` field:

```
{
  raw: '        -> C:\\testing\\test.ts:15:40'
}
```

However, this doesn't have a `file` property so it gets filtered out. The original JavaScript frame right above it has a bit more information (`file` property is populated):

```
{
  raw: '    at UserContext.mapGet (file:///C:/testing/test.js:12:43)',
  file: 'file:///C:/testing/test.js',
  line: 12,
  func: 'UserContext.test'
}
```

I think I found the code that accidentally filters the source-mapped frames:

https://github.com/jasmine/jasmine/blob/b1bcd6e82537ff1849e2d95afa5480101bc85282/lib/jasmine-core/jasmine.js#L3562

**Comment by elliot-nelson** [comment] 2020-11-02 12:37
Having it built-in would be very cool.  The example you provided almost makes me think this is a bug in node and not Jasmine, though... the frame is clearly in a file, and it knows which file it is, so why wouldn't the file properly be set?

(I'm not sure which frames are being filtered out by the undefined check, but in browsers I'd be worried that removing that check could surface a lot of useless per-browser core functions that Jasmine is intentionally hiding.)

**Comment by JannesMeyer** [comment] 2020-11-02 19:58
I have just submitted a pull request that would show a lot of extra information on the stack trace (including source map support). You can see the before and after in my description in https://github.com/jasmine/jasmine/pull/1862.

@elliot-nelson I don't think I would call it a bug in Node or V8, because there is no standardised way of doing stack traces. Many JavaScript engines don't even come close to the [amount of detail](https://v8.dev/docs/stack-trace-api) that V8 provides. I think other engines merely provide a big string object.

Keep in mind that Jasmine can be run in the browser, which means it has to deal with other JS engines, too.

**Comment by sgravrock** [comment] 2020-11-28 17:30
Reopening. I'd never intended to close this. The above-linked PR helps with source maps on Node but doesn't change anything in browsers.

**Comment by sgravrock** [comment] 2024-07-18 00:36
It's been almost four years since we've heard anything on this issue. In that time I've worked on multiple projects that used Jasmine to run TypeScript code, both in Node and in the browser, and they all had properly source-mapped stack traces. The old reproductions that folks have posted here no longer work with current Node and browser versions. 

As far as I can tell, this is largely fixed through a combination of efforts by folks in this thread and improvements to the surrounding ecosystem. I'm closing this since it doesn't look like there's still anything to solve here. I'm willing to revisit that if somebody can show how to reproduce the problem with current tools.

**Closed by sgravrock** 2024-07-18 00:36 UTC
Labels: feature request, help needed
