### ISSUE TITLE
"TypeError: this.expectationResultFactory is not a function" unable to force specs

### ISSUE THREAD

**Issue by seanhelvey** [jasmine/jasmine#1156] opened 2016-07-19 17:43 UTC
I'm currently unable to force specs without receiving the error `TypeError: this.expectationResultFactory is not a function`. I'm running protractor e2e tests using Jasmine 2.3.4.

Here is a stack trace:

```
/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2219
      this.result.failedExpectations.push(this.expectationResultFactory(data);
Suite.onException /node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2219:48
at QueueRunner.queueRunnerFactory.onException /node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2330:28
at onException /jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1924:12
at [object Object]._onTimeout /jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1910:11
at Timer.listOnTimeout (timers.js:92:15) /jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1910:11
```

Please let me know what info would be helpful. Note that I do not have a beforeEach in an it block, as described in issue https://github.com/jasmine/jasmine/issues/1147.

**Comment by slackersoft** [comment] 2016-09-07 23:05
This sounds like it is probably a duplicate of #811 which should be fixed in the 2.5.x releases. Can you take a look at the new version and see if it fixes your issue?

Thanks for using Jasmine!

**Closed** 2016-12-02 18:37 UTC
