### ISSUE TITLE
Karma clock test pollution

### ISSUE THREAD

**Issue by ccorcos** [jasmine/jasmine#985] opened 2015-12-02 22:30 UTC
This is similar to a previous issue:
https://github.com/jasmine/jasmine/issues/790

But it seems to be a little more nuanced. I believe the previous issue was solved because the following does work:

```js
  describe("clock pollution", function() {
    it("async with clock", function(done) {
      jasmine.clock().install()
      setTimeout(function() {
        jasmine.clock().uninstall()
        done()
      }, 2000)
      jasmine.clock().tick(2001)
    })
    
    it("async with clock", function(done) {
      jasmine.clock().install()
      setTimeout(function() {
        jasmine.clock().uninstall()
        done()
      }, 2000)
      jasmine.clock().tick(2001)
    })
  })
```

But check out the following example when I use promises. I'm using the popular [`Q`](https://github.com/kriskowal/q) library:

```js
  describe("clock pollution", function() {
    it("async with clock", function(done) {
      jasmine.clock().install()
      Q.delay(2000)
        .then(function() {
          jasmine.clock().uninstall()
          done()
        })
      jasmine.clock().tick(2001)
    })
    
    it("async with clock", function(done) {
      jasmine.clock().install()
      Q.delay(2000)
        .then(function() {
          jasmine.clock().uninstall()
          done()
        })
      jasmine.clock().tick(2001)
    })
  })
```

I get this weird error:

```
    clock pollution
      ✓ async with clock
      ✗ async with clock
	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

The clocks definitely seem to be polluting each other somehow.

Just for sanity, I tried this one:

```js
  function delay(ms) {
    return new Promise(function(resolve, reject) {
      setTimeout(resolve, ms)
    })
  }

  describe("clock pollution", function() {
    it("async with clock", function(done) {
      jasmine.clock().install()
      delay(2000)
        .then(function() {
          jasmine.clock().uninstall()
          done()
        })
      jasmine.clock().tick(2001)
    })
    
    it("async with clock", function(done) {
      jasmine.clock().install()
      delay(2000)
        .then(function() {
          jasmine.clock().uninstall()
          done()
        })
      jasmine.clock().tick(2001)
    })
  })
```

And it worked! Argh!! Wtf?!

**Comment by ccorcos** [comment] 2015-12-02 22:49
Well apparently I didnt know how `Q.delay` works.

https://github.com/kriskowal/q/blob/v1/q.js#L1849

Still not working though:

```js
  describe("clock pollution", function() {
    it("async with clock", function(done) {
      jasmine.clock().install()
      Q.delay({}, 2000)
        .then(function() {
          jasmine.clock().uninstall()
          done()
        })
      jasmine.clock().tick(2001)
    })
    
    it("async with clock", function(done) {
      jasmine.clock().install()
      Q.delay({}, 2000)
        .then(function() {
          jasmine.clock().uninstall()
          done()
        })
      jasmine.clock().tick(2001)
    })
  })
```

**Comment by slackersoft** [comment] 2015-12-02 23:06
Given that it is working with just `setTimeout` and es6 Promises, it sounds like it's an issue with how Q is going about resolving the promises when using `delay`, and not jasmine's clock itself. If you find something that we could change in jasmine to make this work, I'd be happy to review a pull request.

**Comment by ccorcos** [comment] 2015-12-03 00:06
I have an example coming up

**Comment by ccorcos** [comment] 2015-12-03 00:09
@slackersoft I created a repo demonstrating this issue:

https://github.com/ccorcos/jasmine-promise-issue

I'm not using Q and only using promises. You'll see that the test pass individually, but fail when they're run together -- I'm assuming this is due to some pollution of the clocks.

**Comment by sgravrock** [comment] 2015-12-03 06:44
@ccorcos The problem with calling done synchronously from within a Q promise callback is that it causes the next unit test to run from inside the current iteration of Q's global flush loop. In effect, all of that loop's state is leaked from one test to the next. I don't completely understand why that breaks the tests in your example but I've seen it cause a lot of other problems. Not least of which is that Q's .then() and related methods behave differently if the flush loop is running when they're called.

I suggest never calling done directly from a Q promise callback. Always wrap it in a setTimeout, and you'll save yourself all kinds of trouble.

I haven't had a chance to give the tests at https://github.com/ccorcos/jasmine-promise-issue more than a brief glance but it looks like they're doing a lot more than the Q tests are. Are you sure none of the tests manipulate the clock (or do anything else interesting) after calling done?

**Comment by ccorcos** [comment] 2015-12-03 21:03
In the example I gave, I'm not using Q at all, so I had to add a couple helpers myself. Its as minimal a reproduction I could come up with. I couldnt reproduce the issue with simpler example. The example I gave consists of running a fetch (returning a promise), and then retrying if that request times out. Its pretty simple. But I think recusively using promises is causing some issues...

**Comment by slackersoft** [comment] 2015-12-09 23:11
I'm not able to reproduce the issue with the code you've provided. The spec you have that retries always fails because the `Promise` calls its callbacks asynchronously so it hasn't actually made the second `window.fetch` call at the point where it is expected.

After debugging a similar issue in jasmine's own tests, it looks to me like this is related to having specs that think they are (or might be) async, but actually execute synchronously. This is similar to what @sgravrock was mentioning, but isn't necessarily due only to `Q`.

**Comment by iKBAHT** [comment] 2016-02-02 14:06
I have the same problem, but with [es6-promise](https://github.com/jakearchibald/es6-promise) polyfill library. I found that problem appear because jasmine done function call from .then function, and it run next test case, while library doesn't clean up it stack.
I think it's jasmine problem. To fix it jasmine must run next test case asynchronously.
Temporary fix look like this:
```javascript
describe('test', function () {
	var myPromiseFunction;
	var _resolve;
	var _reject;

	beforeEach(function () {
	  jasmine.clock().install();
	  myPromiseFunction = () => {
	  	return new Promise((resolve, reject) => {
	      _resolve = resolve;
	      _reject = reject;
	    });
	  }
	});

	it('1', function(done) {
	  myPromiseFunction().then(() => {
	    // expects
	    jasmine.clock().uninstall();
	    setTimeout(done, 1);
	  });
	  runAllPromises();
	  _resolve({
	     // data
	  });
	  jasmine.clock().tick(1);
	});

	it('2', function (done) {
	  myPromiseFunction().then(() => {
	    // expects
	    jasmine.clock().uninstall();
	    setTimeout(done, 1);
	  });
	  runAllPromises();
	  _reject({
	     // data
	  });
	  jasmine.clock().tick(1);
	});
});
```
Idea is to call done in setTimeout, as said @slackersoft , but before need to uninstall jasmine clock.

**Closed** 2016-10-14 16:38 UTC
