### ISSUE TITLE
Jasmine does not report anything

### ISSUE THREAD

**Issue by stefanoborini** [jasmine/jasmine#1199] opened 2016-09-06 21:39 UTC
According to [jasmine documentation](https://www.npmjs.com/package/jasmine), I should be able to run the testsuite running `jasmine`.

[On this repository](http://github.com/stefanoborini/configurable-http-proxy) running jasmine in the test directory does absolutely nothing, even after exporting `JASMINE_CONFIG_PATH` to the `jasmine.json` file or passing it as argument. Note that even changing a test so that it fails, I get no result, no error, nothing. The command just returns to the prompt.

This is the content of the file

    $ more jasmine.json 
    {
      "spec_dir": "test",
      "stopSpecOnExpectationFailure": false,
      "random": false,
      "spec_files": ["*spec.js"]
    }

    (venv) sborini@MacBook-Pro:test (protocol-host-rewrite) [1 stash] $ ls `which jasmine`
    /usr/local/bin/jasmine

 package.json

    {
      "version": "1.4.0-dev",
      "name": "configurable-http-proxy",
      "description": "A configurable-on-the-fly HTTP Proxy",
      "author": "Jupyter Developers",
      "license": "BSD-3-Clause",
      "repository": {
        "type": "git",
        "url": "https://github.com/jupyterhub/configurable-http-proxy.git"
      },
      "dependencies": {
        "commander": "~2.9",
        "http-proxy": "~1.13.2",
        "lynx": "^0.2.0",
        "strftime": "~0.9",
        "winston": "~2.2"
      },
      "devDependencies": {
        "jasmine": "^2.4.1",
        "jshint": "^2.9.2",
        "nyc": "^6.4.0",
        "request": "~2",
        "ws": "^1.1"
      },
      "main": "index.js",
      "files": [
        "index.js",
        "lib/configproxy.js",
        "lib/trie.js",
        "lib/error/*.html",
        "bin/configurable-http-proxy"
      ],
      "bin": {
        "configurable-http-proxy": "bin/configurable-http-proxy"
      },
      "scripts": {
        "jshint": "jshint bin/ lib/ test/",
        "test": "nyc jasmine JASMINE_CONFIG_PATH=test/jasmine.json",
        "coverage-html": "nyc report --reporter=html",
        "codecov": "nyc report --reporter=lcov && codecov"
      }
    }

**Comment by godmar** [comment] 2016-09-07 01:01
Same here. This happens with 2.5.0, it does not happen with 2.4.1
How to reproduce:

```bash
$mkdir jasminefail
$cd jasminefail
$cat > testshort.js
describe ("A suite", function () {
  it ("contains spec with an expectation", function () {
    expect (true).toBe (true);
  });
});
$npm init -y
$npm install jasmine
$node_modules/.bin/jasmine init
$node_modules/.bin/jasmine testshort.js
```

Outputs nothing
```bash
$npm install jasmine@2.4.1
$node_modules/.bin/jasmine testshort.js
Started
.


1 spec, 0 failures
Finished in 0.008 seconds
```

**Comment by drtimwright** [comment] 2016-09-07 06:34
I've got this issue as well. Have downgraded to 2.4.1 as a fix.

**Comment by slackersoft** [comment] 2016-09-07 22:21
Closing this as a duplicate of #88. The fix should be released in v2.5.1

**Closed by slackersoft** 2016-09-07 22:21 UTC

**Comment by godmar** [comment] 2016-09-08 01:00
Can you explain how it is a duplicate of #88, an issue that dates back to 2011?

**Comment by slackersoft** [comment] 2016-09-08 02:04
Sorry, that should be jasmine/jasmine-npm#88
