### ISSUE TITLE
Jasmine html web page reports wrong line numbers

### ISSUE THREAD

**Issue by DamienCassou** [jasmine/jasmine#1598] opened 2018-09-06 11:37 UTC
Our project has a tests.html webpage which loads jasmine.js, jasmine-html.js, boot.js and our test suite. When a test fails, I get a stack trace with columns, line numbers and filenames. This is fine except that the line numbers are shifted: there is a difference between the line number as reported by Jasmine and the correct line number in the file.

My project uses webpack and cheap-eval-source-map.

## Expected Behavior

Jasmine should report:

```
TypeError: Cannot read property 'getPeriodType' of undefined
    at <Jasmine>
    at SomeModel._someMethod (webpack-internal:///./js/SomeModel.js:106:18)
```

## Current Behavior

Jasmine instead reports:

```
TypeError: Cannot read property 'getPeriodType' of undefined
    at <Jasmine>
    at SomeModel._someMethod (webpack-internal:///./js/SomeModel.js:112:18)
```

Note that line number (112) is not the same as expected one (106).

## Your Environment
* Version used: 3.2.0
* Environment name and version: Chromium 68
* Operating System and version: Linux desktop
* Link to your project: private
* Technology stack:
    - webpack: 4.3.0

**Comment by DamienCassou** [comment] 2018-09-06 11:41
I've just tried launching the same test suite with karma and I got the *wrong line numbers as well*.

**Comment by DamienCassou** [comment] 2018-10-10 05:14
When Jasmine was displaying the stacktrace in terms of minified files, I was happily using [sourcemapped-stacktrace](https://www.npmjs.com/package/sourcemapped-stacktrace). Then we updated Jasmine and got rid of sourcemapped-stacktrace because Jasmine did the job of looking into the source maps. Unfortunately, the lines numbers became slightly wrong. What about letting sourcemapped-stacktrace do the work for Jasmine?

**Comment by DamienCassou** [comment] 2019-08-19 11:57
I've just created the [smallest project](https://github.com/DamienCassou/jasmine-line-number-bug) reproducing this issue.

How to reproduce:

1. [clone the git project](https://github.com/DamienCassou/jasmine-line-number-bug) or create the files below
3. run `npx webpack  --config webpack.jasmine.config.js` inside the project directory
4. open the `tests.html` within a web browser (using `file://`)
5. Jasmine correctly says "Expected 2 to equal 3"

- **Expected**: Jasmine shows a stacktrace indicating that the problem is on line 8 (the line containing `expect`)
- **Actual**: Jasmine says that the problem is on line 10 (which only contains `});`.

Note: if you remove the useless `import` line at the beginning of`tests.js`, the line number becomes right.

## package.json

All the dependencies are the latest as of today:

```json
{
  "name": "jasmine-line-number-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "jasmine-core": "^3.4.0",
    "webpack": "^4.39.2",
    "webpack-cli": "^3.3.7"
  }
}
```

## tests.html

```html
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Client Tests</title>
    <link rel="stylesheet" type="text/css" href="./node_modules/jasmine-core/lib/jasmine-core/jasmine.css">
    <script type="text/javascript" src="./node_modules/jasmine-core/lib/jasmine-core/jasmine.js"></script>
    <script type="text/javascript" src="./node_modules/jasmine-core/lib/jasmine-core/jasmine-html.js"></script>
    <script type="text/javascript" src="./node_modules/jasmine-core/lib/jasmine-core/boot.js"></script>

    <script src="./build/jasmine.latest.js"></script>
  </head>
  <body>
  </body>
</html>
```

## tests.js

```js
import {add} from './util';

describe('line numbers', () => {
	it('should be the same', () => {
		let expected = 3;
		let actual = 1+1;

		expect(actual).toEqual(expected);
	});
});
```

## util.js

```js
export function add(a,b) {
	return a+b;
}
```

## webpack.jasmine.config.js

```js
const path = require('path');

let config = {
	entry: './tests.js',
	mode: 'development',
	output: {
		filename: 'jasmine.latest.js',
		path: path.resolve(__dirname, 'build')
	}
};

module.exports = config;
```

**Comment by sgravrock** [comment] 2020-01-11 19:49
I'm going to close this in favor of #491, which I believe it's a duplicate of. Thanks again for the repro.

**Closed by sgravrock** 2020-01-11 19:49 UTC
Labels: waiting
