### ISSUE TITLE
(Some) async test fail after update to jasmine-core 2.6.3

### ISSUE THREAD

**Issue by ambvdijk** [jasmine/jasmine#1367] opened 2017-06-08 12:56 UTC
Our build started to fail on a few async tests after updating to jasmine 2.6.3

```
TypeError: JSON.stringify cannot serialize cyclic structures.
```

It's really easy to reproduce, by creating an async test that doesn't call done

```typescript
it('tests nothing', (done) => {});
```

Might be related to commit [578f63b9bd34f75074a00b9a404b48d567dbe180](https://github.com/jasmine/jasmine/commit/578f63b9bd34f75074a00b9a404b48d567dbe180)

Using 
jasmine 2.6.0
jasmine-core 2.6.3
webpack 2.6.1
karma 1.7.0
karma-jasmine 1.1.0

**Comment by slackersoft** [comment] 2017-06-12 21:16
I'm not sure this is purely a Jasmine issue. I'm unable to reproduce the error in either a browser or raw node.js with just Jasmine itself. Additionally, Jasmine doesn't ever call `JSON.stringify`, you might check with Karma.

Hope this helps. Thanks for using Jasmine!

**Comment by jRichardeau** [comment] 2017-06-13 10:33
Hello,
I have an issue too since updating to jasmine 2.6.3 (no issue with 2.6.2) with async tests (angular promises).
My test is about routing web app with ui-router that provides an object with a list of promises which will be resolved before accessing a route.
I want to test one property of this object however when running my test on one property it runs the others (not with 2.6.2), that means I should mock all what is accessed by all these promises !

I don't know if it is clear, do you need a piece of code ?

Thank you

**Comment by slackersoft** [comment] 2017-06-19 18:12
@jRichardeau an example suite and what you expect to be happening would be super helpful.

**Comment by jRichardeau** [comment] 2017-06-21 15:06
I found what is running differently in 2.6.3, a piece of code is running while not running in 2.6.2
This is it :  `router.stateService.go('testState');`
I add a project to test it.
[jasmine-2.6.3-with-uirouter-test.zip](https://github.com/jasmine/jasmine/files/1091915/jasmine-2.6.3-with-uirouter-test.zip)

**Comment by slackersoft** [comment] 2017-06-21 18:12
The only real difference between Jasmine 2.6.3 compared to 2.6.2 is that Jasmine will make sure to go asynchronous (by calling `setTimeout`) for any spec that says it should be asynchronous, but actually calls `done()` synchronously. This could happen in a mocked out promise or timeout type environment.

I would bet that the code in your `otherwise` is being run in 2.6.2 as well, just at a different point in time that isn't causing your specs to fail. I don't see any mechanism by which your `$urlServiceProvider` would only be set up in one of the specs and not the other, so I would assume that it would run at some point. If this is _not_ what you want, you would need to mock something out to cause it to not happen.

Hope this helps. Thanks for using Jasmine!

**Comment by jRichardeau** [comment] 2017-06-22 08:28
You're right !
If I add some synchronous code in my resolve function, my test fails in 2.6.2 too...
So I was lucky that my test passed...
I'll try to mock this.
Thank you very much

**Comment by slackersoft** [comment] 2017-07-28 17:40
Sounds like this ends up being a test setup issue and not something that Jasmine itself is doing wrong, so I'm going to close this issue. If this proves not to be the case, I'd be happy to talk more about what Jasmine might be doing that causes your specs to behave differently than you expect.

Thanks for using Jasmine!

**Closed by slackersoft** 2017-07-28 17:40 UTC
