### ISSUE TITLE
Setup and Teardown misbehavior with focused specs 

### ISSUE THREAD

**Issue by diegossilveira** [jasmine/jasmine#813] opened 2015-03-30 14:49 UTC
When focusing specs with ```fdescribe```or ```fit```, setup and teardown functions ```beforeAll``` and ```afterAll``` acts like ```beforeEach``` and ```afterEach```, running once per spec instead of once per suite. When focus are removed the functions works as expected.

This spec reproduces the issue (with jasmine v2.2.1)

```javascript
fdescribe("A spec using beforeAll and afterAll", function() {
  var foo;

  beforeAll(function() {
    foo = 1;
  });

  afterAll(function() {
    foo = 0;
  });

  it("sets the initial value of foo before specs run", function() {
    expect(foo).toEqual(1);
    foo += 1;
  });

  it("does not reset foo between specs", function() {
    expect(foo).toEqual(2);
  });
});
```

**Comment by slackersoft** [comment] 2015-03-30 15:05
This was the defined behavior in the current release of jasmine. This has been changed on master.

Closing this as a dupe of #732, #758, #773, and #802

Thanks for using jasmine!

**Closed by slackersoft** 2015-03-30 15:05 UTC

**Comment by diegossilveira** [comment] 2015-03-30 20:24
Thank you for the quick reply!
I'm sorry about opening another issue on the same subject.

Just waiting for Jasmine 2.3, and congrats for such a nice project!
