### ISSUE TITLE
[Bug] Async expect fail not triggering done.fail(), timeout reached

### ISSUE THREAD

**Issue by luchillo17** [jasmine/jasmine#1373] opened 2017-06-21 13:55 UTC
### Env info

**Jasmine version:** 2.6.0
**Environment:** Node 7.10.0
**Test runner:** `karma` with `karma-jasmine`

## Description
Async tests that fail still wait for the timeout, an example below
```ts
it('Should be able to query existing products', (done) => {
        (async () => {
          try {
            const query = `{
              products {
                product_id
              }
            }`;

            const resp = await graphql(Schema, query, {}, context);
            expect(() => graphqlSpecErrorHandler(resp, `Product addProduct error`)).not.toThrow();
```
In example above the `graphqlSpecErrorHandler` function will throw, the spec is marked as failed but still waits for the timeout, in such case currently we're forced to use this boilerplate instead:
```ts
try {
    graphqlSpecErrorHandler(resp, `Product addProduct error`)
} catch (e) {
    done.fail(e)
}
```
However how to achieve the same with other simple expects? like this one for example:
```ts
expect(resp).toBeDefined()
```
If the previous expect succeeded, it would go on, but if failed, it will mark as failed but also wait for timeout, what to do here then?

**Comment by slackersoft** [comment] 2017-06-21 18:42
If a spec informs Jasmine that it is asynchronous, by receiving an argument (`done`), then it is the responsibility of that spec to invoke `done()` when all code has been completed and it safe to move on to the next thing in the queue. Since the `it` in your example never calls `done()`, Jasmine waits for the timeout and fails the spec at that point.

The goal of `done.fail()` is really to allow the option of a spec to fail outside of a specific `expect` call, like a Promise failing. A `catch` can also work, but you would still want to call `done()` explicitly in the successful case.

The next full release of Jasmine should add support for Promises and `async` functions directly to Jasmine so wrapping like your example should no longer be needed.

Closing this, since this is the currently desired functionality. Hope this helps. Thanks for using Jasmine!

**Closed by slackersoft** 2017-06-21 18:42 UTC

**Comment by luchillo17** [comment] 2017-06-21 19:05
What i mean is that current `expect` behaviour in async test only marks the test as failed, but doesn't call done so the test still waits for timeout even if the test already failed.

**Comment by slackersoft** [comment] 2017-06-21 19:08
Jasmine allows you to call `expect` multiple times in a single spec, so unless you use the "stop spec execution on expectation failure option" (which makes the `expect` throw an Error on failure), that is the expected behavior.

**Note** that async errors are only handled correctly as of 2.6.0.

**Comment by luchillo17** [comment] 2017-06-21 19:44
Didn't know such option existed, that should fix it for me.
