### ISSUE TITLE
Jasmine reports skipped tests as executed

### ISSUE THREAD

**Issue by Benjarmil** [jasmine/jasmine#1548] opened 2018-04-24 23:31 UTC
When skipping test using fdescribe in Jasmine 3.1.0 the tests come back as executed and as passing.

## Expected Behavior
Skipped tests should be listed as skipped

## Current Behavior
Skipped tests are being reported as Successful 

## Suite that reproduces the behavior (for bugs)
A well outlined suite can be [found here](https://stackoverflow.com/questions/49158691/karma-jasmine-reports-skipped-tests-as-executed)

## Context
Having to wait for thousands of tests to pretend to run is a hassle.

## Your Environment

outline [here](https://stackoverflow.com/questions/49158691/karma-jasmine-reports-skipped-tests-as-executed)

**Comment by slackersoft** [comment] 2018-04-25 00:07
It looks like you're using Karma to run your Jasmine suite. Unfortunately, the Karma maintainers haven't released a new version of Karma-Jasmine that is compatible with some of the reporting changes made in Jasmine 3.0. The pull request for 3.0 support (karma-runner/karma-jasmine#192) has been merged but not yet released. I believe this is also a duplicate of #1532 which is still open pending a release from of Karma-Jasmine which the Jasmine team has no insight or control over.

Closing. Hope this helps. Thanks for using Jasmine!

**Closed by slackersoft** 2018-04-25 00:07 UTC

**Comment by Benjarmil** [comment] 2018-04-25 16:36
Thanks for the insight, slacker. I'll keep my eye on that pr.
