### ISSUE TITLE
Jasmine does not catch error thrown from setImmediate in a Promise.

### ISSUE THREAD

**Issue by agirorn** [jasmine/jasmine#1269] opened 2017-01-31 12:17 UTC
When jasmine is run with the spec below it does not detect the failed test and it exits cleanly with an exit code of 0. This has resulted in falls positive test runs.

I ran this on jasmine version 2.5.2 in node.js version 4.5.0 and 6.9.4.

```javascript
function doIt(callback) {
  return Promise.resolve(true)
    .then(callback)
    .catch((error) => {
      setImmediate(() => {
        throw error;
      });
    });
}

describe('broken', () => {
  it('is broken', (done) => {
    doIt((value) => {
      throw new Error('I am broken!');
    }).then(done).catch(done.fail);
  });
});
```
I get this output.
```shell
➜  bug-in-jasmie ./node_modules/.bin/jasmine
Started
.


1 spec, 0 failures
Finished in 0.005 seconds

➜  bug-in-jasmie echo $?
9
```

I expected to see this.

```shell
➜  bug-in-jasmie ./node_modules/.bin/jasmine
Started
F

Failures:
1) broken is broken
  Message:
    Failed: I am broken!
  Stack:
    Error: I am broken!
        at /home/agirorn/tmp/bug-in-jasmie/spec/broken.spec.js:14:13
        at process._tickCallback (node.js:369:9)
        at Function.Module.runMain (module.js:443:11)
        at startup (node.js:139:18)
        at node.js:974:3

1 spec, 1 failure
Finished in 0.007 seconds

➜  bug-in-jasmie echo $?
1
```

**Comment by slackersoft** [comment] 2017-02-16 00:24
This looks like a duplicate of #529. This is something we're looking at fixing soon though.

Closing. Thanks for using Jasmine!

**Closed by slackersoft** 2017-02-16 00:24 UTC
