### ISSUE TITLE
ERROR: TypeError: s.substring is not a function

### ISSUE THREAD

**Issue by bushuyev** [jasmine/jasmine#1575] opened 2018-07-06 14:10 UTC
## Expected Behavior
jasmin nicely print error
## Current Behavior
fails with murky message

## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() {
  it('d', async(()=>{
//TypeError, like  (stack is from when it's wropped in try /catch)
TypeError: Cannot read property '$injector' of undefined
    at http://localhost:9876/_karma_webpack_/webpack:/src/tests/newPayment.spec.ts:214:41
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
    at AsyncTestZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:713:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:285:1)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:387:1)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:138:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:872:1
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:421:1)
    at AsyncTestZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:697:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:316:1)

}));
});

fails with 
TypeError: s.substring is not a function
    at truncate (http://localhost:9876/absolute/home/mememe/dvl/proj/proj/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?daba65c98fa088349a3e9d7df843a63405ccfc15:4652:11)
    at PrettyPrinter.append (http://localhost:9876/absolute/home/mememe/dvl/proj/proj/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?daba65c98fa088349a3e9d7df843a63405ccfc15:4637:18)
    at PrettyPrinter.emitScalar (http://localhost:9876/absolute/home/mememe/dvl/proj/proj/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?daba65c98fa088349a3e9d7df843a63405ccfc15:4478:10)
    at PrettyPrinter.format (http://localhost:9876/absolute/home/mememe/dvl/proj/proj/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?daba65c98fa088349a3e9d7df843a63405ccfc15:4434:14)
    at PrettyPrinter.emitArray (http://localhost:9876/absolute/home/mememe/dvl/proj/proj/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?daba65c98fa088349a3e9d7df843a63405ccfc15:4496:12)
    at PrettyPrinter.format (http://localhost:9876/absolute/home/mememe/dvl/proj/proj/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?daba65c98fa088349a3e9d7df843a63405ccfc15:4440:16)
    at PrettyPrinter.formatProperty (http://localhost:9876/absolute/home/mememe/dvl/proj/proj/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?daba65c98fa088349a3e9d7df843a63405ccfc15:4632:14)
    at http://localhost:9876/absolute/home/mememe/dvl/proj/proj/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?daba65c98fa088349a3e9d7df843a63405ccfc15:4594:12
    at PrettyPrinter.iterateObject (http://localhost:9876/absolute/home/mememe/dvl/proj/proj/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?daba65c98fa088349a3e9d7df843a63405ccfc15:4471:7)
    at PrettyPrinter.emitObject (http://localhost:9876/absolute/home/mememe/dvl/proj/proj/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?daba65c98fa088349a3e9d7df843a63405ccfc15:4587:26)
```

## Your Environment

* Version used:3.1.0
* Environment name and version (e.g. Chrome 39, node.js 5.4):  Chrome 66.0.3359.139 , node v8.11.3
* Operating System and version (desktop or mobile):  4.15.0-23-generic #25-Ubuntu SMP 
* Link to your project:

**Comment by slackersoft** [comment] 2018-07-20 00:50
Unfortunately, I think you might have removed a bit too much from your example code to help diagnose the underlying issue. It looks like you're using Angular and Karma to run your Jasmine suite, and based on the initial error message with `$injector`, probably angular-mocks or something similar. My best guess based on what I see here is that something in your test setup is causing one of those things to break and when Jasmine tries to format the error message one of the objects in the tree provides it's own `toString()` function (or possibly `jasmineToString()`) and the object returned by that isn't fully a `String` in that it doesn't have a `substring` function on it.

For now, you're probably going to have to dig into your tests and figure out what is causing the original error, but I would be happy to review a pull request for Jasmine that allowed it to cope with `toString` or `jasmineToString` functions that return objects that don't appear to be strings.

Hope this helps. Thanks for using Jasmine!

**Comment by marinvirdol** [comment] 2018-09-18 12:06
I experience the same issue

**Comment by slackersoft** [comment] 2018-10-02 19:49
@marinvirdol If you have any other information or a small sample suite that reproduces the error, we can look into it a bit more, but at this point, I don't have enough information to provide any more help than [above](https://github.com/jasmine/jasmine/issues/1575#issuecomment-406456415).

**Comment by fr0** [comment] 2018-10-31 22:13
I experienced this issue today:

```
TypeError: s.substring is not a function
    at truncate (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?1f336da4025323945fc818c69bdc564a85081e4e:5289:11)
    at PrettyPrinter.append (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?1f336da4025323945fc818c69bdc564a85081e4e:5274:18)
    at PrettyPrinter.emitScalar (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?1f336da4025323945fc818c69bdc564a85081e4e:5115:10)
    at PrettyPrinter.format (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?1f336da4025323945fc818c69bdc564a85081e4e:5071:14)
    at PrettyPrinter.emitArray (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?1f336da4025323945fc818c69bdc564a85081e4e:5133:12)
    at PrettyPrinter.format (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?1f336da4025323945fc818c69bdc564a85081e4e:5077:16)
    at PrettyPrinter.formatProperty (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?1f336da4025323945fc818c69bdc564a85081e4e:5269:14)
    at http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?1f336da4025323945fc818c69bdc564a85081e4e:5231:12
    at PrettyPrinter.iterateObject (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?1f336da4025323945fc818c69bdc564a85081e4e:5108:7)
    at PrettyPrinter.emitObject (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?1f336da4025323945fc818c69bdc564a85081e4e:5224:26)
```
I put breakpoints in jasmine.js and discovered that the [`truncate` function](https://github.com/jasmine/jasmine/blob/110c092c9ece00cd6c882bd573b911c35ff73478/src/core/PrettyPrinter.js#L263) was being given a numeric value where it expects a string.

The numeric value was being passed in from `PrettyPrinter.append` via `PrettyPrinter.emitScalar` via [`PrettyPrinter.format`](https://github.com/jasmine/jasmine/blob/110c092c9ece00cd6c882bd573b911c35ff73478/src/core/PrettyPrinter.js#L50).

The object being formatted is a `ZoneTask` instance from [zone.js](https://github.com/angular/zone.js/). It's odd that the `ZoneTask.toString()` value would return a number rather than a string (this seems like a bug in zone.js).

**Comment by slackersoft** [comment] 2018-11-02 18:31
Given that Jasmine is calling `toString()` but getting a number back, this definitely sounds like an issue with zone.js and not necessarily Jasmine.

**Comment by Jonatino** [comment] 2018-11-19 19:04
Also getting this error.

```
ERROR: TypeError: s.substring is not a function
TypeError: s.substring is not a function
    at truncate (http://localhost:9876/absoluteC:/git/UWF/AngularApps/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?a1eb923d36d1ca53b93387cb5312668373ad9ef2:4943:11)
    at PrettyPrinter.append (http://localhost:9876/absoluteC:/git/UWF/AngularApps/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?a1eb923d36d1ca53b93387cb5312668373ad9ef2:4928:18)
    at PrettyPrinter.emitScalar (http://localhost:9876/absoluteC:/git/UWF/AngularApps/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?a1eb923d36d1ca53b93387cb5312668373ad9ef2:4769:10)
    at PrettyPrinter.format (http://localhost:9876/absoluteC:/git/UWF/AngularApps/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?a1eb923d36d1ca53b93387cb5312668373ad9ef2:4725:14)
    at PrettyPrinter.emitArray (http://localhost:9876/absoluteC:/git/UWF/AngularApps/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?a1eb923d36d1ca53b93387cb5312668373ad9ef2:4787:12)
    at PrettyPrinter.format (http://localhost:9876/absoluteC:/git/UWF/AngularApps/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?a1eb923d36d1ca53b93387cb5312668373ad9ef2:4731:16)
    at PrettyPrinter.formatProperty (http://localhost:9876/absoluteC:/git/UWF/AngularApps/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?a1eb923d36d1ca53b93387cb5312668373ad9ef2:4923:14)
    at http://localhost:9876/absoluteC:/git/UWF/AngularApps/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?a1eb923d36d1ca53b93387cb5312668373ad9ef2:4885:12
    at PrettyPrinter.iterateObject (http://localhost:9876/absoluteC:/git/UWF/AngularApps/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?a1eb923d36d1ca53b93387cb5312668373ad9ef2:4762:7)
    at PrettyPrinter.emitObject (http://localhost:9876/absoluteC:/git/UWF/AngularApps/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?a1eb923d36d1ca53b93387cb5312668373ad9ef2:4878:26)
```

**Comment by Jonatino** [comment] 2018-11-19 20:01
https://github.com/angular/zone.js/issues/1153#issuecomment-440021415

zone.js will be working on a fix in the case where `ZoneTask.toString()` returns a number instead of a string.

**Comment by slackersoft** [comment] 2019-02-22 01:47
It looks like this has been fixed in zone.js v0.8.27. Please update your dependency there and try this again. Please let us know if you're still seeing the issue so we can look into it further.

**Closed** 2019-05-21 00:18 UTC
