### ISSUE TITLE
spyOn(myObject, 'myMethod').with('this argument').andReturn('that');

### ISSUE THREAD

**Issue by bzitzow** [jasmine/jasmine#1053] opened 2016-02-23 23:51 UTC
I would like to set a return value for a spy but only when it is called with a specific argument

```
spyOn(myObject, 'myMethod').with('this argument').andReturn('that');
```

This would return nothing
```
myObject.myMethod('not a recognized argument');
```

This would return 'that':
```
myObject.myMethod('this argument');
```

I couldn't find this brought up in the issues previously. Is this something that I could offer a pull request and add the feature? Am I missing something as to why this has not been implemented already?

**Comment by slackersoft** [comment] 2016-02-24 00:11
This looks like a duplicate of #720. We're looking at ways to allow a user to specify they're own SpyStrategy.

Closing. Thanks for using Jasmine!

**Closed by slackersoft** 2016-02-24 00:11 UTC
