### ISSUE TITLE
Angular 6.1.0 TypeError on is not a function

### ISSUE THREAD

**Issue by theS3ns** [jasmine/jasmine#1602] opened 2018-09-13 09:43 UTC
## Expected Behavior

TypeError on is not a function

## Suite that reproduces the behavior (for bugs)

##Component
```javascript
ngOnInit() {
    const that = this;
    if ( this._var === undefined ) {
      // Saved div with id for later click events
      this._var = document.getElementById('element');
    }
    this._var.on('plotly_click', function( event ) {
      that.customFunction( event );
    });
  }
```
##Test
```javascript
  let component: CustomComponent;
  let fixture: ComponentFixture<CustomComponent>;

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [ CustomComponent]
    })
    .compileComponents();
  });

  beforeEach(() => {
     fixture = TestBed.createComponent(CustomComponent);
     component = fixture.componentInstance;
     fixture.detectChanges();
  });

  it('should create', () => {
     expect(component).toBeTruthy();
  });
```

## Your Environment

* Version used:
"jasmine-core": "~2.99.1",
* Environment name and version (e.g. Chrome 39, node.js 5.4):
Chrome: 68.0.3440.106
* Operating System and version (desktop or mobile):
Desktop

**Comment by slackersoft** [comment] 2018-09-26 00:39
I'm not exactly sure what error you're seeing or what line it might be coming from, so I'm guessing a bit based on the code you've pasted in. If I had to guess, I'd say your `_var` variable is `undefined` (or `null` or something else that doesn't have an `on` function), so that when you call `this._var.on(...)` you get the error you're seeing.

Since this looks like it's being caused by not having an element on the page with the id `element`, it doesn't sound like this is an issue with Jasmine itself, so I'm going to close this.

Hope this helps. Thanks for using Jasmine!

**Closed by slackersoft** 2018-09-26 00:39 UTC
